### ISSUE TITLE
Not able to star this project

### ISSUE THREAD

**Issue by pwab** [adbar/trafilatura#104]
I never encountered such an error message on github before but I'm not allowed to star this repository. This is the message I receive:

![grafik](https://user-images.githubusercontent.com/19271185/127281551-1c9b3002-7db4-4b65-9097-4ac54423402b.png)

Any ideas?

**Comment by adbar** [comment]
Hi @pwab, thanks for your interest! My GitHub nickname seems to collide with ad blockers which restrict URLs of the form `/adbar/`.

If you disable the ad blocker in your browser if should work.

**Comment by pwab** [comment]
Hey @adbar! Well that seems to be the case here. I deactivated ublock origin and had no problems after that. I would never have thought of that 😅 

(Funny thing by the way: I was able to create the issue but it blocked me from commenting on it.)
