### ISSUE TITLE
Why h1,h2,hn tags are converted into tag head ? 

### ISSUE THREAD

**Issue by christophebe** [adbar/trafilatura#109]
Why h1,h2,hn tags are converted into <head rend="hn"> ... </head> ?
and how to avoid this ? 

Thanks

**Comment by adbar** [comment]
Hi @christophebe,

At first the project focused on converting HTML documents to an XML format compatible with these [guidelines](https://tei-c.org/release/doc/tei-p5-doc/en/html/index.html).
The `hN` information is still present in the attribute, for example `<h3>` → `<head rend="h3">`.

**Comment by christophebe** [comment]
Hello, 

Thanks for your reply. 

Is it possible to keep the html as it is ? I would like to just extra the html code of the main content. 

or an alternative : convert it in markdown. 

Thanks

**Comment by adbar** [comment]
For now the output gets converted whatever happens, I see two options:

- use trafilatura's wrappers around [external libraries](https://trafilatura.readthedocs.io/en/latest/corefunctions.html#external-processing)
- if you use TXT output with formatting (`include_formatting=True`) what you get is actually markdown

**Comment by LaundroMat** [comment]
Hi, I created a [PR](https://github.com/adbar/trafilatura/pull/257) to change the formatting of `<head>` XML tags in Markdown, so that

    <head rend="h2">Title</head>

becomes

    ## Title

instead of 

    == Title ==
