### ISSUE TITLE
Unexpected lack of whitespace before/after ref tags in XML output

### ISSUE THREAD

**Issue by adri1wald** [adbar/trafilatura#113]
To reproduce:

```python
import trafilatura
url = 'https://www.vox.com/22638093/air-conditioning-worsens-climate-change-ac?utm_source=pocket-newtab-global-en-GB'
html = trafilatura.fetch_url(url)
xml = trafilatura.extract(
    html,
    output_format='xml',
    include_formatting=True,
    include_images=True,
    include_links=True
)
print(xml)
```

Example of problematic output:

`Phasing out HFCs, which are thousands of times more powerful than carbon dioxide, is one of the most<ref target="https://drawdown.org/solutions/refrigerant-management">critical actions</ref>the world can take this decade to curb climate change.`

What I expected (👆 = where the whitespace should be):

`Phasing out HFCs, which are thousands of times more powerful than carbon dioxide, is one of the most👆<ref target="https://drawdown.org/solutions/refrigerant-management">critical actions</ref>👆the world can take this decade to curb climate change`

**Comment by adbar** [comment]
Hi @adri1wald, that's a bug indeed, thanks for filing the issue.

**Comment by adri1wald** [comment]
Hey @adbar, thanks for your response!

I discovered this also happens with other formatting tags like `hi` and `code`. If you run the following, you can see many examples in the output:

```python
import trafilatura
url = 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/RetrievingObjectVersions.html'
html = trafilatura.fetch_url(url)
xml = trafilatura.extract(
    html,
    output_format='xml',
    include_formatting=True,
    include_images=True,
    include_links=True
)
print(xml)
```

For now I am transforming the xml output using beautifulsoup to fix it as best I can.

**Comment by adbar** [comment]
Hi @adri1wald, how do you currently fix this? We could use this as a quick hack.

I'm not sure where the bug happens, it doesn't affect the Markdown output so it's related to the conversion from HTML to XML.

**Comment by adbar** [comment]
It's now fixed, at least as paragraphs are concerned (cc @adri1wald).
