### ISSUE TITLE
Inclusion of Mercury Spotlight in the benchmarks.

### ISSUE THREAD

**Issue by ydennisy** [adbar/trafilatura#114]
Hi @adbar 

Came across [Mercury](https://github.com/postlight/mercury-parser) and wanted to share the project with you, would be great to include in the benchmarks and maybe get your take on their approach VS yours.

Cheers!
D

**Comment by adbar** [comment]
Hi @ydennisy, for reproducibility reasons I primarily include tools using Python. Let's see if the article extraction benchmark above can test it.

**Comment by ydennisy** [comment]
Thanks @adbar !!
