### ISSUE TITLE
Cannot import Trafilatura

### ISSUE THREAD

**Issue by SkateRock123** [adbar/trafilatura#117]
ImportError: cannot import name 'Document' from 'readability' (C:\Users\name\AppData\Roaming\Python\Python38\site-packages\readability\__init__.py)

**Comment by felipehertzer** [comment]
Hi @SkateRock123, Readability is dependencie of Trafilatura. If you cloned the repository, I recommend run setup.py, or installing via pip `pip install trafilatura`

**Comment by adbar** [comment]
Hi @SkateRock123, installation via the ``pip`` package manager should work on all systems. Have you tried it? If it doesn't work, could you please give us more info on your system? (Python and operating system versions)

**Comment by adbar** [comment]
Hi @SkateRock123, any feedback on this?

**Comment by SkateRock123** [comment]
I apologize for not responding. It was a enviroment issue on my end. Trafilatura has been great!

**Comment by adbar** [comment]
@SkateRock123 thanks!
