### ISSUE TITLE
Design a logo for the software

### ISSUE THREAD

**Issue by adbar** [adbar/trafilatura#120]
Displaying a logo on the homepage and the docs pages could help make `trafilatura` more visible.

**Comment by amirouche** [comment]
What is the intended meaning of `trafilatura` in english?

**Comment by amirouche** [comment]
According to the README it is "wire drawing" https://wikiless.org/wiki/Wire_drawing?lang=en

**Comment by adbar** [comment]
Yes, that's it, it's about wire drawing. I think of it as an operation which refines and filters.

See https://duckduckgo.com/?q=wire+drawing&t=canonical&iax=images&ia=images

It's also how certain pasta types are made: https://duckduckgo.com/?q=trafilatura+pasta&t=canonical&iar=images&iax=images&ia=images

**Comment by amirouche** [comment]
How the work of the software `trafilatura` is related to "wire drawing"?

**Comment by adbar** [comment]
It's metaphorical.
