### ISSUE TITLE
trafilaturan.fetch_url failed to terminate

### ISSUE THREAD

**Issue by Guest400123064** [adbar/trafilatura#128]
Hi,

I am a graduate student developing a data pipeline for semantic analysis over news articles and I just encountered this great package. However, after several experiments, there seem to be some problem with `trafilaturan.fetch_url` with the following [link](http://naplesherald.com/2018/02/07/thousands-african-migrants-protest-israel-deportations/) or `"http://naplesherald.com/2018/02/07/thousands-african-migrants-protest-israel-deportations/"`

After digging into the source code in the `downloads.py`, I discovered that `HTTP_POOL.request('GET', url, headers=_determine_headers(config))` under function `_send_request()` cannot terminate. I wonder if it is caused by the `RETRY_STRATEGY` setting because if I fetch the above URL using `response = requests.get`, the `response.status_code` is `503`. My current workaround is simply to fetch the HTML myself. I wonder if there is any way that I can set a timeout?

```
python version = '3.9.7'
trafilatura.__version__ = '0.9.3'
urllib3.__version__ = '1.26.7'
```

Thank you!

Best,
Yuxuan

**Comment by vbarbaresi** [comment]
Hi,
I was able to reproduce the issue
The bug happens with the `http://` URL, which actually returns `301` response.
Note that `requests.get` automatically follows redirects (unless you set `allow_redirects=False`), so it can mask some redirection issues.

```
trafilatura -u http://naplesherald.com/2018/02/07/thousands-african-migrants-protest-israel-deportations/ -vv
```
It's stuck after this line:
```
DEBUG:urllib3.util.retry:Incremented Retry for (url='/2018/02/07/thousands-african-migrants-protest-israel-deportations/'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
```
If we use the `https://` URL, it stops immediately after the `503` response.

```
trafilatura -u https://naplesherald.com/2018/02/07/thousands-african-migrants-protest-israel-deportations/ -vv

ERROR:trafilatura.downloads:retries/redirects: https://naplesherald.com/2018/02/07/thousands-african-migrants-protest-israel-deportations/ HTTPSConnectionPool(host='naplesherald.com', port=443): Max retries exceeded with url: /2018/02/07/thousands-african-migrants-protest-israel-deportations/ (Caused by ResponseError('too many 503 error responses'))
DEBUG:trafilatura.cli_utils:No result for URL: https://naplesherald.com/2018/02/07/thousands-african-migrants-protest-israel-deportations/
DEBUG:trafilatura.cli_utils:0 URLs could not be found
```

The reason it's stuck after the 301 is that the server sends a header `Retry-After: 86400` and our retry strategy respects it. So trafilatura would wait for 24 hours before the next retry.

The fix would be to patch urllib3 retry strategy with: `respect_retry_after_header=False` 
I tested and it didn't work out of the box. It seems that we don't pass the retry strategy to all requests.

**Comment by vbarbaresi** [comment]
This seems to be a `urllib3` issue. Retry strategy is actually ignored. I opened https://github.com/urllib3/urllib3/issues/2475

**Comment by Guest400123064** [comment]
Thank you very much for your reply!
