### ISSUE TITLE
Tables not removed

### ISSUE THREAD

**Issue by pieterhartel** [adbar/trafilatura#136]
I have just installed trafilatura 0.9.3 with Python 3.9.6.

The attached file (apache.txt, which is actually a html file) contains tables that are not removed when I run:
$ trafilatura --no-tables <apache.txt

[apache.txt](https://github.com/adbar/trafilatura/files/7491052/apache.txt)

**Comment by adbar** [comment]
Yes, I can reproduce the bug.

**Comment by adbar** [comment]
Hi @pieterhartel, thank you for reporting the bug. It is now fixed and it was also an opportunity to simplify the code.

**Comment by pieterhartel** [comment]
Thanks @adbar. Does this mean that "pip install trafilatura" also enjoys the bug fix?

**Comment by adbar** [comment]
Not yet, for that to happen you need to install the cutting-edge version 
straight from the repository:
`pip3 install -U git+https://github.com/adbar/trafilatura.git`

**Comment by pieterhartel** [comment]
I think that the bug is still there.

```
$ trafilatura --version
Trafilatura 0.9.3 - Python 3.9.9
$ trafilatura --no-tables <scam.txt | head
|EU BENZOS
|
|http://wd2vdnd5nmto767l.onion/
|
|Kingdom_Come
|
|http://nfm4hgt5m6dcmlm5.onion/
|
|Queen Galaxy
|
```

**Comment by pieterhartel** [comment]
[scam.txt](https://github.com/adbar/trafilatura/files/7627150/scam.txt)

**Comment by adbar** [comment]
OK, I'll look into it.

**Comment by pieterhartel** [comment]
Thanks. I suspect it has something to do with nested tables.
