### ISSUE TITLE
Interaction with internet archives (API and formats)

### ISSUE THREAD

**Issue by adbar** [adbar/trafilatura#148]
- expose Python function to retrieve links from the Internet Archive
The relevant code for the command-line interface is here:
https://github.com/adbar/trafilatura/blob/7cc59e872652cd01329078614ac9e47ab9e0e04a/trafilatura/cli_utils.py#L310

- and/or accept WARC as input format

**Comment by four43** [comment]
WARC would be very interesting as a direct input method.

**Comment by adbar** [comment]
I'm now against it, Trafilatura can focus on extraction and navigation on live web pages and leave the rest to the users.

There are nice packages to interact with web archives and with the WARC format. I'll add a few hints to the docs shortly.
