### ISSUE TITLE
Keep output file name same as input file name

### ISSUE THREAD

**Issue by sajidrahman** [adbar/trafilatura#15]
First of all, let me thank you for working on this amazing tool! 

One quick feature request: is it possible to keep the output file name same as the input file names, when running on the command line? Also, I see this error **# ERROR: file too small** in command line but while running the API programmatically, it doesn't provide any meaningful message when the extraction is not successful. Can we fix it?

**Comment by adbar** [comment]
Hi, thank you for your input, I might also need to keep the input file names so I implemented this function straightaway in ecdf206 :)

The issue you're mentioning next is something different, could you please open an another issue and describe the problem with a concrete example?

**Comment by mzeidhassan** [comment]
Hi @adbar 
Sorry to bother you on a closed issue, but it is not clear to me how to preserve source file names. I am using the following command to convert local HTML files to text files, but the file names are very random and has nothing to do with the source HTML file names. Any idea? 

`trafilatura --inputdir "./" --outputdir "C:/output/" -out txt`

![image](https://user-images.githubusercontent.com/7589948/166585325-fb602971-76c1-4c1f-9228-4a3ad4117c4a.png)

**Comment by adbar** [comment]
As a side note: the CLI option to preserve file names is `--keep-dirs`.
