### ISSUE TITLE
CLI: run as server

### ISSUE THREAD

**Issue by adbar** [adbar/trafilatura#151]
Implement the ability to listen on a specified port for further incoming documents:
- e.g. using the standard library [wsgiref](https://docs.python.org/3/library/wsgiref.html)
- [http.server](https://docs.python.org/3/library/http.server.html) is not recommended for production but usable

**Comment by lalitpagaria** [comment]
How about using FastAPI and uvcorn?

In past for Obsei (https://github.com/obsei/obsei-rest), I used these techs. They are also suitable for production.
Along with FastAPI and Uvcorn, I used apscheduler which can help with repetitive jobs.

**Comment by adbar** [comment]
It is maybe a little convoluted, I would prefer a default Python-WSGI solution but I take note of it.

**Comment by adbar** [comment]
Note: see the API as described in corresponding [doc page](https://trafilatura.readthedocs.io/en/latest/usage-api.html).

**Comment by lalitpagaria** [comment]
This looks good @adbar, also good idea in making API commercial.
