### ISSUE TITLE
Requesting to re-release with less strong copyleft license

### ISSUE THREAD

**Issue by lalitpagaria** [adbar/trafilatura#155]
First, thanks for such a wonderful tool. Myself maintainer of [Obsei](https://github.com/obsei/obsei), using Trafilatura for web crawling interface. Our users are very happy about the output of Trafilatura.

As we envision the use of Obsei as an SDK and an independent tool., hence I released it under a more permissible license Apache 2.0.
I think Trafilature also can be used both ways.

Recently I am analyzing Obsei's dependencies (refer to this https://github.com/obsei/obsei/issues/220) to remove or replace strong copyleft dependencies, in order to remove license conflict.
Trafilture is released under GPL3+ along with its few dependencies. Hence requesting if there is any chance to re-release it under less string copyleft license more specifically if used as SDK or dependency. I also understand that it is not an easy task as 3-4 Trafilture dependencies are released under GPL3+. For now, I am thinking to make Trafilture as optional dependencies and living it up to the user to handle license conflict but like to solve it properly, hence suggestions are welcome.

**Comment by adbar** [comment]
Hi @lalitpagaria, thanks for your feedback!

I believe the solution you suggest (i.e. an optional download) is doable, I can also suggest interesting at arms length (for instance with on the command-line).

**Comment by lalitpagaria** [comment]
Thanks, @adbar for your input.

> I can also suggest interesting at arms length (for instance with on the command-line).

The above solution with Rest interface would be good instead of CLI

**Comment by adbar** [comment]
@lalitpagaria Would you be interested in working on a REST API for the library? (see #151)
