### ISSUE TITLE
Running Trafilatura in Browser?

### ISSUE THREAD

**Issue by vprelovac** [adbar/trafilatura#157]
I am wondering if you tried running Trafilatura in browser as a replacement for readability.js? This could be done with something like https://pyodide.org

**Comment by adbar** [comment]
Thanks for the suggestion, I'll think about it.

**Comment by adbar** [comment]
Hi @vprelovac, I just learned that Python is moving towards running in the browser, so I'll close this thread and hope that future versions allow for the code to run without modification :crossed_fingers:
