### ISSUE TITLE
xml extraction leads to <graphic> tags in the wrong place.

### ISSUE THREAD

**Issue by joschu** [adbar/trafilatura#158]
```
import trafilatura
downloaded = trafilatura.fetch_url('https://en.wikipedia.org/wiki/Laplace_distribution')
ex=trafilatura.extract(downloaded,output_format='xml',include_images=True)
print(ex)
```
In several places, I see a `<graphic>...</graphic>` region in the wrong place.
For example, trafilatura produces
```
    <p>where <graphic> is the generalized exponential integral function </graphic></p>
```
from
![image](https://user-images.githubusercontent.com/144178/148621885-f690dd3f-8ba9-4760-bbd3-03a5815d4c89.png)

**Comment by adbar** [comment]
Hi @joschu, thanks for your feedback. I can reproduce the bug.

The HTML syntax behind Wikipedia's formulas is quite complex and it seems to confuse the extractor. This is how `E_{n}()` is coded:

```
<span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle E_{n}()}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle scriptlevel="0" displaystyle="true">
        <msub>
          <mi>E</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mi>n</mi>
          </mrow>
        </msub>
        <mo stretchy="false">(</mo>
        <mo stretchy="false">)</mo>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle E_{n}()}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/293d17c59c25748cbad9dbc20020c1649a98313e" class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -0.838ex; width:4.743ex; height:2.843ex;" alt="{\displaystyle E_{n}()}">
```

**Comment by szhengac** [comment]
@adbar Is there progress on this issue? based on my testing, `alt` from wikipedia formulas still cannot be parsed and kept in the output.

**Comment by adbar** [comment]
@szhengac Nothing new at the moment but the `alt`  issue you're mentionning is only loosely related to this one, can you give an example?

**Comment by szhengac** [comment]
@adbar If you use wiki page: https://en.wikipedia.org/wiki/Condorcet_paradox with `extract`, you will find the math equations are missing, e.g., the one near `Using the [central limit theorem](https://en.wikipedia.org/wiki/Central_limit_theorem), we show that`

**Comment by adbar** [comment]
Math elements are still missing but then again the case is quite specific. I'm closing this now as the original problem (misplaced graphic tags) now appears to be solved.
