### ISSUE TITLE
Article cuts off early after advertisement `<div>`

### ISSUE THREAD

**Issue by naftalibeder** [adbar/trafilatura#159]
Given the request for [this article](https://www.newyorker.com/magazine/2021/11/08/energy-and-how-to-get-it):

```
html = fetch_url("https://www.newyorker.com/magazine/2021/11/08/energy-and-how-to-get-it")
extr = bare_extraction(
    html,
    output_format="xml",
    include_formatting=True,
    include_images=True,
    include_links=True,
)
```

the output xml ends on the `<p>` tag containing:

> ...the mitochondria, calling the shots.

In the source, the next element is a `<div>` with class `BaseWrap-sc-TURhJ RowWrapper-egDQBE eTiIvU hVsKfd full-bleed-ad row-mid-content-ad`, and then the content continues after that.

How might the parser continue, and get all the content?

———

EDIT: I just realized that this matches your comment [here](https://github.com/adbar/trafilatura/issues/85#issuecomment-876483685), and true enough, reducing `BODY_XPATH` to an empty array does catch the entire article. Is this still not something that might be fixable? Seems like the New Yorker is a bad citizen here. Potentially the code could do a check for additional siblings with the same class name as the found article?

**Comment by adbar** [comment]
This is indeed related to #85. The idea with additional siblings seems good but in my experience opening the search space leads to boilerplate content really fast.

**Comment by adbar** [comment]
@naftalibeder I will close this thread, we can discuss it further in #85.
