### ISSUE TITLE
Broken parsing of empty anchors

### ISSUE THREAD

**Issue by alex-bender** [adbar/trafilatura#161]
Function extract with `include_links=True` results in an error in case if anchor is empty: `ex('<a></a><b>Jump to se</b>')`
Function `ex` stands for extract. For some reason I had to provide additional filler of string, so `<b>` could be any other tag. The problem is in empty `<a>` tag. Having any text inside that `a` tag results in a correct result.

```~/anaconda3/lib/python3.7/site-packages/trafilatura/xml.py in replace_element_text(element, include_formatting, include_links)
    203                 breakpoint()
    204 
--> 205             element.text = ''.join(['[', element.text, ']', '(', element.get('target'), ')'])
    206         except TypeError:
    207             LOGGER.warning('missing link attribute: %s %s', element.text, element.attrib)

TypeError: sequence item 1: expected str instance, NoneType found

def ex(html):
    text = trafilatura.extract(
        html,
        include_links=True,
    )
    return text
In [135]: ex('<a></a><b>Jump to se</b>')```

**Comment by adbar** [comment]
Hi @alex-bender, you're right, I didn't think empty links would be an issue but they do exist.

**Comment by adbar** [comment]
It should be fixed so I'm closing the issue.
