### ISSUE TITLE
Broken parsing of images

### ISSUE THREAD

**Issue by alex-bender** [adbar/trafilatura#162]
I'm not quite sure what's wrong with images but here is reproducer:
```
$ curl https://en.wikipedia.org/wiki/Tribe > /tmp/tribe.html
$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> html_wiki_tribe = open('/tmp/tribe.html').read()
... text = trafilatura.extract(
...     html_wiki_tribe,
...     include_images=True
... )
~/anaconda3/lib/python3.7/site-packages/trafilatura/xml.py in xmltotxt(xmloutput, include_formatting, include_links)
    272             LOGGER.debug('unexpected element: %s', element.tag)
    273             returnlist.extend([textelement, ' '])
--> 274     return sanitize(''.join(returnlist))
    275 
    276 

TypeError: sequence item 6: expected str instance, NoneType found

```
---
UPD
Looks like this could help:
![image](https://user-images.githubusercontent.com/3628862/150209903-6556cffd-04b9-4689-9e16-22b5c51261cd.png)

**Comment by adbar** [comment]
Hi @alex-bender, thanks, I can reproduce the bug.

The line you highlighted should be fine though, IMO the `get()` method offers a default instead of returning `None`, that's what the `''` is about here.

**Comment by alex-bender** [comment]
yes, this `''` was my fix to that issue

**Comment by adbar** [comment]
My bad, I'm trying it and it works ;)

**Comment by alex-bender** [comment]
that's great. Can you think about any other tags which you haven't handle?
Also, there is a .sourceline attribute on elements but always empty. What does it stand for?

**Comment by alex-bender** [comment]
It looks like lines 255 and 257 which contains alt and title from image could be also guarded by `get(XXX, '')`

**Comment by adbar** [comment]
I'm currently checking, I don't think so, the other attributes are preceded by `if ... is not None` so they're accounted for.
The code was only problematic if the source was missing, I'll add it to the tests.

**Comment by alex-bender** [comment]
ok, cool. Thanks for support

**Comment by adbar** [comment]
It's now fixed and I would close the issue.

I couldn't pinpoint the underlying issue however. Something is wrong with the extraction of certain image `src` attributes in the Wikipedia page you've taken as example. Images aren't my top priority, feel free to look for further information.

My guess would be
a) that the code the function below isn't working as it should, or
b) the necessary attribute info gets removed along the way during HTML conversion
https://github.com/adbar/trafilatura/blob/e72a6d474a0badae4416f13ffda17f9d2b8acbee/trafilatura/core.py#L345

**Comment by alex-bender** [comment]
Thanks a lot!
