### ISSUE TITLE
Handling of `teaser` class

### ISSUE THREAD

**Issue by naftalibeder** [adbar/trafilatura#164]
In [this](https://www.washingtonpost.com/politics/courts_law/neil-gorsuch-sonia-sotomayor-masks-supreme-court/2022/01/19/7977831a-7946-11ec-9102-d65488c31bb1_story.html) Washington Post article, the first two paragraphs are contained in a node with the class `teaser-content`.

Because of [this clause](https://github.com/adbar/trafilatura/blob/master/trafilatura/xpaths.py#L109) in `DISCARD_XPATH`, those paragraphs are excluded. Obviously, removing those lines 'fixes' the issue.

I understand why something marked with `teaser` would seem not to be part of the article. Any ideas for handling this?

**Comment by adbar** [comment]
As I said in the thread above the case of teaser paragraphs is complex.

I chose to deal with the case using the `favor_recall` argument to the `bare_extraction()` and the `extract()` functions. If you set it to `True` you should get to see such paragraphs in the output.

**Comment by naftalibeder** [comment]
That’s great, thanks.

Semi-related note, having `favor_precision` and `favor_recall` as two separate args opens up the possibility of sort of meaningless combinations (`True` and `True`).

I know it’d be breaking, but a change to `precision=high|medium|low` or something like that might be easier to understand and configure.

**Comment by adbar** [comment]
I'll think of it, but "precision=low" does not quite mean the same as "favor recall".
