### ISSUE TITLE
Adding storage plugins

### ISSUE THREAD

**Issue by lalitpagaria** [adbar/trafilatura#172]
Currently, trafilatura supports storing the output in files.

How about a base interface class that can be extended to send output to any other place as well.

For example File, S3, DB, Data Lake or API, etc.

**Comment by adbar** [comment]
Hi @lalitpagaria, it is a design decision of mine to leave that question to the user. The multiple output formats offered serve as input to most databases, especially CSV and JSON. From there is up to the users to define how they will store and query the data.
Do you see another well-known format which could be added?

**Comment by lalitpagaria** [comment]
I see. I understood correctly you like to keep design simple which is a good idea.
For now, I think you already covered well-known formats. `parquet` might be help users to create condensed files.

**Comment by adbar** [comment]
Thanks for the suggestion! I believe people using parquet can build an input pipeline using one of the formats offered by Trafilatura so I'm closing the issue for now.
