### ISSUE TITLE
How to pass "you are not a robot" with trafilature

### ISSUE THREAD

**Issue by Konstantina-Lazaridou** [adbar/trafilatura#18]
Hey, I am using trafilatura to get the content of newspapers. Is it possible to overpass captcha within trafilatura? For instance, Bloomberg is returning "To continue, please click the box below to let us know you're not a robot. Please make sure your browser supports JavaScript and cookies and that you are not blocking them from loading. For more information you can review..." when I try to access a news article.

**Comment by adbar** [comment]
Hi, it is indeed a problem, so far nothing has been implemented  to bypass captchas or anti-scraping mechanisms. You could use another tool to emulate browser behavior (see for example [headless browsers](https://www.scrapehero.com/how-to-prevent-getting-blacklisted-while-scraping/#unique-identifier6)) and then pass the HTML source straight to `trafilatura`.
