### ISSUE TITLE
Problems with unescape on JSON

### ISSUE THREAD

**Issue by felipehertzer** [adbar/trafilatura#180]
Hey @adbar I'm having problems to loads the JSON generated via trafilatura. When some field contains quotes I can't load it in python. 
Current:
```json
"title": "Avast survey: "Australian" elderly highest among internet non-users"
```
Should be:
```json
"title": "Avast survey: \"Australian\" elderly highest among internet non-users"
```

Is this function necessary for some reason? Thank you.
https://github.com/adbar/trafilatura/blob/776eb916df9c7b9f7fb75e06aa765fd7d638ff42/trafilatura/xml.py#L50

**Comment by adbar** [comment]
Hi @felipehertzer, you're right, it was a problem.
