### ISSUE TITLE
[Feature request] Add site configuration

### ISSUE THREAD

**Issue by phongtnit** [adbar/trafilatura#193]
Hi,

I love your script and used trafilatura in some scraped projects. In many cases, there are many errors in scraped content. Do @adbar consider add site configuration?

The idea is that your script will support configuration of a site to extract accurate content based on instruction commands in site config, for example, a site configuration:

`json file: site_config/youtube.com.json`

```
{
  "title": "//xpath_of_title",
  "author": "//xpath_of_author",
  "tags": "//xpath_of_tags",
  "categories": "//xpath_of_categories",
  "body": "//xpath_of_article_body",
  "strip": "//xpath_in_article_body_should_be_stripped",
  "test_url": "https://www.youtube.com/watch?v=.*"
}
```

The idea is not new, if a url supported in site_config and the url matched with `test_url` regex in site_config, the script will process priority with these special configurations. If not, trafilatura will extract content metadata normally as it does.

With the feature, it will be easier to extract exact data and other users can add site configuration, so Trafilatura will extract data more accurately.

Thanks for your reading and considering,

**Comment by adbar** [comment]
Hi @phongtnit, thanks for the suggestion. It looks like an interesting 
additional functionality.

Would you be interested in drafting a corresponding pull request?

**Comment by adbar** [comment]
Trafilatura adopts a generic approach, there are enough scraping libraries supporting such functions.
