### ISSUE TITLE
updated benchmarks

### ISSUE THREAD

**Issue by derekperkins** [adbar/trafilatura#196]
there have been several significant releases since the last benchmark 10 months ago, I'm curious if there have been any notable changes there.
https://trafilatura.readthedocs.io/en/latest/evaluation.html#results-2021-06-07

**Comment by adbar** [comment]
Hi @derekperkins, thanks for your interest!
I'm planning to release an updated benchmark soon. As you'd assume Trafilatura has gotten slightly better over time, I am currently adding more web pages to the evaluation in order to see if it generalizes well (and it should).

**Comment by adbar** [comment]
Hi @derekperkins, I just updated the benchmarks :+1:

**Comment by derekperkins** [comment]
Thanks!
