### ISSUE TITLE
Can't get content from http site

### ISSUE THREAD

**Issue by LeMoussel** [adbar/trafilatura#20]
With cocon.se site `fetch_urlr ` result is `None`. 

**Test code**
```
import trafilatura

if __name__ == '__main__':
  downloaded = trafilatura.fetch_url('http://cocon.se/')
  if downloaded is None:
    print('Error downloaded content')
    exit(1)
  result = trafilatura.extract(downloaded)
  print(result)
```

**Result**
`Error downloaded content`

The reason for this error is that no UA is specified in the header of the request.
With this code, It's OK
```
  response = requests.Session().get('http://cocon.se/', timeout=30, verify=False, allow_redirects=True, headers={'User-Agent': 'Mozilla/5.0'})
  downloaded = response.text
  result = trafilatura.extract(downloaded)
  print(result)
```

**Comment by adbar** [comment]
Thanks, I added a user-agent string in e974b52.

So far it's defined in `settings.py`, if you wish to change it just [clone the repository](https://docs.github.com/en/free-pro-team@latest/github/using-git/which-remote-url-should-i-use), edit `settings.py` and reinstall the package locally (`pip install -U . ` in the home directory of the cloned repository).

I'll implement reading settings from a config file later on (#6).

**Comment by LeMoussel** [comment]
OK. Thanks.
