### ISSUE TITLE
ModuleNotFoundError: No module named '_lzma' in 1.2.1

### ISSUE THREAD

**Issue by marban** [adbar/trafilatura#203]

**Comment by adbar** [comment]
@marban, thanks for your feedback, does that work for you?
https://stackoverflow.com/questions/59690698/modulenotfounderror-no-module-named-lzma-when-building-python-using-pyenv-on

**Comment by adbar** [comment]
@marban Did that solve your issue?

**Comment by mrienstra** [comment]
Worked for me!

See also:
https://github.com/pyenv/pyenv/issues/99
https://github.com/pyenv/pyenv/wiki/Common-build-problems/6dae5cd9c3f0c399e368a3a2e5120fb9debac366
