### ISSUE TITLE
None type handling

### ISSUE THREAD

**Issue by vprelovac** [adbar/trafilatura#206]
```
link="https://www.abc.net.au/news/2022-05-08/native-americans-fight-to-keep-traditions-alive-after-covid/101045668"

 trafilatura.bare_extraction(
                trafilatura.fetch_url(link), include_comments=False
            )

```
crashes with 'incompatible input type', <class 'NoneType'>

**Comment by vprelovac** [comment]
Few other urls with same issue

https://www.sciencedirect.com/science/article/pii/S2352396422002225
https://www.technology.org/2022/05/05/internet-at-the-speed-of-light/ 

This one bit different:
https://aomedia.org/av1/ 'NoneType' object has no attribute 'startswith'

**Comment by vprelovac** [comment]
Great when do you plan to have next release?

**Comment by adbar** [comment]
In the next 5-10 days.

**Comment by adbar** [comment]
@vprelovac it's out.
