### ISSUE TITLE
Remove headers

### ISSUE THREAD

**Issue by nehasrikn** [adbar/trafilatura#207]
Thank you for such an incredibly useful package!

I'm building a corpus of documents which I'm using to automatically generate questions. For a given document, I'd like to solely extract non-header text (i.e only the paragraph text). Is this supported by the `trafilatura.extract()` method? That method returns only a `str`, so I'm not sure if it's possible.

**Comment by adbar** [comment]
Hi @nehasrikn, thanks for your feedback!

- If you choose XML as output format you could then select the elements you wish to retain, here `<p>`. See [this doc page](https://trafilatura.readthedocs.io/en/latest/usage-python.html) for more information on extraction with Python and customization.
- If you know how to work with the lxml library you could also use the [bare_extraction](https://trafilatura.readthedocs.io/en/latest/corefunctions.html#trafilatura.bare_extraction) function to work on the result right away.

**Comment by nehasrikn** [comment]
Wonderful, I look into this! Thank you!

**Comment by nehasrikn** [comment]
Wonderful, I'll look into this! Thanks!

**Comment by nehasrikn** [comment]
Not sure if there's an easy fix this for this, but using XML as the output format won't preserve order on the page right? It groups everything together by tag, so if I have a `<p>` tag immediately followed by a `<list>`, there's no way to recover order this way right? 

Essentially, I'd just like to extract all the main text on the page (concatenated together _in order_) that isn't header text.

I think I'm looking for some combination between the text extraction method (output=txt) which does preserve order, and the selection of certain tags allowed by the xml output format.

It sounds like as is, there's no clean way to do this, but would appreciate anymore insight you have!

**Comment by adbar** [comment]
Hi @nehasrikn, if you use XML as output format you can apply tree traversal methods with the tool of your choice (e.g. LXML) in order to select the nodes you're interested in.
