### ISSUE TITLE
Incorrect recognition

### ISSUE THREAD

**Issue by Lucabenj** [adbar/trafilatura#208]
In this case, the essential part of the article is not recognized from the surrounding context: https://bit.ly/3woC4M2 , https://bit.ly/39ZnenF , https://bit.ly/38r1TTJ

**Comment by adbar** [comment]
Thanks @Lucabenj, I added the articles to a list of known problems. The first one is really tricky though, the main text is really short compared to the rest.

**Comment by adbar** [comment]
I closing this since the issue is now mentioned in #4.
