### ISSUE TITLE
trafilatura behing a proxy

### ISSUE THREAD

**Issue by hpiedcoq** [adbar/trafilatura#210]
Hi,

Trafilatura doesn't seem to work behind our proxy.

Config : a docker container, with openjdk11-slim-bullseye.
A dig soa works like a charm (so internet is up).

print env says : 

```
no_proxy=*.c**************,127.0.0.0/8,10.0.0.0/8,*************12,192.168.0.0/16
HOSTNAME=***********************
JAVA_HOME=/usr/local/openjdk-11
PWD=/app
HOME=/
LANG=C.UTF-8
https_proxy=http://p********************************:xxxx
TERM=xterm
no_proxy=*.c**************,127.0.0.0/8,10.0.0.0/8,*************12,192.168.0.0/16
SHLVL=1
HTTPS_PROXY=http://p********************************:xxxx
HTTP_PROXY=http://p********************************:xxxx
http_proxy=http://p********************************:xxxx
PATH=/usr/local/openjdk-11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app
RELEASE=***********
DEBIAN_FRONTEND=noninteractive
JAVA_VERSION=11.0.15
```
Any idea?

**Comment by adbar** [comment]
Hi @hpiedcoq, I'm afraid the question is too specific for me to reproduce or to answer.

The underlying library used for downloads is `urllib3`, I suggest you try to run a simple script with a [pool manager](https://urllib3.readthedocs.io/en/stable/advanced-usage.html) (i.e. like trafilatura) and see if it works. If it doesn't then it would be an issue related to urllib3.

Another option would be to use another download utility and then process the HTML files locally (on your docker instance) with trafilatura.
