### ISSUE TITLE
Question: Can the program also extract the creation time?

### ISSUE THREAD

**Issue by Lucabenj** [adbar/trafilatura#214]
Can the program also extract the time the page was created, with the date, where the document contains it?

**Comment by adbar** [comment]
Yes, my other library `htmldate` is used to find the publication date of web pages. It is included along with other metadata for output formats other than TXT.

**Comment by Lucabenj** [comment]
So, is it enough to use `htmldate` syntax in `Trafilatura`?

**Comment by adbar** [comment]
If by that you mean the [parameters mentioned in the docs](https://trafilatura.readthedocs.io/en/latest/usage-python.html?highlight=htmldate#date-extraction), yes.

**Comment by Lucabenj** [comment]
Solved. TNX!
