### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by kinoute** [adbar/trafilatura#216]
Hello,

I use Trafilatura to extract thousand of web pages' content and I'm dealing with increasing memory usage when using Trafilatura – around 1mb per page processed. It depends of the web page though. Sometimes the increase is smaller.

My containers quickly reach the memory limit and get OOM killed. When using vanilla `requests` only, I also see a small increase but nothing compared to Trafilatura.

Specs:
- Python 3.8.12
- Trafilatura 1.2.2

Code / website to reproduce:

```python3
import os
import psutil
import requests
import time
for idx in range(100):
    resp = requests.get("https://www.ifri.org/fr/espace-media/lifri-medias/thierry-de-montbrial-principale-rupture-systeme-international-fut-1989-non")
    tmp_var = trafilatura.extract(
                resp.content,
                output_format='json',
                include_images=False,
                date_extraction_params={'extensive_search': True},
                include_comments=False,
    )
    process = psutil.Process(os.getpid())
    print(idx, ":", process.memory_info().rss / 1024 ** 2)
    time.sleep(2)
```

Results:

```
0 : 117.90234375
1 : 118.87109375
2 : 119.70703125
3 : 120.6015625
4 : 121.3359375
5 : 122.21484375
6 : 122.96875
7 : 123.83203125
8 : 124.49609375
9 : 125.50390625
10 : 126.6171875
11 : 127.3125
12 : 128.0390625
13 : 128.7265625
14 : 129.37109375
15 : 129.68359375
16 : 130.41015625
17 : 131.31640625
18 : 131.9765625
19 : 133.4765625
20 : 133.98046875
^C---------------------------------------------------------------------------
```

Same loop with `requests` only:

```python3
import os
import psutil
import requests
import time
for idx in range(100):
    resp = requests.get("https://www.ifri.org/fr/espace-media/lifri-medias/thierry-de-montbrial-principale-rupture-systeme-international-fut-1989-non")
    process = psutil.Process(os.getpid())
    print(idx, ":", process.memory_info().rss / 1024 ** 2)
    time.sleep(2)
```

Results:

```
0 : 54.3125
1 : 54.40234375
2 : 54.4453125
3 : 54.45703125
4 : 54.49609375
5 : 54.5
6 : 54.5234375
7 : 54.5234375
8 : 54.54296875
9 : 54.54296875
10 : 54.54296875
11 : 54.55078125
12 : 54.55078125
13 : 54.5625
14 : 54.5625
15 : 54.5625
16 : 54.5625
17 : 54.5625
18 : 54.76171875
19 : 54.79296875
20 : 54.80078125
^C---------------------------------------------------------------------------
```

**Comment by adbar** [comment]
Hi @kinoute, thanks for your feedback!

I also noticed this problem a while ago and couldn't spot where the leak happens. After a few tests I am now at least able to restrict the search to the date extraction component: if no date (i.e. no metadata) is requested, then the progression of memory usage is not as steep.

**Comment by kinoute** [comment]
With only 10 iterations (from my example above), here is the thread that allocates RAM the most:

<img width="1551" alt="Screenshot 2022-06-15 à 12 34 40" src="https://user-images.githubusercontent.com/623763/173807847-df4d7930-2c91-4160-a1cb-7a15516a48c4.png">

**Comment by adbar** [comment]
Both lines are related to `lxml` which is mostly written is C, maybe something is wrong there but it will be tricky to track. I use both `fromstring` and `deepcopy` elsewhere without running into this problem.

**Comment by adbar** [comment]
It should mostly be fixed, see above.

**Comment by adbar** [comment]
The new `htmldate` version should fix the problem.

Those wishing to benefit from it can upgrade with `pip3 install -U htmldate`.

**Comment by adbar** [comment]
@kinoute @dmoklaf FYI It turns out there is a poorly documented cache in the standard library `urllib.parse` which caches all URLs processed.

I discovered it by chance and wrote a patch which will be included in future versions:
https://github.com/adbar/courlan/pull/34
