### ISSUE TITLE
Classifying webpage as dynamically generated

### ISSUE THREAD

**Issue by nlist2** [adbar/trafilatura#222]
Some results from dynamically generated webpages are quite abbreviated. It may be helpful to classify scraped webpages as dynamic in some way -- potential to make new method: is_dynamic()

**Comment by adbar** [comment]
Hi @nlist2, could you please provide an example of dynamically generated webpage? Do you mean lists of articles like in home and category pages?

**Comment by adbar** [comment]
@nlist2 Could you please provide an example as explained above?
