### ISSUE TITLE
Add argument to use archive.org as a backup in fetch_url()

### ISSUE THREAD

**Issue by vprelovac** [adbar/trafilatura#225]
Here are few pages where trafilatura breaks, with error ('incompatible input type', <class 'NoneType'>)

https://www.thekitchn.com/pan-fried-chicken-thighs-recipe-23394671 
https://www.cubbyathome.com/sweet-and-tangy-watermelon-lemonade-80017159
https://moneywise.com/employment/how-to-reject-a-job-offer-letter-with-samples
https://www.thekitchn.com/savory-spice-capitol-hill-seasoning-review-23409172
https://www.retailmenot.com/blog/free-home-depot-kids-workshop-kit.html 
https://www.apartmenttherapy.com/mindy-kaling-kitchen-booth-37107922 
https://diziet.dreamwidth.org/11840.htm 
https://slowernews.substack.com/p/2022-springi 
https://www.thecipherbrief.com/a-path-of-cooperation-and-opportunity-between-the-u-s-and-the-uae 
https://www.technology.org/2022/07/20/mobile-app-helps-detect-skin-cancer-in-older-patients/ 
https://knowablemagazine.org/article/health-disease/2022/lasting-anguish-moral-injury 
https://www.sciencedirect.com/science/article/abs/pii/S0022395622003557 
https://support.rstudio.com/hc/en-us/articles/5773239924375-RStudio-Electron-Preview-Release-Notes
http://advances.sciencemag.org/content/4/8/eaat3276 
https://app.dataherald.com/visualization/create/feed-search 
http://thenextweb.com/news/web-inventor-tim-berners-lee-screw-web3-my-decentralized-internet-doesnt-need-blockchain 

Hope you have enough to find the problem!

**Comment by adbar** [comment]
Hi @vprelovac, I cannot reproduce the bug, which version and which options/arguments are you using?

`trafilatura -u "https://www.thekitchn.com/pan-fried-chicken-thighs-recipe-23394671"` returns the text, also with different formats.

**Comment by vprelovac** [comment]
Trafilatura 1.2.2 - Python 3.8.10

I get empty result when called from command line (and exception when called from API)

# trafilatura -u "https://www.thekitchn.com/pan-fried-chicken-thighs-recipe-23394671"
# trafilatura -u "http://thenextweb.com/news/web-inventor-tim-berners-lee-screw-web3-my-decentralized-internet-doesnt-need-blockchain"
#

"Normal" URL works:

# trafilatura -u "https://www.cnn.com/2022/07/20/politics/trump-january-7-outtakes-message-supporters-house-hearing/index.html"
(CNN)The House committee investigating the insurrection plans to show footage at Thursday's hearing of then-President Donald Trump having difficulty working through efforts to tape a message to his supporters on January 7, 2021, the day after the Capitol riot, sources familiar with the committee's plans tell CNN.
The outtakes, first reported by The Washington Post, were part of production of a speech Trump gave the night after the riot. They show Trump having a difficult time working through the effort to tape the message. Trump refused to say the election results had been settled and attempted to call the rioters patriots. He also went to great lengths to not accuse them of any wrongdoing.
A spokesman for the January 6 select committee declined to comment on the outtakes.
Rep. Jamie Raskin, a Maryland Democrat who is a member of the committee, confirmed Wednesday night to CNN's Anderson Cooper that the panel has the outtakes and plans to share some of them during the hearing.
"The President displayed extreme difficulty in completing his remarks," Raskin said on "Anderson Cooper 360."
"It's extremely revealing how exactly he went about making those statements, and we're going to let everybody see parts of that," he added.
Rep. Adam Schiff, another committee member, told CNN's Don Lemon later Wednesday that the outtakes "will be significant in terms of what the President was willing to say and what he wasn't willing to say."
The California Democrat said the outtakes will show "all of those who are urging him to say something to do something to stop the violence. You'll hear the terrible lack of a response from the President, and you'll hear more about how he was ultimately prevailed upon to say something and what he was willing to say and what he wasn't."
The video tape outtakes will be one part of a larger presentation during which the committee plans to detail Trump's lack of attention to the ongoing riot. The committee has said it will focus on the 187 minutes that Trump sat back, refusing to act, as the Capitol was under siege. Some committee members have described this as Trump's "dereliction of duty."
Rep. Adam Kinzinger, a retiring Republican from Illinois who is one of the two GOP members on the select committee, on Thursday morning teased some footage from the depositions that will be aired as part of the hearing. In a video montage, several aides describe Trump watching TV in the White House dining room instead of taking action during the crisis.
"Donald Trump is a disgrace to America," Kinzinger wrote on Twitter.
This story has been updated with additional details Wednesday.

**Comment by vprelovac** [comment]
Perhaps a resonable quick 'fix' would be adding a proper error message for download fail.

A more ambitious one would be to provide a paramater for alternate URL (for example proxied) so trafilatura can try with that should the main URL fail.

**Comment by adbar** [comment]
Concerning pycurl, you can install it separately, Trafilatura will use it, which will change download parameters, it may be the reason it works for me. I definitely need to add this to the docs.

Working on a proper error message is definitely a good way to provide info on such errors.

**Comment by adbar** [comment]
Sidenote: this is related to #223.

**Comment by adbar** [comment]
@vprelovac as for the alternative URL source it exists on the command-line with the argument `--archived`:
https://trafilatura.readthedocs.io/en/latest/usage-cli.html#internet-archive

**Comment by vprelovac** [comment]
FYI I installed pycurl and it still fails for all the above URLs. (there is no indicationthat pycurl is used though)

**Comment by vprelovac** [comment]
> @vprelovac as for the alternative URL source it exists on the command-line with the argument `--archived`:
> https://trafilatura.readthedocs.io/en/latest/usage-cli.html#internet-archive

This is exactly what we need :)

To clarify, when you specify archived it tires it only if the original link download fails?

How is this param enabled using fetch_url() in Python?

**Comment by adbar** [comment]
Yes, the CLI utility only tries if the download fails. Please beware 
that retrieving URLs from archive.org is (understandably) costly in 
terms of time.

As of now this parameter cannot be enabled for `fetch_url()`, I will 
think about it.

**Comment by vprelovac** [comment]
> As of now this parameter cannot be enabled for `fetch_url()`, I will think about it.

Do or do not, there is no try :)
