### ISSUE TITLE
Fail to scrape some websites

### ISSUE THREAD

**Issue by felipehertzer** [adbar/trafilatura#228]
Hey @adbar 

I'm having problem to scraper few websites.
Example: https://www.natgeokids.com/au/discover/animals/general-animals/10-tiger-facts/

On Python it returns None, on cli it returns '! D O C T Y P E h t m l >'

But if I change the code to load HTML it works. 

**Current:**
https://github.com/adbar/trafilatura/blob/e4e4406b73c2ac3fa6ec443813201be6fa3cfb3c/trafilatura/utils.py#L170

**Changed:**
```python
    try:
        tree = fromstring(htmlobject.encode('utf8'), parser=HTML_PARSER)
    except ValueError:
        # "Unicode strings with encoding declaration are not supported."
        try:
            tree = fromstring(htmlobject, parser=HTML_PARSER)
        except Exception as err:
            LOGGER.error('lxml parser bytestring %s', err)
    except Exception as err:
        LOGGER.error('lxml parsing failed: %s', err)
```
```json
{"title": "10 terrific tiger facts for kids - National Geographic Kids", "author": "Admin...
```

Thank you.

**Comment by adbar** [comment]
Hi @felipehertzer, I cannot reproduce the bug, it may be related to LXML and to #166.

There are good reasons why I do thing in this order, LXML has its quirks and it makes sense to pass a decoded string, e.g. it is faster.

However there may be better options than `fromstring(htmlobject.encode('utf8'))` on `ValueError` only. Here is an example, could you please try this code and modify it to suit your need if it doesn't? (paste it at line 168 in `utils.py`)

```
    fallback_parse = False
    # use Unicode string
    try:
        tree = fromstring(htmlobject, parser=HTML_PARSER)
    except ValueError:
        # "Unicode strings with encoding declaration are not supported."
        fallback_parse = True
        try:
            tree = fromstring(htmlobject.encode('utf8'), parser=HTML_PARSER)
        except Exception as err:
            LOGGER.error('lxml parser bytestring %s', err)
    except Exception as err:
        LOGGER.error('lxml parsing failed: %s', err)
    if tree is None or not isinstance(tree, HtmlElement) and fallback_parse is False:
        try:
            tree = fromstring(htmlobject.encode('utf8'), parser=HTML_PARSER)
        except Exception as err:
            LOGGER.error('lxml parser bytestring %s', err)
```

Note: a `try-except-else` clause would also be an option here.

**Comment by felipehertzer** [comment]
Hi @adbar, thanks for the reply.

I changed the code as you mentioned, but it didn't work. The tree variable is not None at this point. The content is ```<html element at 0x109d50db0>```

I checked the length of the tree and when it works the size is 2 but when it fails the size is 1. 

I saw in the last line of load_html that you are checking the length of the tree and I changed the line below but I'm not sure if it fits with your idea:
``` python
if (tree is None or not isinstance(tree, HtmlElement) or len(tree) < 2) and fallback_parse is False:
```

**Comment by adbar** [comment]
Yes, let's try `len(tree) < 2` instead of the `isinstance` condition. 
Does that work for you?

**Comment by felipehertzer** [comment]
Yes, it works with this line:

```python
if (tree is None or len(tree) < 2) and fallback_parse is False:
```

**Comment by adbar** [comment]
Thanks for your feedback, please try the code with the commit above and close the bug if it's fixed.

**Comment by felipehertzer** [comment]
Thanks @adbar, It is working now.
