### ISSUE TITLE
Keep orderedness information of lists

### ISSUE THREAD

**Issue by DavidNemeskey** [adbar/trafilatura#229]
I was wondering if it is possible to know whether a `<list>` in the extracted output came from an `<ul>` or an `<ol>`. Even with `include_formatting` (which I don't need), this information is omitted.

I saw that `<head>`, for instance, retains the level in the `rend` attribute. A similar attribute would be handy in `<list>` as well.

On a related note, description lists (`<dl>`s) are handled even worse, as both `<dt>`s and `<dd>`s are extracted as separate `<item>`s. Something like this:
- _dt1_: _dd1_
- _dt2_: _dd2_

would probably serve the purpose better.

**Comment by adbar** [comment]
Hi @DavidNemeskey, thanks for your feedback. It is definitely doable, I would split your remark into two parts:

- [ ] add type information to `<list>`, possibly in a `rend` attribute
- [ ] check extraction order of `<dl>` elements and (optionally) add a numbered attribute

**Comment by DavidNemeskey** [comment]
@adbar thanks, that would be great. Let me know if can be of any help.

**Comment by adbar** [comment]
Hi @DavidNemeskey, I believe I addressed both concerns, does that work for you?

**Comment by DavidNemeskey** [comment]
Will take a look in a few days, thanks!
