### ISSUE TITLE
Using headline instead of name in JSON-LD metadata

### ISSUE THREAD

**Issue by posobin** [adbar/trafilatura#23]
Trafilatura extracts some metadata from JSON-LD tag if it is available. In particular, it tries to search for the title in the "headline" property of the JSON-LD tag, but looks like the headline is not necessarily the title. For example, look at this wikipedia page: https://en.m.wikipedia.org/wiki/Semantic_satiation
The JSON-LD is:
```json
{
"@context":"https:\/\/schema.org","@type":"Article",
"name":"Semantic satiation",
"url":"https:\/\/en.wikipedia.org\/wiki\/Semantic_satiation",
"sameAs":"http:\/\/www.wikidata.org\/entity\/Q226007",
"mainEntity":"http:\/\/www.wikidata.org\/entity\/Q226007",
"author":{"@type":"Organization","name":"Contributors to Wikimedia projects"},
"publisher":{"@type":"Organization","name":"Wikimedia Foundation, Inc.","logo":{"@type":"ImageObject","url":"https:\/\/www.wikimedia.org\/static\/images\/wmf-hor-googpub.png"}},
"datePublished":"2006-07-12T09:27:14Z",
"dateModified":"2020-08-31T23:55:26Z",
"headline":"psychological phenomenon in which repetition causes a word to temporarily lose meaning for the listener"
}
```
Most of the wikipedia pages are like this.

The title of the page is in the "name" property, and the "headline" property contains a short tagline instead. So trafilatura gives the tagline instead of the title as the title of the page. It probably makes sense to search for the "name" property first? Though it would be hard to extract with a regex: "name" also appears in subfields, like in the "author" property above, so would need to parse the json properly.

There was even a proposal to get rid of the headline property and replace it with "name" or with "title": https://github.com/schemaorg/schemaorg/issues/205

**Comment by adbar** [comment]
Thank you for the detailed bug report! Full-fledged parsing would indeed be an option, for now I solved the bug in a straightforward way in 675c764.
