### ISSUE TITLE
Extraction bug: `body > ul` is omitted

### ISSUE THREAD

**Issue by rozbb** [adbar/trafilatura#233]
Trafilatura omits the `<ul>` elements on [this](https://blog.cr.yp.to/20220805-nsa.html) (admittedly extremely barebones) blog post. For example, look at the the paragraph beginning "Did NSA admit that, okay". An unordered list of 6 points follows that paragraph. Trafilatura does include them in its extraction, skipping straight to "George also challenged researchers".

**Comment by adbar** [comment]
Hi @rozbb, that's correct, it's a bug concerning document iteration or extraction.

(For further reference, the archived link: https://web.archive.org/web/20220808001620/https://blog.cr.yp.to/20220805-nsa.html)

**Comment by adbar** [comment]
Hi @rozbb, I just tried to address the issue. The problem here resides in the minimalistic HTML design: just a series of elements in the body. Most of the time lists are undesirable elements in such contexts.

I chose to include them if `favor_recall=True` is set (see commit above). If recall is your priority you could also check out `trafilatura.html2txt()`.
I hope it helps.

**Comment by rozbb** [comment]
This is quite helpful. Thank you!

**Comment by rozbb** [comment]
It looks like adding `--recall` doesn't help actually. The following line outputs nothing:
```
./bin/trafilatura --verbose --recall -u "https://blog.cr.yp.to/20220805-nsa.html" | grep "couldn't use"
```
Whereas the original article has a bullet point containing the string "couldn't use".

Am I using `--recall` wrong?

**Comment by adbar** [comment]
Hi @rozbb, it works for me, please update to the latest version from the repository to benefit from the newest changes:
`pip install --force-reinstall git+https://github.com/adbar/trafilatura`

**Comment by rozbb** [comment]
Sorry for the delay. Yes, you're right I just forgot to update. Thanks again!
