### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ReySadeghi** [adbar/trafilatura#236]
Hi,
I tried using "bare_extraction" and "extract" to fetch some news websites but for some URLs , I got this error:
`'NoneType' object is not subscriptable`

example_url= 'https://www.isna.ir/news/1400070704627/%D8%AA%D8%B5%D8%A7%D9%88%DB%8C%D8%B1-%D8%AE%D8%A7%D8%B1%D9%82-%D8%A7%D9%84%D8%B9%D8%A7%D8%AF%D9%87-%D8%A7%D8%B2-%D8%B2%D9%85%DB%8C%D9%86-%DA%A9%D9%87-%D8%AA%D9%88%D8%B3%D8%B7-%D9%85%D8%A7%D9%87%D9%88%D8%A7%D8%B1%D9%87-%D9%84%D9%86%D8%AF%D8%B3%D8%AA-%D8%AB%D8%A8%D8%AA-%D8%B4%D8%AF%D9%87-%D8%A7%D9%86%D8%AF'

any idea?

**Comment by adbar** [comment]
Hi @ReySadeghi, I cannot reproduce the bug with standard extraction, are you using the latest version of the software and are you using particular options?

**Comment by ReySadeghi** [comment]
yes, I used version of 1.3.0
my code is this:

`import trafilatura
  downloaded = trafilatura.fetch_url(url)
  json_file=trafilatura.bare_extraction(downloaded, include_links=True)
  #json_file= trafilatura.extract(downloaded, output_format='json')

  date=json_file['date']`

**Comment by ReySadeghi** [comment]
Hi again,
thanks for your response.
also I tried both methods : "bare_extraction" and "extract", 
but I couldn't download and got the Error.

I tried download section that you mentioned, but nothing happen.
I think maybe my URL is under restriction by trafilatura.
I also tried with vpn but it doesn't solve.
could you please try to download this URL:

url="https://www.isna.ir/news/1400070704627/%D8%AA%D8%B5%D8%A7%D9%88%DB%8C%D8%B1-%D8%AE%D8%A7%D8%B1%D9%82-%D8%A7%D9%84%D8%B9%D8%A7%D8%AF%D9%87-%D8%A7%D8%B2-%D8%B2%D9%85%DB%8C%D9%86-%DA%A9%D9%87-%D8%AA%D9%88%D8%B3%D8%B7-%D9%85%D8%A7%D9%87%D9%88%D8%A7%D8%B1%D9%87-%D9%84%D9%86%D8%AF%D8%B3%D8%AA-%D8%AB%D8%A8%D8%AA-%D8%B4%D8%AF%D9%87-%D8%A7%D9%86%D8%AF"

**Comment by adbar** [comment]
Hi @ReySadeghi I have trouble downloading the page as well with Python, I'm afraid this problem exceeds the scope of the library.

This solution works on the command-line:
`wget -O - "https://www.isna.ir/news/1400070704627/%D8%AA%D8%B5%D8%A7%D9%88%DB%8C%D8%B1-%D8%AE%D8%A7%D8%B1%D9%82-%D8%A7%D9%84%D8%B9%D8%A7%D8%AF%D9%87-%D8%A7%D8%B2-%D8%B2%D9%85%DB%8C%D9%86-%DA%A9%D9%87-%D8%AA%D9%88%D8%B3%D8%B7-%D9%85%D8%A7%D9%87%D9%88%D8%A7%D8%B1%D9%87-%D9%84%D9%86%D8%AF%D8%B3%D8%AA-%D8%AB%D8%A8%D8%AA-%D8%B4%D8%AF%D9%87-%D8%A7%D9%86%D8%AF" | trafilatura`

**Comment by luguoyixiazi** [comment]
I got this error because 
``` python
# path: trafilatura/htmlprocessing.py
377 HTML_CONVERSIONS = {
378     "list": "ul",
379     "item": "li",
380     "code": "pre",
381     "quote": "blockquote",
--> 382     "head": lambda elem: f"h{int(elem.get('rend')[1:])}",
```
elem.get('rend') got None

**Comment by adbar** [comment]
The issue is not reproducible anymore, probably because it is solved.
