### ISSUE TITLE
Only one author extracted, even when there are multiple

### ISSUE THREAD

**Issue by atestu** [adbar/trafilatura#24]
Example article: https://www.nytimes.com/2020/10/19/us/politics/trump-ads-biden-election.html

This is authored by _Maggie Haberman, Shane Goldmacher and Michael Crowley_, but trafilatura will only show the first one. They are all in the JSON-LD so I think they should all be extracted, and author should be an array.

**Comment by adbar** [comment]
Solved in e014a72, thanks for the bug report!

**Comment by atestu** [comment]
That was fast, thank you! I think you mean this commit btw https://github.com/adbar/trafilatura/commit/c2632a855c621a4083a040b9a186aa145b52ac0b

What do you think of using a different separator than the comma though? I could see it because problematic to split up with suffixes ("Joe Schmo, Sr, Tara Doe, MD"). You could use a semicolon instead?

Other idea that I think would be ideal: deprecate "author" (string) and introduce "authors" (array)

**Comment by adbar** [comment]
Yes, you're right about the commit.

I added a semi-colon in 2f04e508a35fc34ff36dd315ba216c17ec1ad5d1 and won't implement the rest at this time, but feel free to write a pull request concerning a list of authors.

**Comment by atestu** [comment]
Much appreciated, thank you
