### ISSUE TITLE
Use a different delimiter for user agent setting

### ISSUE THREAD

**Issue by k-sareen** [adbar/trafilatura#240]
Hi! First of all, thank you for your amazing work. This is a great library!

I was trying to have a list of multiple user strings in order to rotate between them. However, user strings can actually contain the character `,` such as the user string: "`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko)`". Since the library uses `split(',')`, we can get malformed user agents such as "` like Gecko)`" in the example above.

May I recommend changing how to provide multiple user agents in the settings list? I would recommend using a different delimiter (maybe `;;`) that is not used in normal user agents. I can make a quick and simple PR for this as well if you want.

**Comment by k-sareen** [comment]
Actually now that I think about it, the newline character (`\n`) would be good enough:
```
USER_AGENTS =
    Firefox
    Chrome
    Safari
```
Then a user agent can be easily retrieved by essentially doing:
```python3 
agent = config.get("DEFAULT", "USER_AGENTS").strip().split("\n")[random_int]
```

**Comment by adbar** [comment]
Hi @k-sareen, it is indeed a problem, thanks for suggesting a change.
