### ISSUE TITLE
Elements without text can sometimes result in `element.text is None` unexpectedly

### ISSUE THREAD

**Issue by mrienstra** [adbar/trafilatura#247]
Related to / continuation of #161.

Seems to be quite an edge-case, but under certain circumstances, `TypeError: sequence item 1: expected str instance, NoneType found` can be thrown by certain combinations of elements, the underlying pattern being that they either have no text within them (but still something), or are empty after being sanitized (I'm guessing).

Below are two test files that trigger this bug.

`temp_strong.html`:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>A weird bug</title>
  </head>
  <body>
      <div>
        <h1>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h1>
        <h2>Sed et interdum lectus.</h2>
        <p>Quisque molestie nunc eu arcu condimentum fringilla.</p>
        <!-- strong can be changed to b, em, i, u, or kbd -->
        <strong><a></a></strong>
        <h2>Aliquam eget interdum elit, id posuere ipsum.</h2>
        <p>Phasellus lectus erat, hendrerit sed tortor ac, dignissim vehicula metus.</p>
      </div>
  </body>
</html>
```

---

`temp_em.html`:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>A weird bug</title>
  </head>
  <body>
    <div id="content">
      <h1>A header</h1>
      <h2>Very specific bug so odd</h2>
      <h3>Nested header</h3>
      <p>Some "hyphenated-word quote" followed by a bit more text line.</p>
      <em><p>em improperly wrapping p here</p></em>
      <p>Text here</p>
    </div>
  </body>
</html>
```

```
cat ./temp_strong.html | trafilatura --verbose --formatting --links --images
cat ./temp_em.html | trafilatura --verbose --formatting --links --images
```

Note that these test files are quite temperamental. I tried to reduce them as much as possible, and was surprised to discover that making even very small changes to them will result in the bug no longer being triggered, particularly with the second one.

**Comment by adbar** [comment]
Hi @mrienstra, thanks for reporting the issue and suggesting a solution!

I don't primarily use the extraction options you mention, I mostly added them on users' request, I'm glad to see that changing a few lines of code already makes a difference.
