### ISSUE TITLE
Get only part of the text on the website?

### ISSUE THREAD

**Issue by Rapid1898-code** [adbar/trafilatura#258]
Hello - i tried the module but i only get a part of the text on the website -

eg. for 
https://www.sfgate.com/business/article/A-better-fit-Online-retailers-create-custom-13340732.php?t=33cb161585

I only get this text-part:
```
This is a carousel. Use Next and Previous buttons to navigate
9
After she had her second child, Meghan Litchfield had trouble finding clothes the right size. A former Gap strategy manager, she knew that fit was the top reason for people not buying clothes and for online returns.
“Sizing is a broken system,” she said. “It assumes women’s bodies are standard, which they’re not, and it’s also really arbitrary.”
```

But there is much more text on the website?
Is it somehow possible to get the whole text?

**Comment by Rapid1898-code** [comment]
Thx for your effort

**Comment by adbar** [comment]
The extraction isn't perfect but at least the whole text is now in the output. I'm closing this issue for now.
