### ISSUE TITLE
Fails to parse on mangled DOCTYPE

### ISSUE THREAD

**Issue by bnewbold** [adbar/trafilatura#26]
This HTML document fails to extract any content using current trafilatura: <https://firstmonday.org/ojs/index.php/fm/article/download/10274/9729?inline=1>

From experimentation, I believe this is due to the mangled DOCTYPE line:

    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" 2012"http://www.w3.org/TR/html4/loose.dtd">
    <html>
    <head>
    [...]

Note the misplaced 2012.

I've contacted the webmaster, and this might be more of an issue with a parsing library that trafilatura uses, but I wonder if this pattern of mangled HTML might be popular and could be tolerated. Particularly in older documents (pre modern web).

As some context for prioritization, this is not an urgent or blocking concern for my use of trafilatura, and I am using a work around for this specific situation.

**Comment by adbar** [comment]
Hi, thank you for the bug report, the extraction was indeed failing due to a strict HTML type verification. I fixed it in e9e08e961d054847e6c1a0a2aeb0a83f12cfdcb4, what's returned may not be perfect but at least the extraction now runs on HTML documents with malformed declarations.

**Comment by adbar** [comment]
The new release is out.
