### ISSUE TITLE
Endless reading for link / timeout possible?

### ISSUE THREAD

**Issue by Rapid1898-code** [adbar/trafilatura#263]
Hello, i try to read the text of the following site using this code:

```
url = "http://www.sopral.com"
link = traf.fetch_url(url)
print(traf.extract(link))
```

But it seems the program gets stuck at the fetch with no response.
Why is that?
And is there anyway to define a timeout in such cases in any way?

**Comment by adbar** [comment]
Hi @Rapid1898-code, there is a timeout for downloads. Sometimes the download fails, the object in `link` would be `None` and would throw an error, which is maybe why execution stops.

**Comment by adbar** [comment]
Note: It was also related to a bug (error not caught) so I updated relevant code parts.

**Comment by Rapid1898-code** [comment]
great - thanks a lot
How can i use the new / changed version?

**Comment by adbar** [comment]
Here is a way to install the latest version from the repository:
`pip3 install --no-deps --force-reinstall git+https://github.com/adbar/trafilatura`

**Comment by Rapid1898-code** [comment]
Hello, it seems that i have still the problem with some urls like
`http://www.pick-a-pea.com`
Isn´t it possible to implement a timeout-parameter - so when the fetching of the url takes to long (eg. 5 seconds) it stops trying and returns None or something like that?

**Comment by adbar** [comment]
Yes, there is actually a timeout (30 seconds) but it's a case for the [settings file](https://trafilatura.readthedocs.io/en/latest/usage-python.html#settings-file).

**Comment by adbar** [comment]
Updating to the latest version, setting and using a new `DOWNLOAD_TIMEOUT` in a settings file [as described in the documentation](https://trafilatura.readthedocs.io/en/latest/usage-python.html#settings-file) should solve the issue. I now consider the case solved.
