### ISSUE TITLE
403 for URL for Amazon

### ISSUE THREAD

**Issue by mirfan899** [adbar/trafilatura#270]
Hi, I'm trying to get the Amazon URL and it throws an error
```python
trafilatura.fetch_url("https://www.amazon.com/gp/help/customer/display.html?nodeId=GH3NM2YWEFEL2CQ4")
```
error thrown

```shell
2022-11-16 22:10:37.284 not a 200 response: 403 for URL https://www.amazon.com/gp/help/customer/display.html?nodeId=GH3NM2YWEFEL2CQ4
```

It seems the library most probably will not work on Amazon pages. Any solution to this?

**Comment by adbar** [comment]
Hi @mirfan899, it can be that your IP or user agent is blocked, please check the [documentation page on downloads](https://trafilatura.readthedocs.io/en/latest/downloads.html#troubleshooting).
