### ISSUE TITLE
Bug with LXML parser

### ISSUE THREAD

**Issue by rgeronimi** [adbar/trafilatura#28]
On some documents Trafilatura 0.6.0 fails with this error:

`
...
File "/usr/local/Caskroom/miniconda/base/envs/myenv/lib/python3.7/site-packages/trafilatura/external.py", line 123, in sanitize_tree
    tree = prune_html(tree)
  File "/usr/local/Caskroom/miniconda/base/envs/myenv/lib/python3.7/site-packages/trafilatura/htmlprocessing.py", line 63, in prune_html
    element.drop_tree()
AttributeError: 'lxml.etree._Element' object has no attribute 'drop_tree'
`

A git blame on this line reveals this is new code that has been made 21 days ago in this revision:
https://github.com/adbar/trafilatura/commit/74444d223ec1c2c386f6f4bc6e92754c8dbb632d

Note: I am using the latest version of lxml (4.6.1)

**Comment by rgeronimi** [comment]
Further investigation reveals there might be 2 type of elements within the lxml library:
lxml.etree._Element (generated here by Trafilatura but that doesn't have the drop_tree method)
lxml.html.HtmlElement (that is not used here but has the drop_tree method called by Trafilatura)

**Comment by adbar** [comment]
Good catch, thank you!
As `drop_tree` results in a slight performance increase, I used a try-catch to make sure the error is taken into account: 7abe22230df77a656da4c36d4da53d9c9781d898
