### ISSUE TITLE
Add image urls to metadata

### ISSUE THREAD

**Issue by andremacola** [adbar/trafilatura#281]
Sometimes an image is not included in text body and we can extract by some SEO TAGS like some article parsers do (https://github.com/extractus/article-extractor/blob/main/src/utils/extractMetaData.js)

Here some metatags:

```
'image'
'og:image'
'og:image:url'
'og:image:secure_url'
'twitter:image'
'twitter:image:src'
```

**Comment by adbar** [comment]
Images are not my priority but I get your point, we can work on the PR.
