### ISSUE TITLE
Improve title extraction by removing sitename suffix

### ISSUE THREAD

**Issue by andremacola** [adbar/trafilatura#284]
Most os sites add a suffix like:

- My article title | My Site Name
- My article title - My Site Name

There is no need the sitename within the article title

Common separators are: - | – — • · ‹ › ⁄ « » < > : * ⋆ ~

Some sites use html entities for this, like: `&#8212;`

**Comment by adbar** [comment]
Hi @andremacola, thanks for the observation. I agree that it should be possible to process the titles as you suggest. However it is imaginable to see titles in the form `sitename + separator + article title`, there is currently no way to make sure where the actual title is.

We could start by using the separator list you mention to see if things improve a bit, what do you think?

**Comment by andremacola** [comment]
@adbar I think we can do some logic to Identify the title within the text like newspaper3k or article-parser(node) do.

Maybe we can create something like Mozilla does on Readability.js (which article-parser use): https://github.com/mozilla/readability/blob/fde359445cc96888fd8fa9717d336558ace83a5d/Readability.js#L459

**Comment by adbar** [comment]
We could adapt the approach, would you be willing to draft a PR?

**Comment by andremacola** [comment]
I don't think I've ever seen a site with this pattern `sitename + separator + article title`. At least not in Brazil. This would seriously affect the SEO.

I'm pretty busy for now, maybe in the near future we can create a more elaborate filter

Meanwhile I'm using this simple function and for my use it's ok.

```python
TITLE_SEPARATORS = ["-", "|", "–", "—", "•", "·", "‹", "›", "⁄", "«", "»", "<", ">", ":", "*", "⋆", "~"]

def title_filter(title: str):
    for separator in TITLE_SEPARATORS:
        if f" {separator} " in title:
            title = title.split(separator)[0]

    return title.strip()
```

**Comment by adbar** [comment]
I just added additional symbols, detection of the actual article title in the HTML title tag should now be better.

I'm leaving the thread open as we could make some progress on the sitename as well.

**Comment by adbar** [comment]
Extracting the sitename from the second part of the `<title>` element would be too brittle, I'll close this issue as its main point is now addressed.
