### ISSUE TITLE
Can't get include_images to include any images

### ISSUE THREAD

**Issue by boxabirds** [adbar/trafilatura#288]
Hi apologies I have probably done something wrong but hoped this would produce a list of images somewhere in the output but I'm not having any luck :(

`          img_result = bare_extraction(
              filecontent=html_text,
              output_format="text",
              include_images=True,
              include_formatting=True,
          )
`

Example output -- note also I have struggled to understand how to expand nodes like "commentsbody". When I set `output_format` to `json` I get an error when trying to do `json.dumps` on the result above. Any guidance most appreciated :)

`
{'title': "World's first ammonia-electric semi packs as much energy as the Tesla", 'author': 'Loz Blain', 'url': 'https://newatlas.com/automotive/amogy-first-ammonia-semi/', 'hostname': 'newatlas.com', 'description': 'Claiming a system-level energy density 5X higher than batteries, Amogy has rolled out "the world\'s first ammonia-powered, zero-emission semi truck." It holds about 900 kWh of energy, like the Tesla Semi, but you can refuel it in about eight minutes.', 'sitename': 'New Atlas', 'date': '2023-01-18', 'categories': ['https://newatlas.com/automotive/'], 'tags': ['Electric truck', 'Ammonia', 'Fuel Cell', 'Clean+Fuel', 'Climate Solutions: Road Transport'], 'fingerprint': None, 'id': None, 'license': None, 'body': <Element body at 0x108a15780>, 'comments': None, 'commentsbody': <Element body at 0x10a18ee40>, 'raw_text': 'World\'s first ammonia-electric semi packs as much energy as the Tesla  Claiming a system-level energy density 5X higher than batteries, Amogy has rolled out "the world\'s first ammonia-powered, zero-emission semi truck." It holds about 900 kWh of energy, like the Tesla Semi, but you can refuel it in about eight minutes.  Ammonia does a better job of storing hydrogen than hydrogen itself, in many ways, and it could help clean up some difficult industries that require high-density energy. Brooklyn company Amogy has now presented a world-first ammonia-powered semi truck. Ammonia has two chief advantages over hydrogen as an energy carrier. One is the fact that it\'s a liquid at ambient temperature and pressure levels, making it a ton easier to store, transport and handle; hydrogen either needs to be heavily compressed to around 700 bar, or else kept cryogenically cooled as a liquid, to just 20.28 K (−252.87 °C; −423.17 °F) – both of these are energy-intensive processes. The second is how much energy it carries: by volume, nearly three times as much as hydrogen gas, and by weight, more than 20 times as much as today\'s lithium batteries. It can be produced cleanly, and it can be used as a fuel in many different ways, many of which create zero harmful or climate-relevant emissions. And while it does have certain drawbacks, green ammonia is viewed as a promising clean fuel alternative for industries like shipping, aviation and other applications where batteries and hydrogen gas simply can\'t carry enough juice to get the job done. Amogy was founded in 2020 to accelerate the development of green ammonia as a power source for clean transport. The company says it had a 5-kW ammonia drone flying by July 2021, followed quickly by a 100-kW ammonia tractor in May 2022. Now it\'s scaled-up its ammonia powertrain to 300 kW, and presented it in what it claims is the "world\'s first ammonia-powered, zero-emission semi truck" – a 2018 Freightliner Cascadia Class 8 truck that\'s been retrofit with an ammonia fuel system slung under the cabin and stacked up behind it, appearing to add little in the way of bulk to the standard truck. It fills up in eight minutes, to carry around 900 kWh of "total stored net electric energy" – roughly the same amount of energy as the Tesla Semi stores in its lithium battery packs. Amogy says its "carbon-free energy system ... has 5X higher system-level energy densities compared to lithium batteries," so it\'s reasonable to expect this cab will be significantly lighter than the Tesla. The truck has been built, filled up and "tested for several hours on the campus of Stony Brook University," and it\'s scheduled for full-scale real-world performance evaluation on a test track later this month. So how would we expect it to compare to the Tesla Semi? Does ammonia look better than batteries for this kind of heavy transport? That\'s very hard to say; Amogy doesn\'t provide performance or range estimates at this stage. We do know there\'ll be inefficiencies to deal with here that don\'t apply to battery-electric vehicles. Amogy\'s powertrain features an ammonia cracker that converts the ammonia back into hydrogen. It then runs that hydrogen through a fuel cell to create electrical power, and uses that power to drive electric motors. So if Amogy\'s "total stored net electric energy" of 900 kWh simply means there\'s enough ammonia on board to theoretically store 900 kWh, it doesn\'t mean 900 kWh will reach the motors. There\'ll be losses in the onboard ammonia cracking reactors, further losses in purification stages that make sure the hydrogen\'s ready for use in the fuel cell, and further losses at the fuel cell stage. We don\'t know what technologies Amogy is using, or the efficiency factor at any of these stages. We can try to guess, though. The Ammonia Energy Association cites a best case ammonia cracking efficiency of 76%, but that\'s likely at industrial scale – we wouldn\'t expect a cracking reactor that fits on a truck or a tractor to operate that efficiently. Still, if we use that figure, some 684 kWh of energy will reach the fuel cell in the form of hydrogen. If we take a high-end estimate for PEM fuel cell efficiency at 65%, then 444.6 kWh of energy will make it through to the motors. That\'s a little under half of the original 900 kWh, so in this optimistic scenario, the Amogy truck will travel about half as far as the Tesla Semi. That doesn\'t sound great. But on the other hand, you could easily add range by sticking another couple of ammonia tanks somewhere – and that\'ll be a much less painful process than trying to extend the range of a lithium-battery-powered semi. Plus, this is a retrofit; designing a new truck around the ammonia concept would let you do all sorts of things. We\'ll be interested to learn how this machine performs. We\'ve been harping on for a while now about the widely predicted lithium resource squeeze that\'s expected to kick in over the next decade; there\'s nowhere near enough lithium production to satisfy the projected demand as the EV transition accelerates – let alone other battery-relevant metals. Ammonia represents an inefficient, but high-density energy storage medium. It carries less than half the energy diesel does, but more than lithium or hydrogen, and it can be produced and used cleanly. It\'s well-understood in terms of storage, transport and handling, and it\'s already available in bulk quantities if you don\'t mind working with dirty fuel to start with. And as an easily available liquid fuel, it could absolutely be relevant in the freight sector. Amogy is looking at marine next. It says it\'ll have a 1-MW-scale ammonia powered tugboat to show off later this year, and it hopes to scale this up over 10 MW by 2025, to produce a powertrain relevant to container ships on trans-oceanic voyages. There are other ammonia-powered shipping projects in the works; Australian mining company Fortescue, for example, says it\'ll have a 75-meter (246-ft) vessel running sometime this year. But this is expected to use an ammonia combustion powertrain rather than an electric system run through a fuel cell. Check out a highly uninformative video of the Amogy truck below.', 'text': None, 'language': None}
`

**Comment by adbar** [comment]
Hi @boxabirds, I cannot reproduce your result:

- I tried on the command-line and this includes images as Markdown links: `trafilatura -u "https://newatlas.com/automotive/amogy-first-ammonia-semi/" --json --images`
-  You should use `extract()` instead of `bare_extraction()` if you want to work directly on the output. The nodes are in `etree` (parsed XML) format, there not usable otherwise.

Does this answer your concerns?

**Comment by boxabirds** [comment]
Thanks very much. It looks like include_images is not supported if the output format is `text` could that be possible?

**Comment by adbar** [comment]
I cannot reproduce the case, there are images present as Markdown links in the following:

```
from trafilatura import fetch_url, extract
download = fetch_url("https://newatlas.com/automotive/amogy-first-ammonia-semi/")
extract(download, include_images=True)  # output_format="txt" is superfluous
```

Perhaps the misunderstanding comes from the fact that any inclusion of additional elements like formatting or images in TXT output will happen in Markdown format.

**Comment by boxabirds** [comment]
In my example I’m using raw_extraction… could that make a difference?

**Comment by adbar** [comment]
Yes, that's the point, you should replace the `bare_extraction()` function by `extract()`.

**Comment by charleshan** [comment]
Can you try this link?
https://blacksmithgu.github.io/obsidian-dataview/queries/query-types/#table

It's missing the calendar image at the bottom.

**Comment by adbar** [comment]
Thanks for the additional feedback, the issue is now related to #388.

@charleshan @boxabirds Let's continue the discussion there if you have further comments.
