### ISSUE TITLE
Option to remove unreachable pages and pages not strictly in the same domain

### ISSUE THREAD

**Issue by MTB-nsartor** [adbar/trafilatura#291]
Hi there, 

First, thanks for this amazing library! 

I have a couple of questions, which might turn into possible new features, if interesting to you.

I am creating a list of all viable URLs in a certain domain (using the 'focused_crawler') and subsequently will extract the text from the interesting ones.

Here are some of the results after I built the first part:

**LOGS**
`...
ERROR:trafilatura.downloads:not a 200 response: 404 for URL https://knoema.com/o/front-end-engineer-nashville
ERROR:trafilatura.downloads:not a 200 response: 404 for URL https://knoema.com/o/data-engineer-india`

**Result -->** 
`{
...
 'https://knoema.com/',
...
 'https://knoema.com/o/data-engineer-india',
 'https://knoema.es',
...
 'https://knoema.recruitee.com'}`

1. How can I exclude from the results all those pages which responded 404 ?

    e.g. **https://knoema.com/o/data-engineer-india** made it to the final list, but for me is pretty useless, as I won't be able to get its data, unless I re-send a request (which is quite inefficient).
    
    I think it would be just a matter of adding an optional return in the `downloads._handle_response` function.

2. IMHO  **https://knoema.recruitee.com** should not be part of the results from a focused crawler.

    I can easily discard this kind of result (and the .es) in a second moment, but I believe it's a conceptual error.

Thanks a lot!
Nicholas

**Comment by adbar** [comment]
Hi @MTB-nsartor, thanks for your feedback!

1. The command-line interface keeps track of failed downloads. I didn't include it in the Python library so far but as you say it's doable.
2. You're right, `https://knoema.recruitee.com/` is not the same website as `knoema.com`, this should be fixed.

**Comment by MTB-nsartor** [comment]
let me know if I can help with a PR or something.

**Comment by adbar** [comment]
The second part (the actual bug) is now fixed, I'll release a new version of the underlying library ([courlan](https://github.com/adbar/courlan)) soon.

Yes, feel free to draft a PR for the `downloads._handle_response` return value. I don't have any precise idea in mind right now as of how it could look like. Since it's a function used internally only it should be possible to add the feature as an "export mode" addition without breaking the rest.
