### ISSUE TITLE
Error on compare_extraction function when no fallback is False

### ISSUE THREAD

**Issue by felipehertzer** [adbar/trafilatura#297]
Hi @adbar,

I was checking some articles and this article is throwing an error:
https://pge.sx/3ROqS5K

If I put `no_fallback=False` it will throw.

```
trafilatura/core.py", line 643, in compare_extraction
    algo_text = trim(temppost_algo.text_content())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by adbar** [comment]
Hi @felipehertzer, I cannot reproduce it, do you have other settings to share?

**Comment by felipehertzer** [comment]
I have the default settings, also I tested via CLI.

I'm using MacOS 13.2, but it also happen on Manjaro OS.

Python 3.11

```python

resp = requests.get(url=url, timeout=13)
result = extract(
    filecontent=resp.text,
    url=url,
)

```

**Comment by adbar** [comment]
I just cannot reproduce it so I can't explain it. If you run into the error again please post another URL.
