### ISSUE TITLE
extract_metadata() doesn't return dict, but documentation says it does

### ISSUE THREAD

**Issue by edkrueger** [adbar/trafilatura#298]
Thanks for this awesome library.  

I'm using `trafilatura==1.4.1`.  

It looks like the the documentation is out of sync with the behavior of `extract_metadata()`.  

The documentation says that `extract_metadata()` returns `dict` or `None`: https://trafilatura.readthedocs.io/en/latest/corefunctions.html#extract-metadata  

But, it looks like it actually returns `trafilatura.metadata.Document`.  

I see two paths forward.  

Option 1: Update the Documentation:
- [ ] change the documentation to say that `extract_metadata()` returns `trafilatura.metadata.Document`
- [ ] (optional) add a method to `trafilatura.metadata.Document` to easily convert to a `dict`
  
Option 2: Update the Code:
- [ ] change `extract_metadata()` to return a `dict`

I'm happy to implement either option in a PR.  

Let me know what you think.

**Comment by adbar** [comment]
Hi @edkrueger, thanks, as you write the documentation is outdated.

I'd go for option 1, we could potentially explain somewhere in the docs how to turn the returned object into a dict but I doubt anybody needs this information. What do you think?

**Comment by edkrueger** [comment]
Hey @adbar, I agree that option 1 is the better one.

However, I think it would be good to add either a `__dict__` or `to_dict` method to the `trafilatura.metadata.Document` class and mention it in the documentation.

For my use case, I'm not analyzing anything particular. I'm just loading the metadata to a database for later analysis. It would be nice to have a simple way to convert _all_ the metadata into an easily serializable form. This was what I was thinking about when I wrote the optional task above.

**Comment by adbar** [comment]
A `as_dict()` method would indeed be nice, thanks for the suggestion and feel free to draft a PR!
