### ISSUE TITLE
Empty list value for @type causes extract_metadata to fail

### ISSUE THREAD

**Issue by edkrueger** [adbar/trafilatura#299]
Problem:

`extract_metadata` fails on a html that has json metadata with the following key-value pair.

```json
{
...
"@type": [],
...
}
```

Traceback:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[4], line 3
      1 with open("article-10617.html", "r") as file:
      2     html = file.read()
----> 3     trafilatura.extract_metadata(html)

File ~/.pyenv/versions/3.10.2/lib/python3.10/site-packages/trafilatura/metadata.py:439, in extract_metadata(filecontent, default_url, date_config, fastmode, author_blacklist)
    437 # fix: try json-ld metadata and override
    438 try:
--> 439     metadata = extract_meta_json(tree, metadata)
    440 # todo: fix bugs in json_metadata.py
    441 except TypeError as err:

File ~/.pyenv/versions/3.10.2/lib/python3.10/site-packages/trafilatura/metadata.py:111, in extract_meta_json(tree, metadata)
    109 try:
    110     schema = json.loads(element_text)
--> 111     metadata = extract_json(schema, metadata)
    112 except json.JSONDecodeError:
    113     metadata = extract_json_parse_error(element_text, metadata)

File ~/.pyenv/versions/3.10.2/lib/python3.10/site-packages/trafilatura/json_metadata.py:47, in extract_json(schema, metadata)
     44     continue
     45 if isinstance(content["@type"], list):
     46     # some websites are using ['Person'] as type
---> 47     content_type = content["@type"][0].lower()
     48 else:
     49     content_type = content["@type"].lower()

IndexError: list index out of range
```

Examples:

file 1: https://gist.github.com/edkrueger/a665bdc8b9e549955bb5a5b8100f3396  
problem with line 176 of file 1  

file 2: https://gist.github.com/edkrueger/9e8968054c86a5896c25fe01d9783c08  
problem with line 176 of file 2  

Cause:  
Caused by line 47 of json_metadata.py `content_type = content["@type"][0].lower()`  
Received an empty list, but checks the 0 index.  

Possible Solutions:
I think this should, at the least, not result in an exception halting the execution. It would also be nice if the extraction of the other metadata.   

I think the best fix would be check if the list is empty and do one of the following:
* set `content_type` to `None`
* set `content_type` to `""`

Let me know what you think. I'm happy to make a PR.

**Comment by adbar** [comment]
Let's aim for `content_type` to `None` then, as you say this problem shouldn't halt the extraction. Please draft a PR and add a corresponding test case.

@felipehertzer You wrote the JSON extraction code, any comments?

**Comment by felipehertzer** [comment]
Hey @adbar and @edkrueger, 

In this case where the content type is an empty list, there is no reason to continue checking, as all the code is based on that value. What we can do is check if the list is empty and then execute the 'continue'

I.e.
```python
if len(content["@type"]) == 0:
    continue
```

or 

```python
if isinstance(content["@type"], list) and len(content["@type"]) > 0:
    # some websites are using ['Person'] as type
    content_type = content["@type"][0].lower()
elif isinstance(content["@type"], str):
    content_type = content["@type"].lower()
else:
    continue
```
