### ISSUE TITLE
trafilatura as a server

### ISSUE THREAD

**Issue by lord-alfred** [adbar/trafilatura#300]
Thank you so much for this package, it is very good!

I added it as a server in my little collection of NLP utilities with docker container (the most convenient way not to care about dependencies).

Check it out here https://github.com/lord-alfred/dnlp

I think it will be useful for many people! If you don't mind - I could translate the readme into English and I would really like to get a link my repo from your repository (if it's possible) 😇.

Thanks a lot! I think it's worth mentioning here https://github.com/adbar/trafilatura/issues/151 (for breadcrumbs)

**Comment by adbar** [comment]
I have trouble assessing the relevance of your repository as I don't speak the language of the readme.

I am looking for a simpler option than a docker container to let the package run as a server but I'll have a look at it.

**Comment by lord-alfred** [comment]
> I have trouble assessing the relevance of your repository as I don't speak the language of the readme.

I think this simple google translation will help you understand what's inside:
https://github-com.translate.goog/lord-alfred/dnlp?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=ru&_x_tr_pto=wapp

**Comment by adbar** [comment]
Thanks, I'll keep that in mind.
