### ISSUE TITLE
Cannot extract table from wordpress gutenberg blocks

### ISSUE THREAD

**Issue by fortyfourforty** [adbar/trafilatura#301]
Thanks for this awesome library. 
It's now my go-to tool for content extraction.

Problem:
The WordPress Gutenberg editor wraps the table with a figure tag like this :`<figure class="wp-block-table"><table><tbody></tbody></table></figure>.`

Trafilatura cannot extract the table inside the figure wrapper. If I remove the figure wrapper it can extract the table block just fine.

I would suggest Trafilatura can add the feature to specifically look for WordPress's specific Gutenberg block patterns when extracting content from WP-based sites. Gutenberg is widely used by content creators now and Gutenberg keeps adding custom wrappers to ul, table tags from version to version.

**Comment by adbar** [comment]
Thanks for your feedback, that's correct, the table element is discarded because it's within a figure (usually not a relevant tag). We could improve that.

**Comment by fortyfourforty** [comment]
Is there any hotfix for this, so I can implement and extract tables from wp sites? Thanks! I'm incapable of fixing it on my own.
@adbar

**Comment by adbar** [comment]
Well there is always a way, for example you could get rid of the tag before passing the HTML to Trafilatura.

I need to test the feature beforehand so I don't break anything, so far there are very good reasons why `figure` elements are discarded.

**Comment by fortyfourforty** [comment]
> Well there is always a way, for example you could get rid of the tag before passing the HTML to Trafilatura.

That's clever, I'll give it a try.
