### ISSUE TITLE
Method of Sourcing Elements

### ISSUE THREAD

**Issue by jackHedaya** [adbar/trafilatura#302]
Hi!

Would it be possible to source where the text is coming from? I'd like to be able to know which css selector a given text snippet comes from.

**Comment by adbar** [comment]
Hi @jackHedaya, if you increase verbosity you'll see which part of the document is being targeted by the fast algorithm (logging level debug in Python or `-vv` on the command-line).
The backup extraction methods work differently so in case there are chosen you won't be able to get this information.

**Comment by adbar** [comment]
Does that answer your question?

**Comment by jackHedaya** [comment]
Yes thank you!
