### ISSUE TITLE
Unable to extract full text from New Yorker article

### ISSUE THREAD

**Issue by CyberneticTurtle** [adbar/trafilatura#304]
Thank you for all your work on trafilatura. I've just encountered an interesting bug. trafilatura (and other readability-based text extractors in general) are unable to fully extract the text from the following article: https://www.newyorker.com/tech/annals-of-technology/chatgpt-is-a-blurry-jpeg-of-the-web

Trafilatura and Firefox reader mode (which is based on readability) both only extract text till the line: "Is it possible that, in areas outside addition and subtraction, statistical regularities in text actually do correspond to genuine knowledge of the real world?"

It seems like the article HTML is broken up into two sections and trafilatura/readability stop extracting the article after the first section. See this image of the HTML:
![image](https://user-images.githubusercontent.com/111058418/219958761-f0202097-ee6c-488e-9327-966aac231670.png)

I haven't debugged more than that. I will look into it again when I have more free time.

**Comment by adbar** [comment]
Hi @CyberneticTurtle, this bug is related to #85. I currently have no fix for it but feel free to dig deeper and suggest improvements.
