### ISSUE TITLE
`cchardet` is recommended now or is replaced by `charset-normalizer` by default? 

### ISSUE THREAD

**Issue by lord-alfred** [adbar/trafilatura#305]
In [docs](https://trafilatura.readthedocs.io/en/latest/installation.html#optional-modules): 
> A few additional libraries can be installed for extended functionality and faster processing: language detection and faster encoding detection: the cchardet package may not work on all systems but it is highly recommended.

But now `charset-normalizer` is setup by default, `charset-normalizer` is faster: https://github.com/aio-libs/aiohttp/pull/5930#issuecomment-938592238

**Comment by adbar** [comment]
Hi @lord-alfred, I need to revise the docs from time to time but in your case it's still up-to-date.

The `cchardet` library is just not the same as the `chardet` library, it is more accurate and faster. So I still recommend it, it's not maintained anymore so I had to use a fork.

Does this answer your concern?

**Comment by lord-alfred** [comment]
Sorry, but no :(

I still don't get it: why is it recommended to use [`cchardet` ](https://github.com/adbar/trafilatura/blob/14d9782891c2b4d6ff3eb0e00de2e9a11f01b43a/setup.py#L31), although judging from the benchmarks I cited above `charset-normalizer` is faster?
