### ISSUE TITLE
Extract page type with og:type or jd+json

### ISSUE THREAD

**Issue by andremacola** [adbar/trafilatura#307]
I think it would be interesting to extract the type of page, although some sites do not use Open Graph tags.

Maybe some other algorithm as an alternative to og:type to stipulate whether it's a category/front page or articles page?

**Comment by adbar** [comment]
Hi @andremacola, thanks for the suggestion, I believe it's safe for now to use `og:type`, anything else would be trickier.

If you have other ideas concerning metadata extracted from Open Graph tags feel free to write further pull requests.

**Comment by andremacola** [comment]
I did a PR

**Comment by adbar** [comment]
I understand, I meant other PRs if necessary.

**Comment by adbar** [comment]
`article:section` and `og:locale` are also interesting if you want to look into it. I started working on it but haven't gone any further for now.

I'm closing the issue since `og:type` has been addressed. Thanks for that!
