### ISSUE TITLE
What is the recommended approach to outputting a more readable article

### ISSUE THREAD

**Issue by rbhalla** [adbar/trafilatura#308]
I am asking this here since I've seen a few comparisons with other Readability implementations. Apologies if this library is actually going in a different direction.

I am trying to extract articles and retain as much information as possible (which led me here), however, I'm noticing that with the inbuilt `extract` function I am losing a lot more than I would expect.

Apologies for the crudeness, but as an example I'm going to use a relatively simple site with a unfortunate content: https://motherfuckingwebsite.com/

Using `extract(res.content, 'https://motherfuckingwebsite.com/', output_format="xml", include_formatting=True)`, not only am I missing direct content from the site like the second line "And it's fucking perfect.", but I also lose all context of headers.

If I compare this to https://github.com/mozilla/readability, it seems to retain a lot more.

Also importantly for me, it retains the header tags that are helpful for me when splitting the content up for further parsing.

Two questions here:
1) Am I missing some obvious configuration that makes this simple example work? I know `favor_recall` exists, but I feel like that is more for finetuning than this case.
2) Is there a way to produce an output more representative of the input (i.e. HTML) rather than a completely different format?

**Comment by andremacola** [comment]
In my tests the article is coming complete. Try to use `trfl.bare_extraction()` with `favor_precision=True, favor_recall=True`

![Captura de Tela 2023-02-24 às 04 07 16](https://user-images.githubusercontent.com/3408809/221114680-9b2796a9-4ec0-4e95-87dc-3cd098b27667.jpg)

**Comment by adbar** [comment]
Hi @rbhalla, thanks for your feedback. Your remarks definitely make sense, however few webpages are as minimal as your example. In this case Trafilatura scrambles to recover text elements but usually it works fine because there are more structural markers to start from. (See also #63.)

XML isn't that different from HTML, you could rename the tags manually or this could be done internally, it's an open question.
