### ISSUE TITLE
Cannot extract heading correctly in a list

### ISSUE THREAD

**Issue by fortyfourforty** [adbar/trafilatura#309]
The problem:
If the heading tag is wrapped in a list item, then Trafilatura cannot extract the heading correctly in XML format. It can extract as a heading as `<head>` but cannot identify the h2 or h3 like `<head rend="h2">`. Such sites like `thespruce.com` and similar sites often wrap h2/h3 tags in an ol ordered list to show h2 tags as a list format.

**Comment by fortyfourforty** [comment]
Hi @adbar, this page for example: `https://www.thespruce.com/types-of-electrical-switches-in-the-home-1824672` . You can see all light switch types are wrapped in an ordered list. If you try to extract it into xml, you cannot get the exact h2, only as a h tag.

**Comment by adbar** [comment]
Thanks, I get it but there is a certain level of nesting involved... Not sure it's the priority right now but let's keep track of the bug.

**Comment by fortyfourforty** [comment]
Actually, many, many giant sites are doing this for SEO purposes - Lists h2 in a list to perform better on google search result pages for a rich snippet/ jump links. This could be on your priority list IMO.

**Comment by adbar** [comment]
Yes, thankfully it was easy to fix.
