### ISSUE TITLE
Library is redirecting stderr to /dev/null upon every call

### ISSUE THREAD

**Issue by rgeronimi** [adbar/trafilatura#31]
If readbility fallback is activated, the Trafilatura library redirects stderr to /dev/null upon every call:
https://github.com/adbar/trafilatura/blob/a56fb3e041175df38a32b1c5ef2e9c7888eeb7a6/trafilatura/external.py#L63

Within programs involving other libraries, this causes a host of side effects. E.g., generating a chart with seaborn imports ipython (a dependency of seaborn) which pre-checks upon initialization stdin, stdout and stderr and crashes because stderr is /dev/null. I have other side effects as well in other libraries, including disappearing logs (eg when logs settings are modified after calls to Trafilatura).

This redirection seems to have been necessary to prevent the readibility library to print out messages to stderr. A cursory reading of the current version of readibility seems to indicate it doesn't do that, it only emits proper logs.

Consequently, this redirect may be removed (to be tested).

**Comment by rgeronimi** [comment]
It appears a "MUFFLE_FLAG" allows to control externally thiis behavior. So I used that. However, considering readibility seems clean now (however I didn't test that), it may be better to remove all that code

**Comment by rgeronimi** [comment]
I tested with the MUFFLE_FLAG active for more than 100,000 documents and readability printed out nothing on stderr. Therefore it might be possible to remove all this code. I can contribute a PR if that's relevant

**Comment by adbar** [comment]
I think you're right, the problem I intended to solve with these lines isn't existing anymore, I removed this behavior in effbccf4fff35e7c77c3d396a809ff0c62436a9b

Since we're working on the handling of external modules: do you know how to modify the internal subclass `LXMLDocument` so as to avoid converting back the output back from a string back to an LXML tree? It could save processing time but I'm not sure how to do it:
https://github.com/adbar/trafilatura/blob/3b4cb19d615c2df17cdbb72a9309d724abcef91a/trafilatura/external.py#L56

**Comment by rgeronimi** [comment]
That's a good point! Reading their code, it seems the readibility.Document.get_clean_html is exactly the one to override. The comment there explicitly indicates your use case

**Comment by adbar** [comment]
Yes, it seems the right way to go, but I'm not sure how to do it.

**Comment by rgeronimi** [comment]
Reading the code, I guess this override in your LXMLDocument class should do the trick (not tested):
`
def get_clean_html(self):
        return self.html
`

**Comment by adbar** [comment]
It doesn't work, calling `doc.summary(html_partial=True)` on such a modified `LXMLDocument` class somehow returns empty or unusable trees.

**Comment by rgeronimi** [comment]
Hmmm I dont know this part at all. I would study the current get_clean_html code (it calls 2 functions) to understand what they do to get something usable out of that

**Comment by adbar** [comment]
Thanks, I made a separate issue (#37) for this and will now close this one.

**Comment by rgeronimi** [comment]
Thanks!
