### ISSUE TITLE
Doesnt extract li tags content with an id

### ISSUE THREAD

**Issue by alroythalus** [adbar/trafilatura#318]
![Screenshot (534)](https://user-images.githubusercontent.com/119865678/230439233-d0de5fd9-ba9e-487d-a676-3bc986cf2a24.png)
It doesn't extract this text for some reason.
.
.
.
.
.
It works for this though
![Screenshot (533)](https://user-images.githubusercontent.com/119865678/230439361-424fc213-0c30-427b-85d1-f80aaa6066c4.png)

**Comment by adbar** [comment]
Hi @alroythalus, a screenshot is not enough to diagnose the problem here. Could you please provide an URL for the first case or copy the critical part of the HTML code?

**Comment by alroythalus** [comment]
yes sure @adbar. This is the site in the 1st case **https://www.kia.com/us/en/privacy** and this in the case image https://docs.github.com/en/site-policy/privacy-policies/github-privacy-statement.

It misses out on a lot of core information, the screenshot I sent above is just one example. You can just run it against this site **https://www.kia.com/us/en/privacy** and have a look. Most of the bullet points are omitted.

**Comment by alroythalus** [comment]
I am using this config of trafilature.

`extract(
                original_html,
                include_formatting=True,
                include_tables=True,
                include_comments=False,
                include_links=False,
                output_format="XML"
            )`
