### ISSUE TITLE
feat: add basic auth support

### ISSUE THREAD

**Issue by kondounagi** [adbar/trafilatura#323]

**Comment by kondounagi** [comment]
Hi @adbar , thank you for your excellent tool!
`trafilatura.fetch_url` and other helper functions in this library help gather texts from the web; however, we cannot apply them to websites with basic authentication, which require a username and password.
For example, when I gather docs from a basic-authed website, I must use the `requests` library to pass basic auth like below.
```
class BasicAuth:
    def __init__(self, username: str, password: str):
        self.session = requests.Session()
        self.session.auth = username, password

    def __call__(self, _url):
        return self.session.get(_url)
```

I hope we can specify our id and password of basic auth in `fetch_url` and other helper functions!

**Comment by adbar** [comment]
I understand, thanks for the details. The issue seems related to #322 and could be addressed by providing a more configurable function to fetch HTML documents. Let's keep the issue open for now.

**Comment by adbar** [comment]
@kondounagi Can you try the new `Response` object described in issue #322 and see if it works for you?
