### ISSUE TITLE
ValueError: signal only works in main thread

### ISSUE THREAD

**Issue by pandemosth** [adbar/trafilatura#325]
v1.5.0

Getting the above exception when running within Ray (ray.io) distributed.

Looks like this is a regression of https://github.com/adbar/trafilatura/issues/202, and the config based workaround isnt working, probably a result of moving url handling to courlan lib:

https://github.com/adbar/courlan/blob/b13571f28577c5a188e0eab2f937b97ba530489c/courlan/urlstore.py#L73

**Comment by adbar** [comment]
Hi @pandemosth, I think you've diagnosed the issue correctly. I'll open a corresponding issue in the underlying library, in the meantime you can use another version, e.g. `trafilatura==1.4.1`.
