### ISSUE TITLE
Headers with classes dont get detected

### ISSUE THREAD

**Issue by alroythalus** [adbar/trafilatura#333]
In the case of google the headers are p tags 
https://policies.google.com/privacy?hl=en-US

`<p class="q0cs9b">We want you to understand the types of information we collect as you use our services</p><p>We collect information to provide better services to all our users — from figuring out basic stuff like which language you speak, to more complex things like which <a class="YfaGG" href="[privacy?hl=en-US#footnote-useful-ads](https://github.com/adbar/trafilatura/issues/privacy?hl=en-US#footnote-useful-ads)" data-name="useful-ads" jsaction="click:IPbaae(preventDefault=true)">ads you’ll find most useful</a>`

![Screenshot (543)](https://user-images.githubusercontent.com/119865678/233930879-5aca4b3a-605f-4f11-88fa-83c9c5e1e6b3.png)

Is there any way for trafilatura to reflect such a header disguised as a p tag?

**Comment by adbar** [comment]
I don't think so, Trafilatura performs a simplification and in some cases a conversion based on the tag names present in the HTML document. It doesn't try to infer document structure.
