### ISSUE TITLE
Paras get broken up into fragments

### ISSUE THREAD

**Issue by alroythalus** [adbar/trafilatura#334]
In the case of https://www.kia.com/us/en/privacy 

- Headers do not get detected maybe cus of the class attached to every header
![Screenshot (548)](https://user-images.githubusercontent.com/119865678/233943533-6bc09da5-6b79-49b5-ba40-fc7ca0fa1f1a.png)

- The table present isn't represented as trafilatura as a table but as p tags

**Comment by adbar** [comment]
Hi @alroythalus, I see two different issues here:
1. The first case is not a header but a bold paragraph, you mean to say it isn't in the extracted content?
2. You mean the table which follows? In fact it's not used as a table with columns so the fact that it's treated isn't a problem, or is it?

**Comment by alroythalus** [comment]
- wrt to header: it gets extracted but as a para itself, even tho in the page it is intended to be a header.

- wrt table, it doesn't get treated ideally, and the html of the page does define it as a table.
That's why i was wondering why the table gets converted to p tags.

**Comment by adbar** [comment]
I'm afraid it's related to the issue #333 you also filed, the package makes no assumptions as to the nature of the text segments.
