### ISSUE TITLE
Doesn't detect bullet points within tables

### ISSUE THREAD

**Issue by alroythalus** [adbar/trafilatura#335]
Site: https://stackoverflow.com/legal/privacy-policy#:~:text=We%20will%20only%20process%20your,be%20shared%20with%20other%20parties.

 
![Screenshot (549)](https://user-images.githubusercontent.com/119865678/234219126-5b9ebfdd-a2d7-456d-aa51-e262d2e2713f.png)
For one of the tables, it has a list within a cell, this content gets missed out. 

This is what trafilatura generated
`<row>
        <cell>
          <p>Marketing our services and those of selected third parties to:</p>
        </cell>
        <cell>For our legitimate interests or those of a third party, i.e., to promote our business to existing and former customers</cell>
</row>`

Hope this helps, thanks

**Comment by adbar** [comment]
I agree, it's uncommon to find bullet points in tables but it would indeed be a useful addition.

**Comment by alroythalus** [comment]
Do you feel this could be related to #318?

**Comment by adbar** [comment]
If the parent element is a table it's a duplicate issue, otherwise it's a problem with the extraction of nested elements.

**Comment by adbar** [comment]
I see that the first case now appears to be solved. The second one can be addressed by focusing on recall:
`favor_recall=True` with Python, `--recall` on the command-line.
