### ISSUE TITLE
Simple HTML processing issue?

### ISSUE THREAD

**Issue by alroythalus** [adbar/trafilatura#337]
For this simple piece of HTML :

```
<!DOCTYPE html>
<html lang="en">
<body>
        <h1>4. How Long We Keep df Information</h1>
</body>
</html>
```

This is the Trafilatura output
```
<doc title="4. How Long We Keep df Information" categories="" tags="" fingerprint="g92davQ/jL7gis2YFBcyHhRLd2s=">
  <main>
    <p>4. How Long We Keep df Information</p>
  </main>
</doc>
```

It converts the h-tag to a p-tag for some reason. Is this intended to be like this? Just curious.

**Comment by adbar** [comment]
It can be explained by various issues with document conversion, notably as regards conformity with the XML TEI standard.

**Comment by alroythalus** [comment]
Is this a problem that needs to be solved? Or is it expected not to work for bare-bone simple html

**Comment by adbar** [comment]
No it's not an issue, I'll close the thread.

**Comment by alroythalus** [comment]
Sure. Really appreciate the effort and time you put into this Library. I personally love it too.
