### ISSUE TITLE
Codeblock Markdown formatting is missing

### ISSUE THREAD

**Issue by niksite** [adbar/trafilatura#351]
Hi,

I noticed that `extract(html, include_formatting=True)` does not include the codeblock formatting (three backticks before and after the code). Although it is included in the XML output, it is missing in the Markdown output for some reason. 
Test page: `trafilatura -u https://habr.com/ru/articles/734980/ --formatting`.

It would be great if you could look into this and consider adding support for codeblock Markdown formatting. I think the codeblocks are an essential part of an article when formatting is enabled.

**Comment by adbar** [comment]
Hi @niksite, that's correct, I'm going to look into it.

**Comment by andersfylling** [comment]
@niksite did you figure out a way to deal with this?

**Comment by adbar** [comment]
The general output of code blocks should now be better, however certain elements are not fully converted to markdown. A few lines could be added to this function if anyone wants to draft a pull request:

https://github.com/adbar/trafilatura/blob/71c16614b8fbb72b117c4e1d085d7aad0d04508a/trafilatura/xml.py#L205
