### ISSUE TITLE
Cannot extract Heading tags

### ISSUE THREAD

**Issue by fortyfourforty** [adbar/trafilatura#354]
Hi,

It's weird that Trafilatura sometimes failed to extract simple structured heading tags like h2 or h3.

Example urls like:
`https://www.nextpcb.com/blog/bill-of-material` , `https://www.protoexpress.com/blog/controlled-impedance-really-matters/` 

I even tried unwrapping the ID, a, span, b tags using BS4 before sending the source to Trafilatura, but it still fail to extract the h2 or h3s.

The format I am using is: `trafilatura.extract(str(soup), output_format='xml', include_comments=False)`

**Comment by adbar** [comment]
Hi @fortyfourforty, thanks for reporting the issue, it is only true for the first example though.

It happens because the custom extraction cannot find the main text container and thus resorts to looking for paragraphs only.

**Comment by fortyfourforty** [comment]
Hi @adbar, thanks for the feedback

Sorry wrong example attached. The second example was supposed to be `https://resources.altium.com/p/what-is-a-bom-in-pcb-design`.  Is it the same cause as being unable to find the main text container?

Is there any quick fix for this that I can implement? Without headings, the whole article loses most of the contextual structure and its meaning.  If there is any quick fix please hit me up!

**Comment by adbar** [comment]
Hi @fortyfourforty, thanks for the new example, indeed it's a similar kind of problem though not exactly the same: the titles entail links, that's usually a bad sign and they get discarded.

It turns out I already had such cases in mind:
https://github.com/adbar/trafilatura/blob/7d90f302ae14759adc18e883d1c8303528084776/trafilatura/core.py#L664

It degrades extraction accurary on my benchmark so I didn't include this rule so far. I could activate it to use with `favor_recall` or (hypothetically) solve the problem altogether. I'll give it a thought.

**Comment by fortyfourforty** [comment]
Hi @adbar, Thanks for the reply.

It's weird, I actually thought the same thing that you'd remove headings with links into consideration, so I use bs4 to remove the links and other span tags inside or outside headings before sending the page source to trafilatura. The heading is still not extracted. 
You can have a test on the new example to see if the headings are successfully extracted if the links are removed first.

**Comment by adbar** [comment]
I'll try to address the issue in #356.

Concerning the headings entailing links I'm not sure, we would need to write tests.

Since we're at it is there something else you wish to share concerning your manual pre-cleaning?

**Comment by fortyfourforty** [comment]
I go stupid simple. I go parse with BS4 first and find_all headings, mostly h2 and h3s as I only care about them. Other h4 or h5 might be irrelevant sidebar links which should be already filtered out by your algo.

I iter the h2 and h3s, if their contents contain <a>, <span> or etc, I unwrap the inner tag. Then I send the modified source to Trafilatura for extraction.
You can add an extra, similar pre-cleaning layer in Trafilatura so you don't have to worry about messing with other logic concerning about existing filtering, and cleaning algo.

I do the same for the WordPress `table` block issue I mentioned bout earlier. If the parent element of a table is `figure`, I convert the `figure` tag into `div` before passing the source to Trafilatura so that it can be extracted. And the simple modification does no harm to the source code.

**Comment by adbar** [comment]
The table issue (#301) is now fixed. I managed to find a fix for the second case you mentioned, the first one is tricky as I cannot adjust the extraction parameters without degrading overall performance.

**Comment by fortyfourforty** [comment]
BTW, can you shed some light on how to solve the heading issues( Trafilatura unable to find content container) with some data pre-cleaning? I know you care about the overall benchmarks but I just need to get it to work.

If there are any quick hacks to get Trafilatura to extract headings like it should, please hit me up! For example, maybe I can pre-extract the main content container and feed it to Trafilatura?

**Comment by adbar** [comment]
Usually taking all titles into account degrades performance (mostly because you end up with the menus, the sidebar etc.).

I managed to fix one of the cases in the PR by changing XPath rules but when Trafilatura resorts to barebone extraction it only takes paragraphs. If you're really sure of what you're doing, changing `<h1>/<h2>/...` into `<p>` should do the trick.

**Comment by fortyfourforty** [comment]
So, I convert `h1 h2` into `p` with some kind of additional "marker" in innerhtml like `(heading1)` and convert it back to heading after extraction?

The workflow:
1.) Use Trafilatura to get an xml extraction, get the first and final p tag.
2) In the original page source, convert all headings in between the first and final p tags to `<p>` tags, but with extra "markers" like (h1), (h2) added at the beginning of the innerText. So I don't mess with the menus, sidebars.
3) Send the modified source to Trafilatura, extract and convert the p tags with the pattern like `<p>(h1) abc</p>` to `<h1>abc</h1>`

Is this approach valid?

**Comment by fortyfourforty** [comment]
I just tested. It's an ugly hack but it works for now.
I modify all `headings` within the first `P`'s parent `div` so I won't mess with menus or sidebar headings.

**Comment by fortyfourforty** [comment]
I suggest some ugly algo for fixing this:

1) Normal Trafilatura xml extraction.
2) Check if headings exist.
   If NO heading exist in xml file:      # we check if Trafilatura miss catch the headings
     check if there are heading included in the nearest parent element in the page source which includes all the P tags formerly 
      extracted by Trafilatura. If there are headings, do some modifications..

This approach won't affect your performance in any way, just a more few checks.

**Comment by fortyfourforty** [comment]
Update:
It's wrong to only check the first P as Trafilatura will extract unrelated P tags such as login IDs, which is not the main content and have no parent. 
Need more algo to detect the p tag inside the main content container.

**Comment by fortyfourforty** [comment]
Update:
1) Iter each P tag and find its parent, use Trafilatura to extract the parent div
2) Compare with the initial Trafilatura extraction of the original page source
3) Do a similarity comparison, If the similarity > 0.9, I consider it the main content container and work from that.

**Comment by fortyfourforty** [comment]
Thanks for the fix, i'll take a look.

Actually, this is what I tried:
1. Iter each P tag and find its parent, use Trafilatura to extract the parent div  --- Update: only find and compare similarity for parent or ancestors 3 levels max, this works for most data I tested with.
2. Compare with the initial Trafilatura extraction of the original page source  --- Update:  It works sometimes. But the new problem is that, sometimes Trafilatura cannot extract anything from the parent/ancestor div I feed into it, so sometimes the extraction is None, which is wierd and cannot be used to compare similarity. It seems Trafilatura failed to process the text wrapped in simple <div> tags, even with the fallback function.(Find all P tags like a fallback, like mentioned above). So sometimes this method is very unstable due to the fact that Trafilatura cannot extract single text.

For example. Given a html like this. And we try to find the main text container.

```
<div class= 'outer'>
   <noise html like sidebar, etc>
  <div class= 'inner1'>
    <p> this is P1 </p>
  </div>
  <div class= 'inner2'>
    <p> this is P2 </p>
  </div>
  <noise html>
</div>
```
Step1: We feed html into Trafilatura and we should get a XML output like <item> this is P1 </item><item> this is P2 </item>
Step2: By theory. I get the <p1>'s parent <div inner1>, then I feed into Trafilatura, I should get a output like  <item> this is P1 </item>, so I can compare the similirty betwen  `this is P1` and this is `P1 and  this is P2`.  The problem is sometimes the extraion is simply None. I also tried the `try-redability` and `html2txt `, all nothing returned. If Trafilatura has a parameter to force the fallback method to force ectract all P tags, or to extract the texts like BS4 get_text(), I can use it to compare.

3. Do a similarity comparison, If the similarity > 0.9, I consider it the main content container and work from that.  --- Update: For now I just use the python difflib.SequenceMatcher to compare the similarity. For some data I tested, if the Trafilatura can extract all parent divs correctly, this appoach simply works.


Given the fact that the above method sometimes failed, the current workaround I use is:
1. In the orginal page source, I convert all heading tags, UL, OL List tags to P tags, with additional markers in the inner text like <p>(h1)abc</p> and convert back to correct tags in the end like <h1>abc</h1>.
2. Feed the modified source to Trafilatura and get a cleaned xml output.
3. Now I get more noise information retained in the new xml file like table of contents, and such.
4. I compare the new xml and the old xml.
for example:

The old XML extraion:
```
<p>text1</p>
<p>heading1</p>
<p>text3</p>
```

The new XML:

```
<h3>unrelated, noise data<h3>
<p>text1</p>
<h2>heading1</h2>
<p>text3</p>
<h4>unrelated, noise data<h4>
```

I compare each element in the new XML and extract/remove them until it matches the first element <p>text1</p> in the old xml. I compare only the text/string without tags because the tags may change. Then I keep all the elements until I find the element matches the last element <p>text3</p> in the old xml and I extract/remove all the rest. So I keep all the information with the correct tags.

This is just a workaound, still have noises but it is useable for now.

**Comment by adbar** [comment]
Interesting, thanks! A classifier would also make sense at this point, your pre-processing is complex, multiple similarity comparisons in particular are probably costly from a computational perspective, but if the method is worth it...

The `html2txt()` function should work, it is in essence similar to BS4's `get_text()`. Do you have a simple example for which it misses text inside of div elements?

If you deal with a lot of similar sources it could be that their markup isn't addressed by the XPath expressions to find the main text. Although they are already pretty generic I recently added the attribute `role="article"` to it for example. Maybe we could add more expressions to extend coverage.

**Comment by elrob** [comment]
Thank you for working on this. I'd also like to test with enabling "favor_recall" and see if more of the subheadings end up in the extracted txt. Is there likely to be a release any time soon that would include this change?

**Comment by elrob** [comment]
I found that even after this change, I was unable to get the subheadings included in the extracted text.

```
    if options.recall is True and len_text > min_target_length * 10:
        return body, text, len_text
```

This part was already true so it doesn't even reach the recently added section:
```
    # https://github.com/adbar/trafilatura/issues/354
    elif options.recall is True and not body.xpath('.//head') and temppost_algo.xpath('.//h2|.//h3|.//h4') and len_algo > len_text:
        algo_flag = True
```

I understand that it's not often clear whether headings should or should not be included in extracted text content.
In the test data used to evaluate the precision and recall, do they include headings and subheadings? And are those headings and subheadings expected to be present in the extracted text?

**Comment by elrob** [comment]
Thanks. In trying to provide a good example, it seems my problem may depend on whether I provide a HTML snippet or the full article origin HTML.

In the example below, there is a `<h2 class="presto-h2 ">Perpetrators broke into a room through ventilation shaft to get the chemicals, authorities say</h2>`. The text within that `h2` is not included when I run the extractor with the below HTML snippet. However, it is included when I use the full HTML which is attached.

Is this expected? Should I be using the full HTML rather than HTML snippets? I thought HTML snippets would be better as they ones I have are already relatively clean but I am attempting to use trafilatura to remove image captions and things like that.

Article HTML snippet:
```
<p>Two children suffered “burn-like injuries” after acid was poured on three slides at a Massachusetts playground, authorities said. </p><p>Fire and police departments in Longmeadow, just south of Springfield, are searching for suspects after authorities responded to a call Sunday at 9:40 a.m. local time for a suspicious substance found on the <a href="https://www.facebook.com/LongmeadowFire/posts/pfbid032sikFUPXR5KrpKV6rMtq7TfubJz5PaKkP2UgdT2NZn3LstNp4mgPzmMzz9wN1nDSl">slides at Bliss Park Playground</a>, the Longmeadow Fire Department said in a news release Monday. </p><p>At the same time, Longmeadow EMS crews responded to a report of two children suffering burn-like injuries after leaving the park. Firefighters determined the material on the slides was &#34;acidic in nature.&#34;</p><p>The hazmat team determined that the chemical poured on the slides was muriatic acid, the fire department said.  </p><p>“The (Massachusetts) State Police crime lab gathered several items of evidence,” the fire department said in the news release. “Additional evidence was gathered and has been sent to the crime lab for forensic analysis and fingerprinting.” </p><p>Multiple agencies including the Massachusetts Department of Environmental Protection assisted in the investigation. </p><p><span class="exclude-from-newsgate"><strong style="margin-right:3px;">Texas fish kill: </strong><a href="https://www.usatoday.com/story/news/nation/2023/06/12/texas-gulf-coast-dead-fish/70312349007/" target="_blank">Thousands of dead fish washed ashore beaches along the Texas Gulf Coast. Here’s why.</a></span></p><h2 class="presto-h2 ">Perpetrators broke into a room through ventilation shaft to get the chemicals, authorities say</h2><p>The fire department said the perpetrators climbed two fences and used a ventilation shaft to break into a room in the basement of a pool building, where the chemicals were stored to operate the pool. </p><p>&#34;The pool chemicals had been stored properly in a secured area,&#34; the fire department said.</p><p>Fire department officials said they suspect the perpetrators may have suffered acid burns to their hands or arms and their clothing may have “indications of being degraded from contact with the acid.” </p><p>Longmeadow officials hired a contractor to clean the playground and the status of the playground will be determined after it’s cleaned, the fire department said.</p><p>The playground area is fenced off, but the rest of the park is open, the fire department said.</p><p>The fire department requested anyone with information contact Longmeadow police.</p>
```

(I had to give this file a .txt suffix to be able to upload it as .html was rejected)
[article_html.txt](https://github.com/adbar/trafilatura/files/11735072/article_html.txt)

**Comment by adbar** [comment]
@elrob I just tested the USA Today URL you provided and I see the `<h2>` title in the output.

It makes much more sense to use the whole HTML, Trafilatura uses a series of markup cues to find and extract the main content and this won't work well if you strip parts of the document beforehand.

**Comment by elrob** [comment]
> I just tested the USA Today URL you provided and I see the `<h2>` title in the output.

Thank you for the quick response and advice. Yeah, I realize that it works with the origin HTML. However, the `<h2>` title is not included when using the fragment.

My current plan is to attempt to continue using the fragments as they are generally very clean, I just want to strip things like image captions. I've just tested preprocessing the fragments to convert the headings to `<p>` tags as for these fragments I can assume that the headings are not noise and should be part of the extracted text.

**Comment by fortyfourforty** [comment]
> It makes much more sense to use the whole HTML, Trafilatura uses a series of markup cues to find and extract the main content and this won't work well if you strip parts of the document beforehand.

@adbar  Given this, I'd also like to know if there is any function for Trafilatura to force extract HTML blocks the same as whole HTML source, without taking ` a series of markup cues` into consideration. Like mentioned before, Trafilatura cannot extract content from HTML blocks due to its algo(looking for HTML markup cues first, if it cannot find, it does nothing to the HTML block).   If you have a feature/function for this, then I can proceed my work.

**Comment by elrob** [comment]
Thank you!
