### ISSUE TITLE
metadata extraction problem

### ISSUE THREAD

**Issue by fortyfourforty** [adbar/trafilatura#374]
Hi,

Error url : `https://www.hpe.com/us/en/what-is/security-monitoring.html`

Error code: 

[/usr/local/lib/python3.10/dist-packages/trafilatura/json_metadata.py](https://localhost:8080/#) in extract_json(schema, metadata)
     63                     if metadata.sitename is None or (len(metadata.sitename) < len(candidate) and content_type != "webpage"):
     64                         metadata.sitename = candidate
---> 65                     if metadata.sitename is not None and metadata.sitename.startswith('http') and not candidate.startswith('http'):
     66                         metadata.sitename = candidate
     67 

AttributeError: 'list' object has no attribute 'startswith'

PS:
A similar problem where you might need to have a look when fixing:

[/usr/local/lib/python3.10/dist-packages/trafilatura/json_metadata.py](https://localhost:8080/#) in extract_json(schema, metadata)
     63                     if metadata.sitename is None or (len(metadata.sitename) < len(candidate) and content_type != "webpage"):
     64                         metadata.sitename = candidate
---> 65                     if metadata.sitename is not None and metadata.sitename.startswith('http') and not candidate.startswith('http'):
     66                         metadata.sitename = candidate
     67 

AttributeError: 'list' object has no attribute 'startswith'

Error function: `trafilatura.extract(source, output_format='xml', include_comments=False)`

**Comment by felipehertzer** [comment]
Hey @fortyfourforty, I can't replicate this issue with the given URL, also they aren't using json-ld. Can you provide more details as Trafilatura version?

**Comment by fortyfourforty** [comment]
Hi @felipehertzer, I just tested with a clean install the issue is gone. Guess it has to do with my own code. Thanks for your time testing!

**Comment by adbar** [comment]
Thanks @fortyfourforty & @felipehertzer for your feedback.

**Comment by fortyfourforty** [comment]
Another example for the same problem.

I've tested with clean install and can reproduce the same error. If you have time you can have a look at this thanks. @felipehertzer @adbar 

Error url : `https://www.safetyinsurance.com/`

Error: [/usr/local/lib/python3.10/dist-packages/trafilatura/json_metadata.py](https://localhost:8080/#) in extract_json(schema, metadata)
     63                     if metadata.sitename is None or (len(metadata.sitename) < len(candidate) and content_type != "webpage"):
     64                         metadata.sitename = candidate
---> 65                     if metadata.sitename is not None and metadata.sitename.startswith('http') and not candidate.startswith('http'):
     66                         metadata.sitename = candidate
     67 

AttributeError: 'list' object has no attribute 'startswith'

Function: 
downloaded = fetch_url(url)
res = trafilatura.extract(downloaded, output_format="json", include_comments=False)

**Comment by adbar** [comment]
The webpage is currently offline, I tried with an archived version (`https://web.archive.org/web/20230607164633/https://www.safetyinsurance.com/`) and I cannot reproduce the problem. Are you using the last Trafilatura version?

**Comment by fortyfourforty** [comment]
Yes, last Trafilatura version. 
Pip install in colab with a new notebook dedicated for testing.

I tested again with a notebook, you can have a look. 
The site is not offline as I just tested and you can also see the source in the notebook.

`https://colab.research.google.com/drive/1Bm5rJpt40_veEAGREOwIw-EcMelXHiCr?usp=sharing`

**Comment by felipehertzer** [comment]
Hey @adbar,

The problem is that this website is using [alternateName](https://schema.org/alternateName) as list instead of text. I added a extra to avoid that bug.

https://schema.org/Organization
