### ISSUE TITLE
Doesn't seem to work with recent charset-normalizer

### ISSUE THREAD

**Issue by Stevod** [adbar/trafilatura#379]
I get an error when I use trafilatura with version 3.1.0 of this package  charset-normalizer, but reverting to v2.0.4 seems to work fine

**Comment by adbar** [comment]
Hi @Stevod I cannot reproduce the error, could you please be more specific? Which error are you seeing, during which operation?

**Comment by Stevod** [comment]
Thanks adbar. The same problem is occurring with other packages, so looks like my setup. Closing.
