### ISSUE TITLE
Code example for Multi-Threaded downloads seems out of date

### ISSUE THREAD

**Issue by github-mickael-leclerc** [adbar/trafilatura#385]
Hi,

When trying to run code example from https://github.com/adbar/trafilatura/blob/master/docs/downloads.rst#trafilatura-backed-parallel-threads I get the following error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[30], line 13
     11 # processing loop
     12 while dl_dict:
---> 13     buffer, threads, dl_dict, backoff_dict = load_download_buffer(dl_dict, backoff_dict)
     14     for url, result in buffered_downloads(buffer, threads):
     15         # do something here
     16         print(result)

ValueError: not enough values to unpack (expected 4, got 2)
```

As checked in the source code, the output values mismatch the example code.

Thanks !

**Comment by adbar** [comment]
Hi @github-mickael-leclerc, that's correct, it's a documentation issue.

The function currently takes at most 2 arguments (`dl_dict` and `sleep_time`) and returns 2 (`urls`  and `dl_dict`) so the following should be fine: `urls, _ = load_download_buffer(url_store, sleep_time=5)`

I'll add it to the docs.

**Comment by github-mickael-leclerc** [comment]
Thanks @adbar, I tried something similar of `urls, _ = load_download_buffer(url_store, sleep_time=5)` but thought that the example didn't match with this new method implementation, so I did rollback to version 1.4.1 to have something working. I'll wait for the documentation / example update then to see what I was missing. Thanks :)

**Comment by Jiankun-Huang** [comment]
mhm is this dead?

**Comment by adbar** [comment]
@JBX2060 The change in the docs is delayed on my side but feel free to draft a PR.
