### ISSUE TITLE
Is it possible to get the metadata with markdown format?

### ISSUE THREAD

**Issue by charleshan** [adbar/trafilatura#391]
There are useful information when we output to json format, such as: title, author, and date. However, it looks like json only has `raw_text` as the content format.

The workaround is extracting in both `json` and `txt` with `include_formatting` but I think we can do better

**Comment by adbar** [comment]
Good point, the code here could definitely be improved to add further metadata:

https://github.com/adbar/trafilatura/blob/123414cae5f927e743f5eced2cd43b81a65fc43c/trafilatura/xml.py#L41

**Comment by LaundroMat** [comment]
Having the metadata as JSON and the content as Markdown would be the ideal situation for me. 
Am I right that with the current version, I'll have to extract twice? Once as JSON to get the structured metadata, and once as markdown to get the content in markdown format?

**Comment by adbar** [comment]
In the current state you can use the available Python functions (notably `bare_extraction()` and the conversion functions) to get your own mix.
