### ISSUE TITLE
Try to fetch dead links from archive.org

### ISSUE THREAD

**Issue by adbar** [adbar/trafilatura#40]
URL structure could be `https://web.archive.org/web/20/original-URL`

**Comment by t-duan** [comment]
Thank you very much for investigating this issue and for the collection of Python libraries related to web archive (#39).

**Comment by adbar** [comment]
I didn't really test it thoroughly but an `archive.org`-backup is implemented in 703619378aea2e6a8b86883b148a94f878018bd8. You can trigger it by using the last version from the repository and adding `--archived` as command-line option.

I'm closing this issue for now, please re-open it if something doesn't work as expected.
