### ISSUE TITLE
Use of Signal Prevents Multithreading on Linux

### ISSUE THREAD

**Issue by simplexx** [adbar/trafilatura#403]
Noticed that on my EC2 instance (ubuntu 22), trafilatura can not be used in a different thread, other than the main thread, due to use of Signal (so multithreading doesn't work at all) in python. It works fine on my windows 10 dev machine.
It crashes with the following error:

 File "/home/ubuntu/.local/lib/python3.10/site-packages/trafilatura/core.py", line 1054, in extract
    signal(SIGALRM, timeout_handler)
  File "/usr/lib/python3.10/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter

As a quick and dirty fix, I just changed the following code:

# SIGALRM isn't present on Windows, detect it
try:
    #from signal import signal, alarm, SIGALRM
    HAS_SIGNAL = False
except ImportError:
    HAS_SIGNAL = False

And now it works.

Great project btw, much better and cleaner text extraction than beautiful soup!

**Comment by adbar** [comment]
Hi @simplexx, thanks for the report, I decided to remove signal from standard Python use in 63239a45d5733e80a1f5638f7dc5a65c1dfd9677, a new version will come soon, so I'll close this issue.
