### ISSUE TITLE
Web API idea

### ISSUE THREAD

**Issue by clach04** [adbar/trafilatura#405]
I've been briefly experimenting with[ Postlight (nee Mercury) Parser](https://github.com/postlight/parser), most of my projects are Python based so I was looking at a couple of the server implementations. Any interest in implementing the API described in:

  * https://github.com/postlight/parser-api
  * https://github.com/postlight/parser-api-express
  * https://github.com/HenryQW/mercury-parser-api/

Example (copied from HenryQW/):

`GET /parser?url=[required:url]&contentType=[optional:contentType]&headers=[optional:url-encoded-headers]`

    curl localhost:3000/parser?url=https://www.bbc.co.uk/news/science-environment-35876621

I'm thinking about knocking something up, wondering if anyone else would find it useful (e.g. for switching backends).

**Comment by clach04** [comment]
I've not got as figuring out good defaults for different features when missing/present compared with Postlight's return payload.

**Comment by adbar** [comment]
Hi @clach04, I believe people would find it useful indeed.

You may want to look at this repository which implements a basic API:
https://github.com/Soontao/trafilatura-srv (see `app.py`)

**Comment by adbar** [comment]
@clach04 There is now an official implementation, see the [API page in the docs](https://trafilatura.readthedocs.io/en/latest/usage-api.html).

**Comment by clach04** [comment]
Awesome I'll have an experiment!
