### ISSUE TITLE
Installation problem on Mac due to charset version mismatch

### ISSUE THREAD

**Issue by TheRabidWolverine** [adbar/trafilatura#409]
Trying to install on Mac with pip, getting this error message:

> Installing collected packages: tzlocal, tld, regex, lxml, langcodes, charset-normalizer, dateparser, courlan, htmldate, trafilatura
>   Attempting uninstall: lxml
>     Found existing installation: lxml 4.9.0
>     Uninstalling lxml-4.9.0:
>       Successfully uninstalled lxml-4.9.0
>   Attempting uninstall: charset-normalizer
>     Found existing installation: charset-normalizer 2.0.12
>     Uninstalling charset-normalizer-2.0.12:
>       Successfully uninstalled charset-normalizer-2.0.12
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> requests 2.28.0 requires charset-normalizer~=2.0.0, but you have charset-normalizer 3.2.0 which is incompatible.
> Successfully installed charset-normalizer-3.2.0 courlan-0.9.3 dateparser-1.1.8 htmldate-1.4.3 langcodes-3.3.0 lxml-4.9.3 regex-2023.8.8 tld-0.13 trafilatura-1.6.1 tzlocal-5.0.1
> 

Any idea how to fix this?

**Comment by adbar** [comment]
Hi @TheRabidWolverine, this is not related to the package. You seem to have a version of `requests` which isn't compatible with the rest. Try removing it or using a virtual environment (e.g. with `pyenv`) to perform a clean installation.
