### ISSUE TITLE
Multiple spaces within a text element are not supported

### ISSUE THREAD

**Issue by idoshamun** [adbar/trafilatura#422]
Following #401, I noticed Trafilatura doesn't support multiple spaces within a text element. Specifically code element is what I care about. This causes syntax issues in some languages like python which are indent based.

I debugged the issue and realized the root cause is here: https://github.com/adbar/trafilatura/blob/master/trafilatura/utils.py#L268.
Essentially when we call trim it ignores all the multiple spaces because it split the line by spaces. I'm not sure why we need to trim multiple spaces in the first place, if it's for compression reasons than we can probably remove multiple spaces between elements and not within.

Potentially we can change this line to:
`remove_control_characters(LINES_TRIMMING.sub(r' ', line)).strip()`
But I'm not sure if it introduces new edge cases.

@adbar what would be the right way to address this issue?

**Comment by adbar** [comment]
Hi @idoshamun, according to the benchmarks it's generally a good idea to trim spaces as users want clean output and the input HTML can be messy or convoluted. Of course it doesn't count for elements where literal spacing should be preserved, such as `<pre>` or `<code>`.

A potential course of action would be to skip trimming for certain elements, which would involve modifying all instances of trimming by keeping track of the tag name and possibly the names of the descendants.

**Comment by idoshamun** [comment]
I feel it's quite a significant change, and I believe we can do this change only in the line I mentioned because this is where the literal spacing is removed. I'd appreciate any pointers to help me contribute.

**Comment by idoshamun** [comment]
I'll do my best to look into that. Thanks for the info, I'll keep you posted

**Comment by adbar** [comment]
An different way to tackle the issue would consist in adding a `preserve_space` option to the `extract()` function. That way space could be preserved or removed altogether. So not a differenciated approach but probably simpler to implement.
