### ISSUE TITLE
Inconsistent behavior on macOS

### ISSUE THREAD

**Issue by p-linnane** [adbar/trafilatura#423]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging trafilatura for distribution, we are encountering some inconsistent behavior between macOS versions. We run a simple functionality test to make sure the binary works correctly.

In this case we check that `trafilatura --version` returns the correct version, and that `trafilatura -u https://brew.sh` returns "The Missing Package Manager for macOS (or Linux)" which is the top line on our web page. This works correctly on Ubuntu 22.04, macOS Sonoma (14), and macOS Ventura (13). However, macOS Monterey (12) simply returns `! D O C T Y P E h t m l >`, causing this test to fail.

I'm opening this issue to hopefully gain some insight into reasons this could be different between OS versions. Thank you!

Relates to https://github.com/Homebrew/homebrew-core/pull/146181

**Comment by adbar** [comment]
Hi @p-linnane, thank you for your feedback. Sadly I think the bug is not related to the library itself but to the `lxml` dependency. Is there already a corresponding package for homebrew and/or have you witnessed such inconsistencies with lxml in the past?

**Comment by p-linnane** [comment]
I have not seen any similar issues in the past. We have roughly 60 packages currently using `lxml` with no issues.

**Comment by p-linnane** [comment]
I worked around this by testing google.com instead of our site brew.sh.
