### ISSUE TITLE
crawl only sub-pages from an arbitrary URL?

### ISSUE THREAD

**Issue by pchalasani** [adbar/trafilatura#427]
I thought `focused_crawler` would allow this, but if I use a URL which is _not_ the home URL (i.e. is a long "full" URL like `https://www.va.gov/resources/evidence-to-support-va-pension-dic-or-accrued-benefits-claims/`
then it tries to go to the home url `https://www.va.gov` and starts getting links from there. 

How can I restrict it to only (recursively) get sub-pages of the actual URL?

**Comment by adbar** [comment]
Hi @pchalasani, indeed this extended functionality is not implemented (yet), the focused crawler restricts itself to a website but not to a given portion of a website.

You could use the underlying library [courlan](https://github.com/adbar/courlan) to filter the URLs you've collected accord to a pattern like `"/evidence-to-support-va-pension-dic-or-accrued-benefits-claims/"`.

Does that answer your question?

**Comment by pchalasani** [comment]
Yes I was considering a solution along these lines, e.g. discard from `known_links` those that I don't want. 
I wouldn't actually match with the full URL, since I am interested in links _reachable_ from this page AND contain the base URL, and it could well be that some of these don't contain the initial URL as a prefix. So maybe just discard from `known-links` those that don't contain the domain URL.

**Comment by adbar** [comment]
Please note that even if there are relative links they should come out as absolute, which allow for filtering based on the complete URL structure.
