### ISSUE TITLE
trafilatura fails extracting 

### ISSUE THREAD

**Issue by tejeshbhalla** [adbar/trafilatura#433]
I have tried using it on most websites it , gives a wierd error on some 

`output
ERROR:trafilatura.utils:parsed tree length: 1, wrong data type or not valid HTML
ERROR:trafilatura.core:empty HTML tree for URL None`

it even fails on trafilaturas own documentation , `https://trafilatura.readthedocs.io/en/latest/usage-python.html`

**Comment by adbar** [comment]
If you're on MacOS, especially M1/M2 platforms, this is a common problem.

Brew can now be used to install Trafilaturain a seamless way:
https://formulae.brew.sh/formula/trafilatura

**Comment by tejeshbhalla** [comment]
no i was using google colab os , why is this happening though ? what the best way to install in docker image and what os ?

**Comment by adbar** [comment]
I'm not aware of any problem on Google Colab, please try other [installation methods](https://trafilatura.readthedocs.io/en/latest/installation.html) and tell me if something works, it shouldn't be an issue.

**Comment by tejeshbhalla** [comment]
i was using pip install trafilatura[all] but this seems to fail so should i grab the latest one with u ?

**Comment by tejeshbhalla** [comment]
> I'm not aware of any problem on Google Colab, please try other [installation methods](https://trafilatura.readthedocs.io/en/latest/installation.html) and tell me if something works, it shouldn't be an issue.

it fails on specific links like the above but the rate is high though from my test its like 30% for me

**Comment by adbar** [comment]
Then it could simply mean that the downloads failed because the IP is blocked and/or the page blocks the user agent.

**Comment by adbar** [comment]
@tejeshbhalla Any feedback on this?
