### ISSUE TITLE
ld-json extraction cruft

### ISSUE THREAD

**Issue by Yomguithereal** [adbar/trafilatura#45]
Hello @adbar,

This is not an issue per-se but it seems that when you extract metadata from `ld-json`, such as the author, for instance, you don't take into account the fact that it is sometimes stringified with python's infamous `ensure_ascii` keyword to default `True`. If we take this html page for instance: [https://www.bvoltaire.fr/jean-sevillia-letat-francais-et-letat-algerien-doivent-reconnaitre-les-crimes-commis-des-deux-cotes/](https://www.bvoltaire.fr/jean-sevillia-letat-francais-et-letat-algerien-doivent-reconnaitre-les-crimes-commis-des-deux-cotes/) the name "Jean Sévillia" is stringified as "Jean S\u00e9villia". This can be a drag sometimes.

I am not saying this should be addressed by `trafilatura` directly and I personally use [this](https://github.com/medialab/minet/blob/trafilatura/minet/utils.py#L70-L74) hacky function to get the job done (a replacer might be dangerous because of some erroneous html text containing badly stringified emojis missing parts of a surrogate combination I keep stumbling upon these days...), but I just wanted to open a discussion.

**Comment by adbar** [comment]
I just tested it (192130252d1a3626daf427ff902ac9690981340b) and it doesn't come from the HTML source code but from a serialization later in the code, I'm not sure what I can do to correct it. The strings in `bare_extraction` should be fine.

**Comment by Yomguithereal** [comment]
Isn't your commit fixing this in a sense?

> The strings in bare_extraction should be fine.

I am using `bare_extraction` and I get those ascii encoded strings.

**Comment by adbar** [comment]
It should now be fixed in 7ed5d449953b8b911b65ac5943b047491ba893ff. Can you please confirm and close the issue?

**Comment by Yomguithereal** [comment]
Sorry @adbar. Haven’t found time to check yet. But I trust you.
