### ISSUE TITLE
Extraction with unexpected result

### ISSUE THREAD

**Issue by Lucabenj** [adbar/trafilatura#46]
Case: In an HTML page, the main text has been placed in paragraphs contained in a DIV. Then after a few more tags outside the `DIV`, some `h2` headings appear:

`...`
`<div>`
`<p>Lorem ipusm dolor</p>`
`<p>sit amet</p>`
`</div>`

`<h2>Hello World</>`
`<h2>and a few other texts</>`
`...`

Unexpected behaviour: In the response JSON, the fields "text" and "raw-text" are composed of the content of the `h2` tag, **followed** by the content of the preceding paragraphs `p` in the HTML stream:
`"raw-text" : "Hello World and a few other texts Lorem ipusm dolor sit amet"`

**Comment by Yomguithereal** [comment]
Hello @Lucabenj, can you give the url displaying such an example? Also could it be an issue of wrongly formatted HTML that is "fixed" by the browser whereas `lxml` wouldn't do so, or not in the same manner? For instance in your example here:

```html
<h2>Hello World</>
<h2>and a few other texts</>
```

there are some badly formatted tags (but I am sure it is just an error when writing HTML by hand, I do it all the time also :) ).

**Comment by adbar** [comment]
Hi, I can't reproduce the bug with the following fragment:

```
<html>
<body>
<div>
<p>Lorem ipusm dolor</p>
<p>sit amet</p>
</div>
<h2>Hello World</>
<h2>and a few other texts</>
</body>
</html>
```
The result of `trafilatura --json` is as expected, considering the malformed tags:
`"raw-text": "Lorem ipusm dolor sit amet Hello World> and a few other texts>"`

Which version are you using and is there something else that gets in the way?

**Comment by adbar** [comment]
Hi @Lucabenj, could you please provide the requested information?
