### ISSUE TITLE
TXT output doesn't produce markdown-compliant paragraphs

### ISSUE THREAD

**Issue by claudehenchoz** [adbar/trafilatura#467]
Currently, paragraphs in txt format are returned as follows:

> Text of paragraph 1
> Text of paragraph 2

However, in order to be compliant with [markdown formatting rules for paragraphs](https://daringfireball.net/projects/markdown/syntax#p) (and thus allowing for correct rendering), there should be an empty line between paragraphs:

> Text of paragraph 1
>     
> Text of paragraph 2

Can this be fixed?

**Comment by adbar** [comment]
Thanks for your feedback, there is still an ambiguity as the output is not officially Markdown but TXT with Markdown elements depending on the configuration.

So yes, it can be fixed and would be an occasion to address this setting.
