### ISSUE TITLE
fetch_url('spiegel.de/....') returns None

### ISSUE THREAD

**Issue by robertour** [adbar/trafilatura#474]
I am consistently getting None values when I try to fetch spiegel articles

```
from trafilatura import fetch_url
fetch_url('https://spiegel.de')
```

The corresponding version in requests is working:

```
import requests
response = requests.get('https://spiegel.de')
print(response.content)
```

And `fetch_url` is working if I try other URLs:

```
fetch_url('https://google.com')
```

Since I running a scraping process, I can report that my problem started exactly on `2023-10-03` on trafilatura==1.6.1

I have tested also trafilatura==1.6.3, and trafilatura==1.6.4. 

I am using a different IP for my tests.

**Comment by adbar** [comment]
Hi @robertour, thanks for your feedback, I can reproduce the error (403 response for the homepage).

The download utility aims at staying simple and lean, sometimes it doesn't come through. This can be circumvented, notably by emulating a browser or changing the configuration (see [troubleshooting doc page](https://trafilatura.readthedocs.io/en/latest/troubleshooting.html)), but it doesn't always work.

I see that Der Spiegel's [robots.txt](https://www.spiegel.de/robots.txt) file states that "The use of robots or other automated means to access spiegel.de or collect or mine data without the express permission of spiegel.de is strictly prohibited."
My guess is that they took measures to restrict access.

I can suggest to use `fetch_url()` in most cases and some other tool or URL (e.g. a web archive) when it doesn't work, then use the extract function on the HTML.

**Comment by robertour** [comment]
Thanks @adbar, it is all good then.  Feel free to close the issue. 

I was wondering if something was off. I am a bit puzzled of how did you extract the 403, is there a global variable that one can check for this?

**Comment by adbar** [comment]
The info is present in the logs but overall the `fetch_url()` function could be restructured (see #322).

For testing and prototyping I usually use the command-line interface with `-v` or `-vv` to increase verbosity:

```
$ trafilatura -u "https://www.spiegel.de" -v
ERROR:trafilatura.downloads:not a 200 response: 403 for URL https://www.spiegel.de/
WARNING:trafilatura.cli_utils:No result for URL: https://www.spiegel.de/
```

**Comment by adbar** [comment]
Note: I had of course forgotten that you can use `fetch_url(url, decode=False)` to get a response object with the status code.

**Comment by robertour** [comment]
Thanks, yes, I saw the parameter in the other thread. I initially thought it referred to text encoding (utf-8, etc). If I remember correctly the encoding comes in the header.
