### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [adbar/trafilatura#475]
Hi,
Great library! Would you consider switching the license to a more permissive one (ie LGPL/MIT/ISC) so this library can be included in upstream projects?
Thanks!

**Comment by adbar** [comment]
Hi @fakerybakery, I'm not completely against it but this library is already included in a wide range of other packages, I'm not sure what you mean.

**Comment by fakerybakery** [comment]
Hi, sorry, I want to make a non-GPL-licensed project. I’m working with embeddings, and it would be super useful to be able to easily extract the main content of a webpage.

**Comment by adbar** [comment]
Have you read the [license section of the Readme](https://github.com/adbar/trafilatura?tab=readme-ov-file#license)? In particular, you could consider interacting at [arms length](https://www.gnu.org/licenses/gpl-faq.html#GPLInProprietarySystem) with the software package.

**Comment by fakerybakery** [comment]
Thanks for the suggestion! I've read that section, but the main thing is that this usually is slower than using the package directly

**Comment by adbar** [comment]
Your project is open-source isn't it? All [these licenses](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses) are compatible ("you can combine code released under the other license with code released under the GNU GPL in one larger program"), that's a lot to choose from.

**Comment by fakerybakery** [comment]
I am planning to opens source my project soon. Thanks for your suggestions!

**Comment by adbar** [comment]
Point addressed in #512.
