### ISSUE TITLE
Make markdown an explicit output format

### ISSUE THREAD

**Issue by adbar** [adbar/trafilatura#489]
So far markdown is only activated when formatting is preserved. However it makes sense to improve markdown output and make it an explicit output format. TXT output would be left as it is now.

Related to #467.

**Comment by mike-clark-8192** [comment]
I agree. Markdown has become so important these days.  Making it its own explicit format would allow grouping Markdown-specific configuration options together a bit easier in documentation and type hints, and allow for growth in that area.  It's a bit confusing that some output formatting options apply to plain text, some apply to Markdown, and some apply to both. Which makes sense conceptually, but it would be nice if it was sectioned out more explicitly.
