### ISSUE TITLE
Trafilatura to support more robust async library than standard request

### ISSUE THREAD

**Issue by krstp** [adbar/trafilatura#514]
This is request for Trafilatura to support a more robust async library, such as `asyncio/aiohttp` instead of underlying `urllib`, which has some issues.

Assisting conversation: https://github.com/adbar/trafilatura/discussions/515

**Comment by adbar** [comment]
Hi @krstp, I get your point but it is an open question whether Trafilatura should support more complex download utilities. I am inclined to say that the basics should be covered but that people who know their way around it could simply download the files first and then use the extraction functions on the content.

**Comment by krstp** [comment]
Fair point. Thanks for your input.

**Comment by Ousret** [comment]
You could probably leverage [urllib3.future](https://github.com/jawah/urllib3.future) as optional deps to bring an async entrypoint.

**Comment by adbar** [comment]
@Ousret I'll check it out.

@krstp  I have to say though that the download utilities are already quite robust and that they spread the load in order to avoid saturating or getting blocked. Of course there are more efficient librairies and there may be a bottleneck here and there in the code but for massive downloads on a single machine the problem is always going to be the latency/bandwith. Since support for multiple servers is not the focus of Trafilatura we can only do so much.

Please note that using pycurl also helps with the problem.

**Comment by brycepg** [comment]
So to be clear, the workaround for async is to call the trafilatura entry-point with an [async subprocess](https://docs.python.org/3/library/asyncio-subprocess.html)

**Comment by adbar** [comment]
@brycepg I'm open to review a pull request on this if you're interested.

**Comment by brycepg** [comment]
Seems to work well with async, just there were no examples :):

```python
import asyncio

import aiohttp
from trafilatura import fetch_url, extract

async def main():
    url = 'https://github.blog/2019-03-29-leader-spotlight-erin-spiceland/'
    async with aiohttp.ClientSession() as session:
        async with session.get(url) as response:
            downloaded = await response.text()
    result = extract(downloaded)
    print(result)

if __name__ == "__main__":
    asyncio.run(main())

```

**Comment by krstp** [comment]
Well... thanks for the sample of the code, but I do not think it solves then "problem" despite elegant portion of the code.

Indeed, the implementation of aiosync is possible, however, due to used/implemented urllib3 under-the-hood of trafilatura, it will not allow the use of actual full async.

Down to the root, it is like using requests library that relies on urllib3 as well. So just by specifying async, it does not immediately mean/delivers full async capability. Simple benchmark of those two libraries very quickly shows with aiosync one gets superior one-and-only async capability. For more details see urllib3 documentation that actually states it does not allow for full async.

I know, in very recent time, there were some key updates to urllib3 that solved some bugs , but historically it does not allow for full async capability even if by principle you can mark it as such.

From my past investigation, one-and-only way to get full async functionality in python is to use aiosync library, and with that - due to nature how async works - it requires async wrapper across all the functions, which - in trafilatura - probably will require some deep testing, not just single point async add-on. Even single async request broken in the code/process breaks async capability; but on this front latest python error catcher should do just fine communicating any unmatched async object requests. 

Needless to say, async alone also does not solve "it" necessarily, because by heuristic nature of how trafilatura processes input, the process of it is synchronous. So on this front overall Trafilatura's code (not single method call) would require even more testing with async.

So aiosync would definitely deliver some efficiencies, but in the meantime, all I can see, the only parallelization/actual-async processing with current state of trafilatura code is through usage of multiple trafilatura endpoints, such as API server pods, which I am guessing Trafilatura API runs on; unless there is some other custom code under-the-API-hood that I/we are not aware of.

**Comment by pietz** [comment]
I would also appreciate an async fetch_url version.

It's just a basic best practice when building functionalities on web servers. Given the purpose of trafilatura, it would also benefit the parallel async processing efficiently. Sure, I could just use an async GET myself, but trafilatura has quite a few things under the hood to make it smarter.

If it's not in scope, ok.
