### ISSUE TITLE
LXML 5.2.0 breaks import

### ISSUE THREAD

**Issue by marban** [adbar/trafilatura#532]
`ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
`

**Comment by rithvikshetty** [comment]
I tried installing it separately, and the error doesn't come up. But, `bare_extraction()` stops working.

**Comment by cyber-emreclskn** [comment]
same problem anyone solve this????
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.

**Comment by romanthegentle** [comment]
I downgraded to lxml == 5.1.0
And that solved it for me

**Comment by cyber-emreclskn** [comment]
but i use trafilatura package inside lxml. And i try this solution. Not worked me!!!

**Comment by UmairAhmadBaltoro** [comment]
using lxml==5.1.0 will fix your problem..

**Comment by adbar** [comment]
Alternatively you can update Trafilatura to its latest version (1.8.0), `lxml.html.clean` has been removed.

**Comment by adbar** [comment]
This is now fixed in #535, I'll issue a new Trafilatura release shortly.

**Comment by adbar** [comment]
The issue is now fixed in release 1.8.1.

**Comment by adbar** [comment]
It's already done, or can you be more specific?

**Comment by adbar** [comment]
It's normal, that's the bug fix for now.

**Comment by adbar** [comment]
LXML will be up-to-date in the next version, see #593.
