### ISSUE TITLE
Wrong encoding detected: gb2312

### ISSUE THREAD

**Issue by s-jse** [adbar/trafilatura#541]
Occasionally, the detected encoding is incorrect and I get an error saying `wrong encoding detected: gb2312`.
Related to #79.

Minimal code that reproduces the error:
```python
from trafilatura import extract, fetch_url

print(
        extract(
            requests.get(
                "http://politics.people.com.cn/n1/2023/1117/c1024-40120027.html"
            ).content
        )
    )

# or even just fetching:
print(fetch_url("http://politics.people.com.cn/n1/2023/1117/c1024-40120027.html"))
```

Environment:
```
Python: 3.10.14
requests: 2.31.0
trafilatura: 1.8.1
OS: Ubuntu 20.04
```

The problem might be that this webpage has so many HTML tags at the top (in English) while the rest is in Chinese. I'm generally wondering how the current encoding detection code would handle multilingual webpages.

Potential solution:
Removing `from_bytes(bytesobject[:15000]) or` from this line fixes the issue: https://github.com/adbar/trafilatura/blob/d9d47a71bc6c4a684e398d4939da25fb3cc670be/trafilatura/utils.py#L123

**Comment by adbar** [comment]
Hi @s-jse, thanks for reporting the issue and suggesting a fix.

I cut the test string short because it's costly to run encoding detection on large files. We could either opt for a larger detection window or take text at the end of the HTML string, since it seems to be the problem here.

**Comment by s-jse** [comment]
Thanks for looking into this.
Yeah, maybe taking samples from start, middle and end of the string and running detection on them individually (or by concatenating them) would be a good solution?

**Comment by adbar** [comment]
I tried taking text at the middle but it didn't improve the results. The code in the PR above works on your example and also makes Trafilatura run faster.
