### ISSUE TITLE
Scraping directly from wayback machine (newbie question)

### ISSUE THREAD

**Issue by scaramouche88** [adbar/trafilatura#551]
Hi!
Quite a newbie in the field, so maybe my questions are trivial.
Trafilatura seems top-notch for my application but maybe I have some misunderstanding.

I would like to extract all news from a newspaper in the past years. 
So I fetch the URLs of old snapshots with the wayback package:
`import wayback`
`client = wayback.WaybackClient()`
`results_wayback = client.search("https://antaranews.com",from_date='2020-02-07')`
`record_wayback = next(results_wayback)`
`target_url = record_wayback.raw_url`

Let's say that my target_url is: 
https://web.archive.org/web/20200101174059id_/http:/antaranews.com/

Then I would like to extract all articles / link articles. I've tried with the following methods:
`find_feed_urls` --> empty list, ok makes sense
`sitemap_search` --> empty list
`focused_crawler` --> `(set(), {'https://web.archive.org/web/20200101174059id_/http:/antaranews.com/', 'https://web.archive.org/terkini', 'https://web.archive.org/web/20200101174106id_/https:/www.antaranews.com/', 'https://web.archive.org/'})` , no useful informations
`fetch_url` and `extract` --> no article's links but a list of dates 
`1 Januari 2020 20:36`
`1 Januari 2020 20:18`
`1 Januari 2020 11:52`
`1 Januari 2020 20:05`
`1 Januari 2020 19:51`

Btw, when I download the page:
`downloaded = trafilatura.fetch_url(target_url)`
downloaded is rightfully the html code of the page...

What am I getting wrong? 
Thank you for your help

**Comment by adbar** [comment]
The web archive follows a different logic, the functionality you're using is meant for live web pages.
1. There are dedicated Python packages for retrieving documents from web archives.
2. You can then use Trafilatura to extract the content (given a series of HTML files downloaded from the archive).

**Comment by scaramouche88** [comment]
ok, I understand that about find_feed, sitemap and crawler.
But why the strategy with fetch_url and extract do not work?

(tbh I worked in the other way around: given that WM snapshots are not live web pages, I tried first with fetch + extract but since it failed I tried other approaches but I get now that they are not suited)

I attach the output of:
`downloaded = trafilatura.fetch_url(target_url)`
`result = trafilatura.extract(downloaded,include_links=True)`

it is as if there were an element (like a newsfeed) that blocks the exploration of the html file and of which it only extracts the dates/hours of publication

Jawa Timur
[Jumlah korban keracunan ikan tongkol di Jember bertambah menjadi 199 orang] (https://jatim.antaranews.com/berita/342119/jumlah-korban-keracunan-ikan-tongkol-di-jember-bertambah-menjadi-199-orang)
1 Januari 2020 22:42
Sepakbola / 11 menit lalu
Metro / 24 menit lalu
Humaniora / 25 menit lalu
Ekonomi / 1 Januari 2020 23:49
Olahraga / 1 Januari 2020 23:32
Dunia / 1 Januari 2020 23:26
Metro / 1 Januari 2020 23:25
Humaniora / 1 Januari 2020 23:20
Ekonomi / 1 Januari 2020 23:13
Humaniora / 1 Januari 2020 23:04
Ekonomi / 1 Januari 2020 22:59
Metro / 1 Januari 2020 22:56
Metro / 1 Januari 2020 22:52
Tekno / 1 Januari 2020 22:48
Humaniora / 1 Januari 2020 22:48
Metro / 1 Januari 2020 22:41
Metro / 1 Januari 2020 22:39
Humaniora / 1 Januari 2020 22:32
Sepakbola / 1 Januari 2020 22:31
Humaniora / 1 Januari 2020 22:29
Metro / 1 Januari 2020 22:24
Metro / 1 Januari 2020 22:21
Sepakbola / 1 Januari 2020 22:17
Metro / 1 Januari 2020 22:15
Humaniora / 1 Januari 2020 22:09
Metro / 1 Januari 2020 22:07
Metro / 1 Januari 2020 22:06
Hukum / 1 Januari 2020 21:55
Metro / 1 Januari 2020 21:45
Humaniora / 1 Januari 2020 21:45
[Tenis] (https://www.antaranews.com/olahraga/tenis) /
1 Januari 2020 23:32
[Balap] (https://www.antaranews.com/olahraga/balap) /
1 Januari 2020 21:35
[All Sport] (https://www.antaranews.com/olahraga/all-sport) /
1 Januari 2020 20:36
[Pentas] (https://www.antaranews.com/hiburan/pentas) /
1 Januari 2020 20:05
[Pentas] (https://www.antaranews.com/hiburan/pentas) /
1 Januari 2020 19:08
[Bisnis] (https://www.antaranews.com/ekonomi/bisnis) /
1 Januari 2020 23:49
1 Januari 2020 21:55
1 Januari 2020 21:05
1 Januari 2020 20:12
1 Januari 2020 16:02
1 Januari 2020 16:01
1 Januari 2020 12:12
1 Januari 2020 23:25
1 Januari 2020 22:56
25 menit lalu
1 Januari 2020 23:20
1 Januari 2020 23:04
[...]
1 Januari 2020 12:12
1 Januari 2020 11:40
31 Desember 2019 20:07

**Comment by adbar** [comment]
I cannot reproduce the bug, Trafilatura extracts the article text for the link you provided.

**Comment by scaramouche88** [comment]
I've made a minimal script in a separate virtual environment, to check if there were any problems with dependencies:

```
import trafilatura

url = 'https://web.archive.org/web/20190107064625id/https://www.antaranews.com/'
downloaded = trafilatura.fetch_url(url)
extracted = trafilatura.extract(downloaded,url=url,include_links=True)
print(extracted)
```

I copy the printed extracted. I repeat maybe i'm missing something very basic but it doesn't seems to me that it extracts the whole text with link, no?

```
Yogyakarta
[35 kios terbakar, pedagang merugi ratusan juta rupiah](https://web.archive.org/web/20190107064625/https://jogja.antaranews.com/berita/364486/35-kios-terbakar-pedagang-merugi-ratusan-juta-rupiah)
13 menit lalu
Nasional / 2 menit lalu
Hiburan / 2 menit lalu
Nasional / 11 menit lalu
Nasional / 7 Januari 2019 13:12
Nasional / 7 Januari 2019 13:11
Nasional / 7 Januari 2019 13:08
Nasional / 7 Januari 2019 13:02
Nasional / 7 Januari 2019 13:02
Nasional / 7 Januari 2019 12:59
Nasional / 7 Januari 2019 12:59
Ekonomi / 7 Januari 2019 12:59
Dunia / 7 Januari 2019 12:56
Hiburan / 7 Januari 2019 12:53
Nasional / 7 Januari 2019 12:52
Nasional / 7 Januari 2019 12:52
Ekonomi / 7 Januari 2019 12:51
Nasional / 7 Januari 2019 12:46
Hiburan / 7 Januari 2019 12:46
Ekonomi / 7 Januari 2019 12:45
Nasional / 7 Januari 2019 12:43
Hiburan / 7 Januari 2019 12:39
Hiburan / 7 Januari 2019 12:37
Nasional / 7 Januari 2019 12:36
Nasional / 7 Januari 2019 12:34
Warta Bumi / 7 Januari 2019 12:26
Nasional / 7 Januari 2019 12:12
Dunia / 7 Januari 2019 12:03
Nasional / 7 Januari 2019 12:01
Hiburan / 7 Januari 2019 11:50
[Sepakbola](https://web.archive.org/web/20190107064625/https://www.antaranews.com/olahraga/sepakbola) /
7 Januari 2019 11:26
[Sepakbola](https://web.archive.org/web/20190107064625/https://www.antaranews.com/olahraga/sepakbola) /
7 Januari 2019 11:18
[Basket](https://web.archive.org/web/20190107064625/https://www.antaranews.com/olahraga/basket) /
7 Januari 2019 11:14
[Sepakbola](https://web.archive.org/web/20190107064625/https://www.antaranews.com/olahraga/sepakbola) /
7 Januari 2019 10:53
[Selebritis](https://web.archive.org/web/20190107064625/https://www.antaranews.com/hiburan/selebritis) /
2 menit lalu
[Gaya Hidup](https://web.archive.org/web/20190107064625/https://www.antaranews.com/hiburan/gaya-hidup) /
7 Januari 2019 12:53
[Gaya Hidup](https://web.archive.org/web/20190107064625/https://www.antaranews.com/hiburan/gaya-hidup) /
7 Januari 2019 12:46
[Makro](https://web.archive.org/web/20190107064625/https://www.antaranews.com/ekonomi/makro) /
7 Januari 2019 12:59
[Bisnis](https://web.archive.org/web/20190107064625/https://www.antaranews.com/ekonomi/bisnis) /
7 Januari 2019 12:51
[Bursa](https://web.archive.org/web/20190107064625/https://www.antaranews.com/ekonomi/bursa) /
7 Januari 2019 12:45
6 Januari 2019 17:18
6 Januari 2019 15:50
6 Januari 2019 14:23
2 menit lalu
11 menit lalu
7 Januari 2019 13:12
7 Januari 2019 10:30
7 Januari 2019 09:27
6 Januari 2019 18:48
2 menit lalu
7 Januari 2019 12:56
7 Januari 2019 12:59
7 Januari 2019 11:26
2 menit lalu
7 Januari 2019 12:26
7 Januari 2019 10:30
```

**Comment by adbar** [comment]
Thanks for the description, I can reproduce this problem but it's a homepage. Trafilatura is geared towards article pages, blog posts, main text parts, etc. If you give a link list or a catalog as input the results vary wildly.

Here is what happens:
1. There is no main text block to be found (correct)
2. The article titles are 100% links, they are removed (not something a human would do but the heuristic on links is correct)
3. The dates are central elements with no links, so they end up being the only text being extracted (the strange result you're observing)

It's definitely a corner case but there isn't much we can do about that, it's less an article extraction and more a link extraction task.

**Comment by scaramouche88** [comment]
ok thank you a lot for the insights.
One the problem of extraction (trying now a solution with scrapy) is solved, I'll look into all the other features of Trafilatura!
