### ISSUE TITLE
strikethrough  text is returned as normal

### ISSUE THREAD

**Issue by snarb** [adbar/trafilatura#555]
I've found that strikethrough text is often (or always) returned as normal text in XML, even with include_formatting=True. For example, when scraping  [a webpage like](https://megasport.ua/ua/product/air-force-1-07_dv0788-001/?size=27.5&gad_source=1&gclid=Cj0KCQjwztOwBhD7ARIsAPDKnkAqkkkBBI0RUFk0r8ahoqUJQK6LHpn0Ba85Us_GWi4Lkn-ZsXlZ2KAaAqAYEALw_wcB) the strikethrough formatting is crucial, especially for tasks like price scraping, because we need to know if the text is strikethrough.

**Comment by adbar** [comment]
Hi, I just had a look at the page, here is how the price looks like in the HTML:

`<span class="MeSmTt EN0LY8" data-new-price="true">4&nbsp;999<!-- --> <!-- -->грн</span><span class="EGoTsG" data-old-price="true">6&nbsp;690<!-- --> <!-- -->грн</span>`

The result looks good with a browser but looking at the code I see no way to detect it as strikethrough text.
