### ISSUE TITLE
Scraping websites which are protected by WAF

### ISSUE THREAD

**Issue by thebigbone** [adbar/trafilatura#558]
I have noticed that sites which are protected by Cloudflare and other WAFs are not being scraped. I would like to propose a solution here. We can use [Flaresolverr](https://github.com/FlareSolverr/FlareSolverr) for the sites protected by Cloudflare. Let me know your thoughts on this.

**Comment by adbar** [comment]
Hi @thebigbone, thanks for your input. The principle so far is to keep the download utilities lean, also for compatibility and maintenance reasons.
The users can benefit from more complex packages on their side if necessary and then use Trafilatura on the result. So this looks more like a documentation issue to me.

**Comment by thebigbone** [comment]
That's a good approach. However, I believe it would be beneficial to provide an option for users who wish to utilize it

**Comment by adbar** [comment]
If you want to draft a PR you can add the package as optional dependency in `setup.py` and add your workaround to `downloads.py`.

**Comment by thebigbone** [comment]
Flaresolverr is not shipped as a package (and therefore no optional dependency). Rather, it exposes an API to which requests are sent to and therefore an entirely different installation procedure which is outlined in their documentation. Can we add a flag which would enable this option?

**Comment by adbar** [comment]
It's more complicated then I thought then. I have to read more about this before deciding, it could make the code unnecessarily hard to maintain.

**Comment by thebigbone** [comment]
Alright. I will wait for you to examine it. Thanks.

**Comment by adbar** [comment]
I advise against it, APIs can be brittle, it's easier to use the one you mention separately and then Trafilatura on the HTML content.
