### ISSUE TITLE
AttributeError: module 'regex' has no attribute 'compile'

### ISSUE THREAD

**Issue by sreekarn** [adbar/trafilatura#56]
When i'm trying to import trafilatura, it throws an error that regex has no compile attribute, I have installed version trafilatura-0.8.0. I'm currently running it in jupyter notebook.

**Comment by adbar** [comment]
Hi, thanks for the feedback. Could you please copy the whole error message that you see?

**Comment by sreekarn** [comment]
<re.Match object; span=(14, 17), match='abc'>
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-233cc9b7e875> in <module>
----> 1 import trafilatura

F:\sreekar\lib\site-packages\trafilatura\__init__.py in <module>
     14 import logging
     15 
---> 16 from .core import bare_extraction, extract, process_record
     17 from .utils import fetch_url, load_html
     18 

F:\sreekar\lib\site-packages\trafilatura\core.py in <module>
     25                              link_density_test, link_density_test_tables,
     26                              process_node, tree_cleaning)
---> 27 from .metadata import extract_metadata, METADATA_LIST
     28 from .settings import use_config, DEFAULT_CONFIG, TAG_CATALOG
     29 from .utils import load_html, trim, txttocsv, is_image_file

F:\sreekar\lib\site-packages\trafilatura\metadata.py in <module>
     10 from courlan.core import extract_domain
     11 from courlan.filters import validate_url
---> 12 from htmldate import find_date
     13 from lxml import html
     14 

F:\sreekar\lib\site-packages\htmldate\__init__.py in <module>
     13 import logging
     14 
---> 15 from .core import find_date
     16 
     17 try:  # Python 2.7+

F:\sreekar\lib\site-packages\htmldate\core.py in <module>
     17 
     18 # own
---> 19 from .extractors import (discard_unwanted, extract_url_date,
     20                          extract_partial_url_date, idiosyncrasies_search,
     21                          json_search, timestamp_search, try_ymd_date,

F:\sreekar\lib\site-packages\htmldate\extractors.py in <module>
     16 # coverage for date parsing
     17 #try:
---> 18 import dateparser  # third-party, slow
     19 EXTERNAL_PARSER = dateparser.DateDataParser(settings={
     20     'PREFER_DAY_OF_MONTH': 'first', 'PREFER_DATES_FROM': 'past',

F:\sreekar\lib\site-packages\dateparser\__init__.py in <module>
      1 __version__ = '1.0.0'
      2 
----> 3 from .date import DateDataParser
      4 from .conf import apply_settings
      5 

F:\sreekar\lib\site-packages\dateparser\date.py in <module>
      7 from dateutil.relativedelta import relativedelta
      8 
----> 9 from dateparser.date_parser import date_parser
     10 from dateparser.freshness_date_parser import freshness_date_parser
     11 from dateparser.languages.loader import LocaleDataLoader

F:\sreekar\lib\site-packages\dateparser\date_parser.py in <module>
      1 from tzlocal import get_localzone
      2 
----> 3 from .timezone_parser import pop_tz_offset_from_string
      4 from .utils import strip_braces, apply_timezone, localize_timezone
      5 from .conf import apply_settings

F:\sreekar\lib\site-packages\dateparser\timezone_parser.py in <module>
     85 
     86 _search_regex_parts = []
---> 87 _tz_offsets = list(build_tz_offsets(_search_regex_parts))
     88 _search_regex = re.compile('|'.join(_search_regex_parts))
     89 _search_regex_ignorecase = re.compile(

F:\sreekar\lib\site-packages\dateparser\timezone_parser.py in build_tz_offsets(search_regex_parts)
     69             for tz_obj in tz_info['timezones']:
     70                 search_regex_parts.append(tz_obj[0])
---> 71                 yield get_offset(tz_obj, regex)
     72 
     73             # alternate patterns

F:\sreekar\lib\site-packages\dateparser\timezone_parser.py in get_offset(tz_obj, regex, repl, replw)
     60             tz_obj[0],
     61             {
---> 62                 'regex': re.compile(re.sub(repl, replw, regex % tz_obj[0]), re.IGNORECASE),
     63                 'offset': timedelta(seconds=tz_obj[1])
     64             }

AttributeError: module 'regex' has no attribute 'compile'

The command I ran was import trafilatura statement

**Comment by adbar** [comment]
The error happens in an external module, I've opened an issue there.
In the meantime I patched the `htmldate` module (part of trafilatura) which was raising the error.

Please try installing the latest version from the repository (`pip install -U git+https://github.com/adbar/htmldate.git`) and tell me if the problem is solved.

**Comment by sreekarn** [comment]
Hello,

Thanks for the response,

Although, after updating, I'm still facing same issue:

<re.Match object; span=(14, 17), match='abc'>
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-233cc9b7e875> in <module>
----> 1 import trafilatura

F:\sreekar\lib\site-packages\trafilatura\__init__.py in <module>
     14 import logging
     15 
---> 16 from .core import bare_extraction, extract, process_record
     17 from .utils import fetch_url, load_html
     18 

F:\sreekar\lib\site-packages\trafilatura\core.py in <module>
     25                              link_density_test, link_density_test_tables,
     26                              process_node, tree_cleaning)
---> 27 from .metadata import extract_metadata, METADATA_LIST
     28 from .settings import use_config, DEFAULT_CONFIG, TAG_CATALOG
     29 from .utils import load_html, trim, txttocsv, is_image_file

F:\sreekar\lib\site-packages\trafilatura\metadata.py in <module>
     10 from courlan.core import extract_domain
     11 from courlan.filters import validate_url
---> 12 from htmldate import find_date
     13 from lxml import html
     14 

F:\sreekar\lib\site-packages\htmldate\__init__.py in <module>
     13 import logging
     14 
---> 15 from .core import find_date
     16 
     17 try:  # Python 2.7+

F:\sreekar\lib\site-packages\htmldate\core.py in <module>
     17 
     18 # own
---> 19 from .extractors import (discard_unwanted, extract_url_date,
     20                          extract_partial_url_date, idiosyncrasies_search,
     21                          json_search, timestamp_search, try_ymd_date,

F:\sreekar\lib\site-packages\htmldate\extractors.py in <module>
    114 JSON_PATTERN_PUBLISHED = \
    115   re.compile(r'"datePublished": ?"([0-9]{4}-[0-9]{2}-[0-9]{2})')
--> 116 TIMESTAMP_PATTERN = regex.compile(r'([0-9]{4}-[0-9]{2}-[0-9]{2}|[0-9]{2}\.[0-9]{2}\.[0-9]{4}).[0-9]{2}:[0-9]{2}:[0-9]{2}')
    117 
    118 # English + German + Turkish dates cache

AttributeError: module 'regex' has no attribute 'compile'

**Comment by adbar** [comment]
- Which version of Python are you using?
- Do you have somewhere in your working directory a file named `regex` or did you make modifications to `re` or `regex` modules locally?
See this thread: https://stackoverflow.com/questions/38555161/attributeerror-module-object-has-no-attribute-compile

**Comment by sreekarn** [comment]
Hi,

I used python 3.7.6.
Do you have somewhere in your working directory a file named regex or did you make modifications to re or regex modules locally?
Yes, I created file at other location and trafilatura has been imported, thank you so much and so sorry for the trouble.

Regards
Sreekar
