### ISSUE TITLE
Content failed to be extracted

### ISSUE THREAD

**Issue by alroythalus** [adbar/trafilatura#568]
The contact section of  https://www.mozilla.org/en-US/privacy/ gets missed out
![image](https://github.com/adbar/trafilatura/assets/119865678/f173f71b-18e8-4ce6-9321-98a33aae4f37)
This is my code
`        extract(
            web_content,
            include_formatting=True,
            include_tables=True,
            include_comments=False,
            include_links=False,
            output_format="xml",
            favor_recall=True,
            config=config,
        )`
        
        
 What I've noticed is that the contact section is placed between a footer tag separate from the main footer.
 Can anything be done besides ignoring footers all together?

**Comment by adbar** [comment]
As you say it is part of a footer so I would say it is too far-fetched to try to retrieve this kind of content.
