### ISSUE TITLE
Is there a way to extract a top image from an article?

### ISSUE THREAD

**Issue by ArturasDruteika** [adbar/trafilatura#57]
article_trafilatura = trafilatura.bare_extraction(trafilatura.fetch_url(url), include_images=True)

When I set include_images=True, I get article src, but it seems to miss the  top article image src. Is it meant to be this way or is it still not implemented or am I doing something wrong? I have tried passing different urls from different websites but still I cannot find a way how to extract that image.

**Comment by adbar** [comment]
Hi, trafilatura is optimized for text retrieval, if the images you're looking for are not within the main text they will not be displayed in the processed document. Can you please give me an example of a webpage where the top image is missing?

**Comment by ArturasDruteika** [comment]
@adbar Fox example this article: https://edition.cnn.com/2021/03/08/uk/meghan-harry-oprah-interview-recap-scli-gbr-intl/index.html. Maybe I am missing something but aren't all the article photos inside the main text frame?

**Comment by adbar** [comment]
Thanks for the input, this is indeed a bug, I'll look into it. Do you have other similar examples?

**Comment by adbar** [comment]
@ArturasDruteika Do you have other similar examples?

**Comment by AliaHamwi** [comment]
Hello
I have this examples 
https://thepopinsider.com/news/shang-chi-trailer/
https://www.cnet.com/news/explosive-marvel-shang-chi-trailer-reveals-the-new-mandarin/

**Comment by adbar** [comment]
The second one now works but not this one:
https://thepopinsider.com/news/shang-chi-trailer/

**Comment by phongtnit** [comment]
Hi @adbar , please check url https://www.scmp.com/lifestyle/families/article/2160779/three-reasons-more-chinese-indonesians-are-learning-mandarin-and . When I fetch the article with `include_images=True`, the `graphic` tag have no `src` attribute.

**Comment by adbar** [comment]
Hi @phongtnit, the SCMP article you mention is a different bug, I opened another thread.

The second link above and the others mentioned earlier are now fixed in a4d0bd1dc903d79b812f897d9e7cfe07ba6550f6. @phongtnit @ArturasDruteika @AliaHamwi

**Comment by pranav-profjim** [comment]
Hi, I know this is an old thread, but I have several examples where it fails to fetch images:

1. https://openstax.org/books/anatomy-and-physiology/pages/6-1-the-functions-of-the-skeletal-system#fig-ch06_01_04
2. https://openstax.org/books/anatomy-and-physiology/pages/1-1-overview-of-anatomy-and-physiology

Basically, all images on that domain seem to get missed on the output XML

**Comment by adbar** [comment]
Hi @pranav-profjim, images are not my priority but I reopen the thread and will have a look at your cases later.

**Comment by pofey** [comment]
<p><img src="/assets/dashboard_apikeys.fff14e02.jpg" alt="API Keys"></p>
test page: https://docs.aiproxy.io/guide/quick-start
This type of link also cannot be resolved, is it possible to fix it, or can you provide suggestions for improvement?

**Comment by adbar** [comment]
@pofey Images are not my priority, I'm not sure how to fix it but let's keep the issue open to have a look at it.
