### ISSUE TITLE
<li> tag output in TXT

### ISSUE THREAD

**Issue by ethael** [adbar/trafilatura#597]
Hi there. First, thank you for the great library!

I want to parse health condition data from NHS. For example: https://www.nhs.uk/conditions/kyphosis/

The resulting markdown always messes up the bullet formatting like so:

_back pain and stiffness
\-
tenderness of the spine
\-
tiredness
\-_

the result of course should have been:

_\- back pain and stiffness
\- tenderness of the spine
\- tiredness_

trafilatura version: 1.9.0
call is made with all configs/presets set on default like so: trafilatura.extract(html)

**Comment by adbar** [comment]
Thanks for your input, this is a regression, the XML output works fine, something happens during conversion to TXT.
