### ISSUE TITLE
Footer removal

### ISSUE THREAD

**Issue by hamsarajan** [adbar/trafilatura#617]
I've encountered an issue when extracting text in Vietnamese. It appears that a portion of the footer of a webpage is still being extracted. An example would be this article: https://myrica.vn/. Would appreciate your help in this matter!

**Snippet of the Vietnamese text extracted:**
Nôi cũi
Ghế ngồi ô tô
Mua ở đâu
Đăng ký serial
Xe đẩy trẻ em Myrica ALB1VN - hồng phấn
Xe đẩy trẻ em Myrica ALB1VN - xanh mint
Xe đẩy trẻ em Myrica ALB1VN - ghi xám
Tại sao chọn
Công ty TNHH ĐT Và TM QT Thanh Mai Đỏ
Số 32 Yên Ninh, Trúc Bạch, Ba Đình, Hà Nội
Ngày cấp: 27/11/2018, Sở KHĐTHN
Kết nối:
Bảo hành / Đổi trả hàng
Câu hỏi thường gặp FAQ
```
Tầm nhìn, sứ mệnh
Bản quyền thuộc về Myrica co., ltd
```

**Translation:**
Crib
Car seats
Where do you buy it
Register serial
Myrica ALB1VN baby stroller - pink
Myrica ALB1VN baby stroller - mint green
Myrica ALB1VN baby stroller - gray
Why choose
Thanh Mai Do International Investment and Trading Company Limited
No. 32 Yen Ninh, Truc Bach, Ba Dinh, Hanoi
Date of issue: November 27, 2018, Department of Planning and Development
Connect:
Warranty / Returns
Frequently asked questions FAQ
```
Vision, mission
Copyright belongs to Myrica co., ltd
```

**Comment by adbar** [comment]
Trafilatura does not work as well on index pages and catalogs because there is no main article to extract. That being said there is an issue here, all extraction methods fail and all the text on the page is then in the output.
