### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by ernests** [adbar/trafilatura#62]
Me again :)

I'm trying to extract metadata and encountered this error. Dug a bit deeper and it was caused by metadata extractor. Particularly in this case extracting title.
In html <title> tag is empty - `<title></title>` and inside  `<head></head>`. There is plenty of meta tags and js garbage also and I couldn't make short example to reproduce it but I found solution.

In extract_sitename:

```python
def extract_sitename(tree):
    '''Extract the name of a site from the main title (if it exists)'''
    title_elem = tree.find('.//head/title')
    print (title_elem.text_content())

    if title_elem is not None:

        try:
            mymatch = re.search(r'^.*?[-|]\s+(.*)$', title_elem.text)
            if mymatch:
                return mymatch.group(1)
        except AttributeError:
            pass
    return None
```

it checks ` if title_elem is not None`. My `title_elem` passes this and returns `True`
But when passed to regex raises this error.

I checked `title_elem.text_content()` and it is empty
I also checked `type(title_elem.text)` and shows that it is `NoneType` and is cause for the error.

To fix this, you have to check `if title_elem.text is not None` instead of just `title_elem`

**Comment by adbar** [comment]
Thanks, it's fixed in 694cf8513f4929c4683ceae46d7ff2530c41d1e0.
