### ISSUE TITLE
Parts of article block are sometimes not being extracted

### ISSUE THREAD

**Issue by naktinis** [adbar/trafilatura#622]
First noticed this when trying to extract text from [1Password documentation](https://developer.1password.com/docs/web/compatible-website-design/) and realized that code blocks are not being extracted.

Then reduced it to a minimal reproducible example.

Version tested: `1.10.0`.

HTML:
```html
<!DOCTYPE html>
<html>
  <body>
    <article>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
        veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
        commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
        velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
        cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
        veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea.
      </p>

      <div>
        This is a very important line that is part of the article.
      </div>

      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
        veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
        commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
        velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
        cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.
      </p>
    </article>
  </body>
</html>
```

Extract call:
```
extract(h, include_formatting=True, favor_recall=True)
```

Output (does not include "This is a very important..."):
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.
```

Is there a reason why the text within a `<div>` block is being ignored, and would there be any way to change this behavior? Ideally maybe wouldn't even need to favor recall.

**Comment by adbar** [comment]
@naktinis Yes there is a reason, text within div (and nothing else) is generally undesirable. It is always a tradeoff between precision and recall.

The easiest way I see is to add `"div"` manually in `settings.TAG_CATALOG` and re-install the package locally, it should be propagated to the extractors. Does that solve your problem?

**Comment by adbar** [comment]
@naktinis Do you have anything new to report on this and it is still an issue?

**Comment by naktinis** [comment]
@adbar thank you for the response.

I don't have anything new to report. It is unfortunate that some sites don't use semantically correct tags (it should have been `<code>` in this example). I guess there's not much we can do without affecting parsing of other sites.

The only suggestion would be to make `settings.TAG_CATALOG` customizable without making manual changes to the code. That being said, I don't think we'd be using that at this point anyway because it would have side effects on other sites.

So I guess we can close this now, still just wanted to mention this real-life issue in case some solution could come in the future (like detecting whether a `<div>` contains "text content for people to read" vs "a button" or "an ad" etc.).
