### ISSUE TITLE
Error parsing non-English web pages

### ISSUE THREAD

**Issue by vodkaslime** [adbar/trafilatura#626]
Try this code:

```
url = "https://vip.stock.finance.sina.com.cn/corp/view/vCB_AllBulletinDetail.php?id=8117044"
downloaded = trafilatura.fetch_url(url)
print(downloaded)
```
Then you got a bunch of broken chars.

Not sure if this is relevant to issue https://github.com/adbar/trafilatura/issues/541.

But interestingly, if I use `requests` instead, it works well... I could even do

```
res = requests.get(url)
content = trafilatura.extract(res.text)
```

Confusions:
1. Good to see `trafilatura.extract()` working well with `requests`, but is this supposed to be? Any potential discrepencies?
3. Why could `requests` raw api correctly detect/parse encodings, while `trafilatura` could not? How to get it fixed?

**Comment by adbar** [comment]
Hi @vodkaslime, I recommend installing the optional dependency `cchardet` which works well for encodings common in East Asia.

I cannot reproduce the bug with it, does that solve your problem?

**Comment by vodkaslime** [comment]
Oh that works. Thanks @adbar !
