### ISSUE TITLE
links/urls are not apprearing using extract

### ISSUE THREAD

**Issue by alroythalus** [adbar/trafilatura#636]
extract(
            web_content,
            include_formatting=False,
            include_tables=True,
            include_comments=False,
            include_links=True,
            output_format="xml",
            favor_recall=True,
            config=config,
        )
    )  # type: ignore
    
    
    with this config urls are not showing up. What is the issu. How can it be fixed?
    
sites tested on
https://openai.com/policies/privacy-policy/
https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement

@adbar

**Comment by adbar** [comment]
@alroythalus I just tested the Github example and the links are in the XML output, here is a small example:

```
To remove content or information you have publicly posted, please submit a <ref target="https://support.github.com/contact/private-information">Private Information Removal request</ref>.
```

I cannot reproduce the bug, can you see if it works for you or if you can provide more information?
