### ISSUE TITLE
Can I get an extracted element's CSS selector?

### ISSUE THREAD

**Issue by theabhinavdas** [adbar/trafilatura#639]
Hi @adbar. Firstly, I would like to thank you for such a brilliant piece of FOSS work.

My question - I'm wondering if it's possible to extract the CSS selector for an element that trafilatura finds? 

Like if it finds the HTML element that contains the main body of a webpage, could I proceed to then get it's CSS selector somehow? 

I recognize that changes to the library may be necessary and I'm willing to make such changes if you're able to point me in the right direction! 🙏

**Comment by adbar** [comment]
The main extractor changes the document, it simplifies it and prunes certain sections, so I am afraid your question goes beyond the current capabilities of the package.

**Comment by theabhinavdas** [comment]
Understood! Thanks, @adbar :)
