### ISSUE TITLE
Question about deduplication

### ISSUE THREAD

**Issue by Yomguithereal** [adbar/trafilatura#65]
Hello @adbar, just a methodological question: would you say your deduplication (through the `deduplicate` kwarg) scheme is robust enough so that it could be set to `True` by default in most use cases? It seems to me this is often what you want (notably to avoid some html templating patterns that duplicate information) but I would need to be sure this is not a potentially dangerous/lossy mechanism.

**Comment by adbar** [comment]
Hi @Yomguithereal, deduplication isn't fully functional yet (#3) but it works: Trafilatura can be expected to omit text present more than _x_ times (defaults to 2, see `settings.cfg` file) on document and element levels.

Here are a few potential caveats:
- If you're using threads or multiprocessing the memory won't be shared across processes, so you might miss potential duplicates
- The detection can get too greedy if documents contain similar parts (#17)
- I didn't test it thoroughly so particular element types might still escape detection on element level

You can also have a look at content fingerprinting currently present in XML output to conveniently detect duplicates on document level by comparing the hashes:https://github.com/adbar/trafilatura/blob/081447413383a082e3069af2a883e405286c8b7e/trafilatura/filters.py#L117

And of course near duplicate removal would be best but it goes beyond the scope of the package for now.

**Comment by Yomguithereal** [comment]
> If you're using threads or multiprocessing

I am :). But if you can guarantee that the deduplication is at least coherent for a single document it should be alright for me. Memory might be an issue also but I guess you already have a way not to let it overflow?

> You can also have a look at content fingerprinting 

Sorry if this can be found in the docs, but is this fingerprint present in the `bare_extraction` output?

> And of course near duplicate removal would be best but it goes beyond the scope of the package for now.

I have tools for this relying on minhash variants tailored to this use case :)

**Comment by adbar** [comment]
> I am :). But if you can guarantee that the deduplication is at least coherent for a single document it should be alright for me. Memory might be an issue also but I guess you already have a way not to let it overflow?

The computation is efficient in terms of CPU and memory, there shouldn't be any problems.

>Sorry if this can be found in the docs, but is this fingerprint present in the bare_extraction output?

No, I have to add in to the docs... The fingerprinting function just takes any string as input:
`from trafilatura.filters import content_fingerprint`
`content_fingerprint('aaaaa bbbbb')`
For now it's only meant to be used on document level (only usable with at least one word of length 5).

> I have tools for this relying on minhash variants tailored to this use case :)

I'm interested ;) Could you point me to the place in the code where you run minhash-like deduplication?

**Comment by adbar** [comment]
@Yomguithereal any input on where you run minhash-like deduplication?

**Comment by Yomguithereal** [comment]
Sorry @adbar I haven't found the time to release the code yet. But part of it can be found [here](https://github.com/Yomguithereal/fog/blob/master/fog/lsh/minhash.py) (especially the `SuperMinHash` and `LSBMinHash` implementations). I also need to scour my Zotero library to find the juicy papers back.

**Comment by adbar** [comment]
I'm assuming that `deduplicate` didn't cause any trouble so I'm closing the issue for now. Feel free to re-open it if you run into bugs.

**Comment by MaureyCesar** [comment]
Hi ! I just reopen this cause I have a question : I've noticed that the deduplicate True does give me way better results on one single text extraction. However, as I use trafilatura for extraction only in my code, I do need to "reset" the cache or something like that for the deduplicate kwargs. So is there a way to do that in a clean way ? Thanks in advance !
