### ISSUE TITLE
Add magic_html to benchmarks

### ISSUE THREAD

**Issue by dantetemplar** [adbar/trafilatura#650]
Authors have stated that [magic_html](https://github.com/opendatalab/magic-html?tab=readme-ov-file#benchmark-report) outperforms similar libraries including trafilatura. I'm not sure how relevant their benchmark is. It would be great if you included this library in your evaluation [tables](https://trafilatura.readthedocs.io/en/latest/evaluation.html).

**Comment by adbar** [comment]
Hi @dantetemplar, thanks for the link, the package is interesting indeed.

They evaluate the packages on 200-300 webpages and forums in Chinese, this is a pretty specific use case and things would look different on a larger, more international benchmark, but it would be good to add magic_html all the same.

**Comment by adbar** [comment]
I had to tweak the evaluation script in the magic_html repository because it doesn't work as is. In the end magic_html is not better than other alternatives, the PR above will be merged soon.
