### ISSUE TITLE
Processing homepages of news sites.

### ISSUE THREAD

**Issue by ydennisy** [adbar/trafilatura#66]
Hi again @adbar!

Again cheers for a great lib :)

I have been struggling to get any meaningful results from the library for pages such as: https://www.yorkshirepost.co.uk/

Where we mainly have links to other pages, is this the desired and expected behaviour?

Thanks!

**Comment by adbar** [comment]
Hi @ydennisy, thanks!

Yes, this is expected since there is no main text to be found, not even
loose <p>-elements. The extractors target actual article pages, e.g.
https://www.yorkshirepost.co.uk/news/people/biker-dies-in-collision-with-estate-car-near-ferrybridge-power-station-3201739

**Comment by ydennisy** [comment]
Thanks @adbar do you have any suggestions on how one may extract information from a page such as this?

Most homepages are of this style, and have high traffic, so should get some attention :) 

I feel capturing the article names is valuable. Would you agree?

**Comment by adbar** [comment]
Thanks @ydennisy for the input.

Although I'm not primarily interested by such segments some users indeed wish to extract all potentially interesting text parts.

Let's try to address it in a future version (see also #68).

**Comment by ydennisy** [comment]
Thanks - that is a possible solution, but why not extend the current functionality where a user can request elements such as comments, to lists also?

**Comment by adbar** [comment]
Lists are already part of the potential output, there are just absent when there isn't any article-style layout or when they are full of links (as it often means boilerplate parts).
A homepage like in your example combines both characteristics, these are tricky text parts to extract. I guess it's better to implement a recall-based preset which would yield text whatever happens.

**Comment by adbar** [comment]
You can follow #68 for updated info, I'm closing this issue for now.
