### ISSUE TITLE
How can I set the proxy IP port and userAgent to avoid the web anti-crawler mechanism?

### ISSUE THREAD

**Issue by coderwpf** [adbar/trafilatura#666]
How can I set the proxy IP port and userAgent to avoid the web anti-crawler mechanism? thanks

**Comment by coderwpf** [comment]
Also, how to set the reffer for website requests and how to bypass anti-crawler mechanisms similar to JA3 ？

**Comment by adbar** [comment]
Trafilatura does not currently provide all of the functions you mention, there are other libraries for that, you can then use Trafilatura on the downloaded HTML content.

- User agents and cookies can be set in the `settings.cfg` file
- For ideas on downloads see the [troubleshooting section of the docs](https://trafilatura.readthedocs.io/en/latest/troubleshooting.html)
