### ISSUE TITLE
AttributeError in prune_unwanted_sections

### ISSUE THREAD

**Issue by Honesty-of-the-Cavernous-Tissue** [adbar/trafilatura#667]
`trafilatura`: 1.12.0

`AttributeError: 'NoneType' object has no attribute 'remove'`
at here: https://github.com/adbar/trafilatura/blob/c642ab65e7385cf49804f458e4d1eb8902981878/trafilatura/main_extractor.py#L529

```
url = 'http://www.gunbargain.com/'
```

**Comment by adbar** [comment]
@Honesty-of-the-Cavernous-Tissue I cannot reproduce the bug, the page is offline and the [archived version](https://web.archive.org/web/20240413154814/http://www.gunbargain.com/) of it does not trigger it. Are you using a particular combination of options?

**Comment by Honesty-of-the-Cavernous-Tissue** [comment]
> @Honesty-of-the-Cavernous-Tissue I cannot reproduce the bug, the page is offline and the [archived version](https://web.archive.org/web/20240413154814/http://www.gunbargain.com/) of it does not trigger it. Are you using a particular combination of options?我无法重现该错误，该页面已离线并且其[存档版本](https://web.archive.org/web/20240413154814/http://www.gunbargain.com/)不会触发该错误。您是否使用特定的选项组合？

here's the content which cause this error that extracted from WARC: https://github.com/Honesty-of-the-Cavernous-Tissue/trafilatura/blob/master/tests/test.html
forgive me for i don't kown if this is a general error.
