### ISSUE TITLE
trafilatura version > 1.10.0 doesnt fetch images

### ISSUE THREAD

**Issue by rkiacnhg** [adbar/trafilatura#670]
Assuming the same html string, versions <= 1.10.0 work as desired when fetching images (thumbnails) but versions > 1.10.0 do not.

**Comment by adbar** [comment]
Hi @rkiacnhg, the image tests are passing so I don't see where the regression could be. Can you provide a short example so that I can reproduce it?

**Comment by rkiacnhg** [comment]
Hi @adbar, apologies for not including an example earlier.

This is the response for [https://www.bbc.com/news/10462520](url) for version 1.10.0
`{'thumbnail': 'https://ichef.bbci.co.uk/news/1024/branded_news/15C7E/production/_90041298_p01tlf61.jpg', 'url': 'https://www.bbc.com/news/10462520', 'tags': [], 'html': '<p>One-minute World NewsThis video can not be playedTo play this video you need to enable JavaScript in your browser.One-minute World NewsCloseWatch the latest news summary from BBC World News. International news updated 24 hours a day.SectionNewsPublished8 hours agoShareclose panelShare pageCopy linkAbout sharingRead description</p>', 'title': 'One-minute World News', 'source': 'BBC', 'description': 'Watch the latest news summary from BBC World News. International news updated 24 hours a day.', 'published_time': '2024-08-12 00:58:44.293694+00:00', 'category': '', 'author': None}`

This is the respone for the same url for version 1.12.0.
`{'thumbnail': None, 'url': 'https://www.bbc.com/news/10462520', 'tags': None, 'html': '<h1>One-minute World News</h1>\n<p>Watch the latest news summary from BBC World News. International news updated 24 hours a day.</p>', 'title': 'One-minute World News', 'source': 'BBC', 'description': None, 'published_time': '2024-08-12 00:58:22.593073+00:00', 'category': '', 'author': None}`

Thumbnails and descriptions are left out in the new versions' response, it seems.

This is the line of code I am using:
`traf = trafilatura.bare_extraction(data, include_images = True, include_formatting = True, favor_precision= True)`

Thanks,
Richard

**Comment by adbar** [comment]
See changelog:

[trafilatura-1.11.0](https://github.com/adbar/trafilatura/releases/tag/v1.11.0)

Breaking change:

- metadata now skipped by default (https://github.com/adbar/trafilatura/pull/613), to trigger inclusion in all output formats:
   - `with_metadata=True` (Python)
   - `--with-metadata` (CLI)
