### ISSUE TITLE
Missing some text information from markdown file

### ISSUE THREAD

**Issue by lalitpagaria** [adbar/trafilatura#69]
First thank you for awesome web scrapping tool.

While paying with this to evaluate it for my personal project, I found that for my links parsing some output txt is missing.
I tried following examples and in all cases out is missing large chunk information from the top. It might be use to the way this readme is written.  I tried following commands -
```
trafilatura -u "https://github.com/lalitpagaria/obsei" 
trafilatura -u "https://github.com/lalitpagaria/obsei/blob/master/README.md" 
trafilatura -u "https://lalitpagaria.github.io/obsei/" 
```
In all the three cases I am getting output from following location -
![image](https://user-images.githubusercontent.com/19303690/115462649-2f8d1280-a22b-11eb-88f2-7b7f7fa96f05.png)

I am sure I might be doing something wrong :)

**Comment by adbar** [comment]
Hi, thanks for your feedback. Your sample webpage is tricky to extract because of the richness of its markup, which confuses the generic algorithms. I'm planning a recall-oriented preset for similar cases (see #68).

**Comment by lalitpagaria** [comment]
Thank you.
Please let me know if you would like me to test intermediate changes. I am working on one project to fetch readme of all my favourite GitHub repos and push that structured data to neutral search (similarity search) engine like haystack. So that I can reference repo later based on my search criteria. For this purpose I am looking for good web parsers (already tried multiple), but most of them are loosing structure like heading, title etc.

**Comment by adbar** [comment]
Hi @lalitpagaria, I fixed an issue related to the bug you mentioned, please try the latest version of the repository, it should work better now:
pip or pip3 `install -U git+https://github.com/adbar/trafilatura.git`

**Comment by adbar** [comment]
The "fast" option (without fallback extraction, `-f`/`--fast`) works to some extent for the two cases you mention, you could also try it:

`trafilatura --fast -u "https://github.com/lalitpagaria/obsei"`

**Comment by lalitpagaria** [comment]
Thank you @adbar 
My bad, I did not explored all the available options.

Yes output from `-f` option is good enough for me to start my project.

Again thank you very much for this awesome tool.

**Comment by adbar** [comment]
Hi @lalitpagaria, thanks for reporting the bug, even in the `fast` version it's only fixed since the commit above.
