### ISSUE TITLE
ImportError: lxml.html.clean module is now a separate project

### ISSUE THREAD

**Issue by regstuff** [adbar/trafilatura#693]
Saw the issue [here](https://github.com/adbar/trafilatura/issues/532) but the fix isn't working for me.
I'm still getting this error. I'm on Windows if that matters. Python 3.9.13. Also seeing this issue on a Ubuntu 22 system with python 3.10
Installed the latest Trafilatura from pypi.
Installed using `pip install --no-cache-dir --force-reinstall trafilatura` to make sure I don't use any cached versions.
Here are some relevant package versions in my pip list
```
trafilatura        1.12.1
jusText            3.0.1
lxml               5.3.0
```
The error I get is
```
Traceback (most recent call last):
  File "D:\Code\researchbot\app.py", line 5, in <module>
    from trafilatura import fetch_url, extract
  File "D:\Code\researchbot\researchbot\lib\site-packages\trafilatura\__init__.py", line 18, in <module>
    from .core import bare_extraction, extract, process_record
  File "D:\Code\researchbot\researchbot\lib\site-packages\trafilatura\core.py", line 16, in <module>
    from .external import compare_extraction
  File "D:\Code\researchbot\researchbot\lib\site-packages\trafilatura\external.py", line 9, in <module>
    from justext.core import (ParagraphMaker, classify_paragraphs,
  File "D:\Code\researchbot\researchbot\lib\site-packages\justext\__init__.py", line 12, in <module>
    from .core import justext
  File "D:\Code\researchbot\researchbot\lib\site-packages\justext\core.py", line 21, in <module> 
    from lxml.html.clean import Cleaner
  File "D:\Code\researchbot\researchbot\lib\site-packages\lxml\html\clean.py", line 18, in <module>
    raise ImportError(
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
Install lxml[html_clean] or lxml_html_clean directly.
```

Also tried downgrading lxml to 5.1.0 and also installing lxml.html.clean separately but now I get a different error
`TypeError: extract() takes 0 positional arguments but 1 was given`

**Comment by adbar** [comment]
@regstuff Thanks for the details, I can neither reproduce the first nor the second error. Trafilatura is tested across platforms and updating it with justext solves the problem.

Python dependency management can be tricky and I think there is a problem with the way you install or use packages. I suggest to perform a clean install with a virtual environment (e.g. venv or pyenv). In the worst case you can always install lxml[html_clean] and see how it goes.

**Comment by regstuff** [comment]
@adbar 
Confirmed. Some issue one my side
For some reason, when running in threads, this wouldn't work
```
from trafilatura import extract, fetch_url
downloaded = fetch_url(url)
if downloaded:
    text = extract(downloaded)
```

I had to do this:
```
import trafilatura
downloaded = trafilatura.fetch_url(url)
if downloaded:
    text = trafilatura.extract(downloaded)
```
