### ISSUE TITLE
bare_extraction URL empty on success

### ISSUE THREAD

**Issue by vprelovac** [adbar/trafilatura#70]
First of all thank you for creating a very promising scraping library. I like your attention to detail and benchmarks.

Here is example code:
trafilatura.bare_extraction(trafilatura.fetch_url('http://www.k2.t.u-tokyo.ac.jp/vision/DPM/'), include_comments=False)

Returned is:
{'title': 'System Vision Design: High Speed Image Processing', 'author': None, **'url': None,** 'hostname': None, 'description': None, 

(URL is empty) although the lib correctly redirects to http://ishikawa-vision.org/vision/DPM/ and extracts title/content from it.

The lib should always return the URL of the page it landed at.

Also what would be very useful is to have HTTP status code of the landing page (200, 404, 403 etc..) for additional context. Maybe there is already a way to get status code with the response?

Thank you!!

**Comment by adbar** [comment]
Hi @vprelovac, thanks for the feedback, there is indeed something missing here.

Unlike `bare_extraction()` the `extract()` function works as expected but most importantly it would be better to have the redirection URL instead of the input one. I guess the underlying `urllib3` library makes it possible to store the redirect URL.

**Comment by Yomguithereal** [comment]
> I guess the underlying `urllib3` library makes it possible to store the redirect URL.

@adbar, yes it should be under `response.geturl()` if I recall correctly.

**Comment by vprelovac** [comment]
> Hi @vprelovac, thanks for the feedback, there is indeed something missing here.
> 
> Unlike `bare_extraction()` the `extract()` function works as expected but most importantly it would be better to have the redirection URL instead of the input one. I guess the underlying `urllib3` library makes it possible to store the redirect URL.

extract() does not return url, title etc that bare_extraction() does. It just returns plain text?

>>> trafilatura.extract(trafilatura.fetch_url('http://www.k2.t.u-tokyo.ac.jp/vision/DPM/'), include_comments=False)
'Projection mapping attracts attentions as an emerging technology to extend the real world. However, almost realized examples have been limited to static or quasi-static environments. This research aims at overcoming this limitation and realizes dynamic projection mapping in which dynamically-changing real-world and virtual visual information are completely merged in the level of human visual perception. This high-speed dynamic projection mapping requires a high-speed projector ena


Ideally I wanto to be able to get

lading page url (after redirects)
status code of that page
title
text

What is the best way to do it?

**Comment by adbar** [comment]
Hi @vprelovac, I will think about adding the redirect and status code info to trafilatura.

If you want this information straight away you could perform the HTTP request on your own, gathering everything you need, and then pass the response to trafilatura to extract the necessary info (here title and text):
- `bare_extraction()` will do the trick
- choosing `extract()` with JSON or XML format would also return it

**Comment by vprelovac** [comment]
Roger. What does trafilatura use internally for extraction? Readability is pretty much the standard so wondering what you use to get better results?

**Comment by adbar** [comment]
Trafilatura uses its own extraction algorithm and takes advantage of readability-lxml and justext as fallbacks. In the end the combination provides better coverage, while the integrated filters yield better precision.

**Comment by adbar** [comment]
Hi @vprelovac, the library now allows for passing response objects to the extraction (see 615ca8c91fdddd921436eb7514e48be3f13294ab), here is how to use it:

```
from trafilatura import fetch_url, bare_extraction
response = fetch_url(url, decode=False)
bare_extraction(response, url=response.geturl())
```

It should work with the latest version from the repository. I will add it to the docs shortly.

**Comment by vprelovac** [comment]
Fantastic, you are really a prolific creator of useful stuff.

Your library is used here http://teclis.com hope you like it!

**Comment by adbar** [comment]
That's good to know, thanks!
