### ISSUE TITLE
I can't extract main content from this html,could anyone help me?

### ISSUE THREAD

**Issue by CNXDZS** [adbar/trafilatura#702]
url:https://www.jesc.or.jp/training/tabid/141/Default.aspx
my code is :
html_markdown = extract(html_content, include_comments=False, include_tables=True,
                                   favor_precision=False,
                                   no_fallback=True, output_format="markdown")
I can't extract main content from this html,are there some parameters that I haven't set correctly?

**Comment by adbar** [comment]
Hi @CNXDZS, I cannot reproduce the bug, changing parameters like `no_fallback` affects the output a bit but there is text.
