### ISSUE TITLE
extract function runs indefinitely on large HTML body content

### ISSUE THREAD

**Issue by hitesh1997** [adbar/trafilatura#704]
When using the extract function from Trafilatura on extremely large body content (e.g., over a million rows(attached screenshot), as in the case of the URL: https://www.manga-sanctuary.com/fiche_serie_personnages.php), the extraction process runs indefinitely without stopping. This behavior can severely impact performance and resource management in situations where large datasets need to be processed.

Although I noticed there is an EXTRACTION_TIMEOUT parameter mentioned in the documentation, it seems to work only in the command line and doesn’t raise timeout errors when using the extract function directly in Python code. 

<img width="1072" alt="Screenshot 2024-09-30 at 7 28 55 PM" src="https://github.com/user-attachments/assets/4a1baee3-aa85-4894-b949-9fbded36adcc">

`extraction_result = extract(
    body,
    deduplicate=args.deduplicate,
    favor_precision=args.favor_precision,
    favor_recall=args.favor_recall,
    include_comments=args.include_comments,
    include_tables=args.include_tables,
    no_fallback=args.no_fallback,
    with_metadata=args.with_metadata,
    output_format="json",
)`

Would it be possible to implement a timeout mechanism for the extract function, allowing us to raise timeout errors in such scenarios? If there’s an existing solution that can be integrated into the code, please provide some guidance on how to apply it outside of the command line usage.

**Comment by adbar** [comment]
Hi @hitesh1997, there was such a timeout function but the underlying `signal` library prevents use of the extract function in certain contexts, see #202 for details.

You can write a wrapper around the extract function to set your own timeout.
