### ISSUE TITLE
User Agent

### ISSUE THREAD

**Issue by tonifergue** [adbar/trafilatura#73]
Hi, congrats for your library. I would like to ask you about the user agent, I have problems with a lot of webs, but with others libraries works fine. I prefer to use trafilatura because give me what I need. 

I have added my own user agent to your code, but it still doesn't work: 

DEFAULT_HEADERS = {
    'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0',#USER_AGENT,
}

Please, Can you recomend me a nice configuration on this part?
Thanks, Grazie

**Comment by adbar** [comment]
Hi @tonifergue, you need to specify your user agent in a custom [settings.cfg](https://github.com/adbar/trafilatura/blob/master/trafilatura/settings.cfg) file, then you can apply the changes by parsing it beforehand and using the `config` argument:

```
from trafilatura.settings import use_config
myconfig = use_config('path/to/myfile')
fetch_url(url, config=myconfig)
```

Thanks for your feedback, I will clarify the docs on this point.

**Comment by tonifergue** [comment]
Thank you very much.
