### ISSUE TITLE
CLI downloads: make sure all user-specified options are used

### ISSUE THREAD

**Issue by andyskipper** [adbar/trafilatura#732]
Using this URL: 
`https://andrewwinnicki.medium.com/people-with-high-tolerance-for-ambiguity-or-high-need-for-closure-406a8445726d`

It looks like there are two 301 redirects happening - I'm using a config file with 
`max_redirects = 5`

Results in this exception, but silently returns Nothing:

`ERROR:trafilatura.downloads:download error: https://andrewwinnicki.medium.com/people-with-high-tolerance-for-ambiguity-or-high-need-for-closure-406a8445726d HTTPSConnectionPool(host='medium.com', port=443): Max retries exceeded with url: https://medium.com/m/global-identity-2?redirectUrl=https%3A%2F%2Flevelup.gitconnected.com%2Fpeople-with-high-tolerance-for-ambiguity-or-high-need-for-closure-406a8445726d (Caused by ResponseError('too many redirects'))
WARNING:trafilatura.cli_utils:No result for URL: https://andrewwinnicki.medium.com/people-with-high-tolerance-for-ambiguity-or-high-need-for-closure-406a8445726d`

**Comment by andyskipper** [comment]
This is the cli command:
`trafilatura -u "https://andrewwinnicki.medium.com/people-with-high-tolerance-for-ambiguity-or-high-need-for-closure-406a8445726d" --verbose --config-file config.cfg`

This is the contents of config.cfg:
`[DEFAULT]
download_timeout = 30
max_file_size = 20000000
min_file_size = 10
sleep_time = 5
user_agents =
cookie =
max_redirects = 5
min_extracted_size = 250
min_extracted_comm_size = 1
min_output_size = 1
min_output_comm_size = 1
extraction_timeout = 30
min_duplcheck_size = 100
max_repetitions = 2
extensive_date_search = on
external_urls = off`

**Comment by adbar** [comment]
Trafilatura's download utility will deal with most cases but not all and I suspect that medium.com is protecting itself against scrapers, so that more complex ways are needed. See the [troubleshooting section of the docs](https://trafilatura.readthedocs.io/en/latest/troubleshooting.html) for ideas.

**Comment by andyskipper** [comment]
Just confirmed, this is an issue with the CLI alone, changing the MAX_REDIRECTS value in a Python script results in the fetch_url function working correctly.

I believe the problem is specific to the --config-file argument to the CLI tool.

**Comment by adbar** [comment]
Thanks for the additional details, the issue is actually related to #703, there is a mismatch between the old `config` and the new `options` in CLI downloads.
