### ISSUE TITLE
Extracting full text from an URL returns None

### ISSUE THREAD

**Issue by vrnch** [adbar/trafilatura#739]
```python
import trafilatura 

url = 'https://venturebeat.com/ai/moondream-raises-4-5m-to-prove-that-smaller-ai-models-can-still-pack-a-punch/'
download = trafilatura.fetch_url(url=url)
article = trafilatura.extract(download)

print(article)
```

```bash
None
```

**Comment by vrnch** [comment]
`https://www.hoteliermagazine.com/robots-are-the-future-of-hospitality-in-canada/` same

**Comment by adbar** [comment]
These pages appear to be protected against straight downloads. Please check the [troubleshooting section of the docs](https://trafilatura.readthedocs.io/en/latest/troubleshooting.html) for more ideas.
