### ISSUE TITLE
AttributeError in prune_unwanted_nodes

### ISSUE THREAD

**Issue by PLPeeters** [adbar/trafilatura#760]
I'm running into an `AttributeError` both with version 1.12.2 and 2.0.0, for which I isolated the following minimal reproduction:

```
Python 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import trafilatura
>>> from lxml import html
>>> trafilatura.__version__
'2.0.0'
>>> tree = html.fromstring('<html></html><!-- comment -->')
>>> trafilatura.extract(tree, prune_xpath='//comment()')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/lib/python3.12/site-packages/trafilatura/core.py", line 462, in extract
    document = bare_extraction(
               ^^^^^^^^^^^^^^^^
  File "[...]/lib/python3.12/site-packages/trafilatura/core.py", line 277, in bare_extraction
    tree = prune_unwanted_nodes(tree, [XPath(x) for x in prune_xpath])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/lib/python3.12/site-packages/trafilatura/htmlprocessing.py", line 112, in prune_unwanted_nodes
    subtree.getparent().remove(subtree)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'remove'
```

Looking into this, I found #667 and noticed that for some reason `prune_unwanted_nodes` is still using `getparent().remove()` instead of using `delete_element()`, which seems to be how you fixed this the first time around:

https://github.com/adbar/trafilatura/blob/c6e834030779f0fb59aa3888c2f3222101bbdd0f/trafilatura/htmlprocessing.py#L112

Could you look into this?

**Comment by adbar** [comment]
@PLPeeters Thanks for the detailed bug report! I believe you found the culprit, using `delete_element()` should do the trick. Are you interested in drafting a pull request?

**Comment by PLPeeters** [comment]
@adbar Sure, will do!
