### ISSUE TITLE
Trafilatura duplicating text

### ISSUE THREAD

**Issue by cta2106** [adbar/trafilatura#81]
Issue described [here](https://stackoverflow.com/questions/67812700/has-anyone-experience-issues-with-duplicated-text-while-using-trafilatura)

**Comment by adbar** [comment]
Hi @cta2106, this has to do with the maximum number of allowed duplicates.

The threshold is set to 2 by default, you can change it in `settings.cfg`:
`MAX_REPETITIONS = 1`

See the [docs on customization](https://trafilatura.readthedocs.io/en/latest/usage-python.html?highlight=settings.cfg#id1) for more info.

**Comment by cta2106** [comment]
Hi @adbar, I tried that and it didn't work, unfortunately. Any idea why this behavior is occurring? There are no duplications in the [page html](https://www.federalreserve.gov/monetarypolicy/fomcminutes20200429.htm). Thanks in advance for your help - this library is amazing!

**Comment by adbar** [comment]
Hi @cta2106, thanks for your feedback!

I cannot reproduce the bug, I don't get duplicate elements like "Staff Economic Outlook" or "By notation vote completed on". Could you please be more precise about the way you extract the text? Is it with Python or on the command-line? Which lines of code did you run to get this result?

Furthermore there is a mismatch between the URL you mention above and the text you quote on stackoverflow, it cannot be "By notation vote completed on May 19, 2020" because the document is from April 2020.

**Comment by cta2106** [comment]
Thanks again for being so responsive and helpful. Here's an example of weird behavior that I noticed:

```
import trafilatura

URL = 'https://www.federalreserve.gov/monetarypolicy/fomcminutes20160727.htm'
downloaded = trafilatura.fetch_url(URL)
text = trafilatura.extract(
    downloaded,
    include_comments=False,
    output_format="txt",
    include_tables=True,
    include_images=False,
    include_formatting=False,
    deduplicate=True,
)
print(text)
```
One duplicated fragment is the following:

`Domestic financial conditions remained accommodative over the intermeeting period. Equity price indexes increased, on net, despite an initial sharp decline following the Brexit vote, and corporate bond spreads declined on balance. Conditions in business and consumer credit markets were about unchanged`

Another chunk:

`In their discussion of monetary policy for the period ahead, members judged that the information received since the Committee met in June indicated that the labor market had strengthened and that economic activity had been expanding at a moderate rate. They noted that the most recent employment report showed that job gains had been strong in June following weak growth in May, and, on balance, payrolls and other labor market indicators pointed to some increase in labor utilization in recent months. Members agreed that household spending had been growing strongly but business fixed investment had been soft. Inflation continued to run below the Committee's 2 percent longer-run objective, partly reflecting earlier declines in energy prices and in prices of non-energy imports. Market-based measures of inflation compensation remained low over the intermeeting period, and most survey-based measures of longer-term inflation expectations were, on balance, little changed.`

**Comment by cta2106** [comment]
I managed to get rid of some duplication by setting `include_tables=False` in the snippet above. However, this doesn't work for `URL = 'https://www.federalreserve.gov/monetarypolicy/fomcminutes20180131.htm'`.  Some duplications:

`By unanimous vote, the Federal Reserve Bank of New York was selected to execute transactions for the System Open Market Account (SOMA).`


`(As reaffirmed effective January 30, 2018)`


`(As amended effective January 30, 2018)`

`The staff presented three briefings on inflation analysis and forecasting. The presentations reviewed a number of commonly used structural and reduced-form models. These included structural models in which the rate of inflation is linked importantly to measures of resource slack and a measure of expected inflation relevant for wage and price setting--so-called Phillips curve specifications--as well as statistical models in which inflation is primarily determined by a time-varying inflation trend or longer-run inflation expectations. The briefings noted several factors beyond those captured in the models that appeared to have put downward pressure on prices in recent years. These included structural changes in price setting for some items, such as medical care, and the effects of idiosyncratic price shocks, such as the unusual drop in prices of wireless telephone services in 2017. The staff found little compelling evidence for the possible influence of other factors such as a more competitive pricing environment or a change in the markup of prices over unit labor costs. Overall, for the set of models presented, the prediction errors in recent years were larger than those observed during the 2001-07 period but were consistent with historical norms and, in most models, did not appear to be biased.`

**Comment by adbar** [comment]
Hi @cta2106, I understand now, it's a bug I need to look into.

**Comment by adbar** [comment]
Hi @cta2106, good catch! A line of code to handle such cases had gone missing. The case should be solved now.

Text parts like "As reaffirmed effective January 30" are true duplicates as they occur twice in the text, so the fix doesn't affect them.

**Comment by cta2106** [comment]
Amazing, @adbar, I cannot thank you enough.
