### ISSUE TITLE
Exception in trafilatura.spider  focused_crawler

### ISSUE THREAD

**Issue by saadali96** [adbar/trafilatura#84]
When there is an error on any sub URL in the focused crawler it throws an error and exits. Excepted functionality should be if there is an error on one page ignore that page, crawl the rest and then return URLs of successful pages only. Right now it returns an empty set in case of error. 

Am I doing something wrong or is this how the implementation is done?

**Comment by adbar** [comment]
Hi @saadali96, can you please describe the type of error that you run into?

The focused crawler is still experimental, as you say it would be more robust if it just skips pages where problems arise.

**Comment by adbar** [comment]
Hi @saadali96, any feedback on this? I'd like to know which kind of error you got.

**Comment by saadali96** [comment]
hi @adbar , 

It was an error ( null value found ),  then the list that is returned is empty without any URL. My best guess is that once an exception occurs in one specific URL's the rest of the URLs are also not returned. I will try to replicate and give an exact screenshot of the issue.

**Comment by adbar** [comment]
Hi @saadali96, I need to know the error type (e.g. `AttributeError`) and the line where it happens. I'd rather not write a general `try...except` without understanding what's going on.

**Comment by adbar** [comment]
I'm assuming the problem has been solved in the commit above.
