### ISSUE TITLE
Articles without date, or with date without id, class or props

### ISSUE THREAD

**Issue by felipehertzer** [adbar/trafilatura#96]
Is the date really mandatory to extract the file? can we create a regex to fetch dates in html?

Here is an example where the article has a date but it is difficult to find it without the regex.
[Example](https://www.cis.org.au/commentary/articles/the-gilded-cage-down-under/)

**Comment by adbar** [comment]
@felipehertzer The date is only necessary if the parameter `only_with_metadata` is set to `True`.

In your example I would say that htmldate's logic is to find several occurrences of `/2021/07/` (here in URLs) and deduce that the article is from July 2021.
Pushing the granularity to the very day (the 9th) doesn't seem doable with a generic approach, or only at the cost of looking for regexes in the whole page, which comes at a computational cost. Nonetheless, it's what htmldate's extensive mode is about.

**Comment by felipehertzer** [comment]
After correcting the date search, it is now working perfectly. Thanks.
