### ISSUE TITLE
[trafilatura.core] INFO: discarding data for url: None

### ISSUE THREAD

**Issue by phongtnit** [adbar/trafilatura#98]
Hi,

These urls cannot extract content because of `[trafilatura.core] INFO: discarding data for url: None`

Tested on urls:
```
https://www.biblestudy.org/bibleref/meaning-of-numbers-in-bible/17.html
https://www.biblestudytools.com/revelation/17.html
https://affinitynumerology.com/number-meanings/number-1-meaning.php
```

Sample code:
```
url = 'https://www.biblestudy.org/bibleref/meaning-of-numbers-in-bible/17.html'

downloaded = trafilatura.fetch_url(url)
result = bare_extraction(downloaded, output_format='xml', no_fallback=True, include_tables=True, include_images=True,
                         include_formatting=True, with_metadata=True, include_links=True)

if result and result['body'] is not None:
    print(etree.tostring(result['body'], pretty_print=True))
```

**Comment by adbar** [comment]
Hi @phongtnit, please refer to #75, and please note that `with_metadata` is ambiguous, it will be replaced by `only_with_metadata` in the future.

**Comment by phongtnit** [comment]
Hi @adbar thanks for your info, I added `url` param on `bare_extraction` function but there is the same error.

Sample code:
```
url = 'https://www.biblestudy.org/bibleref/meaning-of-numbers-in-bible/17.html'

downloaded = trafilatura.fetch_url(url)
result = bare_extraction(downloaded, output_format='xml', no_fallback=True, include_tables=True, include_images=True,
                         include_formatting=True, only_with_metadata=True, include_links=True, url=url)

if result and result['body'] is not None:
    print(etree.tostring(result['body'], pretty_print=True))
    print('\n\r')
```

**Comment by adbar** [comment]
Hi @phongtnit, I see, it's because the date extraction fails for this webpage.

`only_with_metadata` specifies that title, URL and date have to be present, if one of them is missing (here the date) then nothing is returned.
If you set the parameter to `False` you'll get an output.

**Comment by adbar** [comment]
Hi @phongtnit, I believe the problem has been addressed by my answer and by recent commits. If you still run into a bug you can re-open the issue.
