### ISSUE TITLE
Parse JSON-LD information and write heuristics to decide where to draw info from

### ISSUE THREAD

**Issue by adbar** [adbar/trafilatura#99]
JSON info (metadata or content) can be parsed with Python's `JSON` module, however this is not to be trusted systematically:

- [x] Parse and store JSON-LD info
- [x] Use it for certain metadata if it fits
- [x] Replace the backup content extraction with it

**Comment by felipehertzer** [comment]
I started the development of JSON-LD parse, the results are good, it will solve half of the author problems that we have.

**Comment by adbar** [comment]
Other useful schema.org metadata as mentioned by @felipehertzer:

```
Organization/Url
NewsArticle/mainEntityOfPage/WebPage - URL of Page
NewsArticle/keywords
```

As well as optionally `NewsArticle/articleBody` which is tackled by regex so far.

**Comment by adbar** [comment]
The main content is now extracted with the standard JSON parser when everything else fails (#619).
